constant(int_1,int).
constant(int_2,int).
constant(int_0,int).
constant(int_5,int).
constant(int_3,int).
constant(int_6,int).
constant(int_7,int).
constant(int_4,int).
head_pred(label,2).
body_pred(perm_android_permission_access_network_state,2).
body_pred(n_permissions,2).
body_pred(n_used_permissions,2).
body_pred(n_api_calls,2).
body_pred(suspicious_getsystemservice,2).
body_pred(suspicious_base64,2).
body_pred(n_urls,2).
body_pred(suspicious_getpackageinfo,2).
body_pred(suspicious_getexternalstoragedirectory,2).
body_pred(suspicious_ljava_lang_system___loadlibrary,2).
body_pred(suspicious_ljava_lang_system___load,2).
body_pred(suspicious_getdeviceid,2).
body_pred(n_services,2).
body_pred(intent_android_intent_action_boot_completed,2).
body_pred(perm_android_permission_read_external_storage,2).
body_pred(suspicious_cipher,2).
body_pred(n_activities,2).
body_pred(perm_android_permission_access_coarse_location,2).
body_pred(perm_android_permission_record_audio,2).
body_pred(perm_com_android_vending_billing,2).
body_pred(perm_android_permission_access_wifi_state,2).
body_pred(intent_android_intent_action_view,2).
body_pred(suspicious_ljava_lang_runtime___exec,2).
body_pred(perm_android_permission_modify_audio_settings,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(perm_android_permission_nfc,2).
body_pred(intent_com_taobao_accs_intent_action_start_from_agoo,2).
body_pred(perm_com_yulong_android_launcher_permission_read_settings,2).
body_pred(perm_android_permission_set_debug_app,2).
body_pred(intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start,2).
type(label,(ex,int)).
type(perm_android_permission_access_network_state,(ex,int)).
type(n_permissions,(ex,int)).
type(n_used_permissions,(ex,int)).
type(n_api_calls,(ex,int)).
type(suspicious_getsystemservice,(ex,int)).
type(suspicious_base64,(ex,int)).
type(n_urls,(ex,int)).
type(suspicious_getpackageinfo,(ex,int)).
type(suspicious_getexternalstoragedirectory,(ex,int)).
type(suspicious_ljava_lang_system___loadlibrary,(ex,int)).
type(suspicious_ljava_lang_system___load,(ex,int)).
type(suspicious_getdeviceid,(ex,int)).
type(n_services,(ex,int)).
type(intent_android_intent_action_boot_completed,(ex,int)).
type(perm_android_permission_read_external_storage,(ex,int)).
type(suspicious_cipher,(ex,int)).
type(n_activities,(ex,int)).
type(perm_android_permission_access_coarse_location,(ex,int)).
type(perm_android_permission_record_audio,(ex,int)).
type(perm_com_android_vending_billing,(ex,int)).
type(perm_android_permission_access_wifi_state,(ex,int)).
type(intent_android_intent_action_view,(ex,int)).
type(suspicious_ljava_lang_runtime___exec,(ex,int)).
type(perm_android_permission_modify_audio_settings,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(perm_android_permission_nfc,(ex,int)).
type(intent_com_taobao_accs_intent_action_start_from_agoo,(ex,int)).
type(perm_com_yulong_android_launcher_permission_read_settings,(ex,int)).
type(perm_android_permission_set_debug_app,(ex,int)).
type(intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
