int_0(0).
int_1(1).
int_2(2).
int_3(3).
int_4(4).
int_5(5).
int_6(6).
int_7(7).
intent_android_intent_action_boot_completed(0,0).
intent_android_intent_action_boot_completed(1,0).
intent_android_intent_action_boot_completed(10,0).
intent_android_intent_action_boot_completed(11,0).
intent_android_intent_action_boot_completed(12,0).
intent_android_intent_action_boot_completed(13,0).
intent_android_intent_action_boot_completed(14,0).
intent_android_intent_action_boot_completed(15,0).
intent_android_intent_action_boot_completed(16,0).
intent_android_intent_action_boot_completed(17,0).
intent_android_intent_action_boot_completed(18,0).
intent_android_intent_action_boot_completed(19,0).
intent_android_intent_action_boot_completed(2,0).
intent_android_intent_action_boot_completed(20,0).
intent_android_intent_action_boot_completed(21,0).
intent_android_intent_action_boot_completed(22,0).
intent_android_intent_action_boot_completed(23,0).
intent_android_intent_action_boot_completed(24,1).
intent_android_intent_action_boot_completed(25,0).
intent_android_intent_action_boot_completed(26,0).
intent_android_intent_action_boot_completed(27,0).
intent_android_intent_action_boot_completed(28,0).
intent_android_intent_action_boot_completed(29,0).
intent_android_intent_action_boot_completed(3,0).
intent_android_intent_action_boot_completed(30,0).
intent_android_intent_action_boot_completed(31,0).
intent_android_intent_action_boot_completed(32,0).
intent_android_intent_action_boot_completed(33,0).
intent_android_intent_action_boot_completed(34,0).
intent_android_intent_action_boot_completed(35,0).
intent_android_intent_action_boot_completed(36,0).
intent_android_intent_action_boot_completed(37,0).
intent_android_intent_action_boot_completed(38,0).
intent_android_intent_action_boot_completed(39,0).
intent_android_intent_action_boot_completed(4,0).
intent_android_intent_action_boot_completed(40,0).
intent_android_intent_action_boot_completed(41,0).
intent_android_intent_action_boot_completed(42,0).
intent_android_intent_action_boot_completed(43,0).
intent_android_intent_action_boot_completed(5,0).
intent_android_intent_action_boot_completed(6,0).
intent_android_intent_action_boot_completed(7,0).
intent_android_intent_action_boot_completed(8,0).
intent_android_intent_action_boot_completed(9,0).
intent_android_intent_action_view(0,0).
intent_android_intent_action_view(1,0).
intent_android_intent_action_view(10,0).
intent_android_intent_action_view(11,0).
intent_android_intent_action_view(12,0).
intent_android_intent_action_view(13,0).
intent_android_intent_action_view(14,0).
intent_android_intent_action_view(15,0).
intent_android_intent_action_view(16,0).
intent_android_intent_action_view(17,0).
intent_android_intent_action_view(18,0).
intent_android_intent_action_view(19,0).
intent_android_intent_action_view(2,0).
intent_android_intent_action_view(20,0).
intent_android_intent_action_view(21,0).
intent_android_intent_action_view(22,0).
intent_android_intent_action_view(23,0).
intent_android_intent_action_view(24,0).
intent_android_intent_action_view(25,0).
intent_android_intent_action_view(26,0).
intent_android_intent_action_view(27,0).
intent_android_intent_action_view(28,0).
intent_android_intent_action_view(29,0).
intent_android_intent_action_view(3,0).
intent_android_intent_action_view(30,0).
intent_android_intent_action_view(31,0).
intent_android_intent_action_view(32,0).
intent_android_intent_action_view(33,0).
intent_android_intent_action_view(34,0).
intent_android_intent_action_view(35,0).
intent_android_intent_action_view(36,0).
intent_android_intent_action_view(37,0).
intent_android_intent_action_view(38,0).
intent_android_intent_action_view(39,0).
intent_android_intent_action_view(4,0).
intent_android_intent_action_view(40,0).
intent_android_intent_action_view(41,0).
intent_android_intent_action_view(42,0).
intent_android_intent_action_view(43,0).
intent_android_intent_action_view(5,0).
intent_android_intent_action_view(6,0).
intent_android_intent_action_view(7,0).
intent_android_intent_action_view(8,0).
intent_android_intent_action_view(9,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(0,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(1,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(10,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(11,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(12,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(13,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(14,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(15,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(16,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(17,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(18,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(19,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(2,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(20,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(21,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(22,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(23,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(24,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(25,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(26,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(27,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(28,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(29,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(3,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(30,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(31,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(32,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(33,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(34,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(35,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(36,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(37,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(38,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(39,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(4,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(40,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(41,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(42,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(43,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(5,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(6,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(7,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(8,0).
intent_com_qihoo360_mobilesafe_pcdaemon_sms_restore_start(9,0).
intent_com_taobao_accs_intent_action_start_from_agoo(0,0).
intent_com_taobao_accs_intent_action_start_from_agoo(1,0).
intent_com_taobao_accs_intent_action_start_from_agoo(10,0).
intent_com_taobao_accs_intent_action_start_from_agoo(11,0).
intent_com_taobao_accs_intent_action_start_from_agoo(12,0).
intent_com_taobao_accs_intent_action_start_from_agoo(13,0).
intent_com_taobao_accs_intent_action_start_from_agoo(14,0).
intent_com_taobao_accs_intent_action_start_from_agoo(15,0).
intent_com_taobao_accs_intent_action_start_from_agoo(16,0).
intent_com_taobao_accs_intent_action_start_from_agoo(17,0).
intent_com_taobao_accs_intent_action_start_from_agoo(18,0).
intent_com_taobao_accs_intent_action_start_from_agoo(19,0).
intent_com_taobao_accs_intent_action_start_from_agoo(2,0).
intent_com_taobao_accs_intent_action_start_from_agoo(20,0).
intent_com_taobao_accs_intent_action_start_from_agoo(21,0).
intent_com_taobao_accs_intent_action_start_from_agoo(22,0).
intent_com_taobao_accs_intent_action_start_from_agoo(23,0).
intent_com_taobao_accs_intent_action_start_from_agoo(24,0).
intent_com_taobao_accs_intent_action_start_from_agoo(25,0).
intent_com_taobao_accs_intent_action_start_from_agoo(26,0).
intent_com_taobao_accs_intent_action_start_from_agoo(27,0).
intent_com_taobao_accs_intent_action_start_from_agoo(28,0).
intent_com_taobao_accs_intent_action_start_from_agoo(29,0).
intent_com_taobao_accs_intent_action_start_from_agoo(3,0).
intent_com_taobao_accs_intent_action_start_from_agoo(30,0).
intent_com_taobao_accs_intent_action_start_from_agoo(31,0).
intent_com_taobao_accs_intent_action_start_from_agoo(32,0).
intent_com_taobao_accs_intent_action_start_from_agoo(33,0).
intent_com_taobao_accs_intent_action_start_from_agoo(34,0).
intent_com_taobao_accs_intent_action_start_from_agoo(35,0).
intent_com_taobao_accs_intent_action_start_from_agoo(36,0).
intent_com_taobao_accs_intent_action_start_from_agoo(37,0).
intent_com_taobao_accs_intent_action_start_from_agoo(38,0).
intent_com_taobao_accs_intent_action_start_from_agoo(39,0).
intent_com_taobao_accs_intent_action_start_from_agoo(4,0).
intent_com_taobao_accs_intent_action_start_from_agoo(40,0).
intent_com_taobao_accs_intent_action_start_from_agoo(41,0).
intent_com_taobao_accs_intent_action_start_from_agoo(42,0).
intent_com_taobao_accs_intent_action_start_from_agoo(43,0).
intent_com_taobao_accs_intent_action_start_from_agoo(5,0).
intent_com_taobao_accs_intent_action_start_from_agoo(6,0).
intent_com_taobao_accs_intent_action_start_from_agoo(7,0).
intent_com_taobao_accs_intent_action_start_from_agoo(8,0).
intent_com_taobao_accs_intent_action_start_from_agoo(9,0).
n_activities(0,1).
n_activities(1,2).
n_activities(10,1).
n_activities(11,1).
n_activities(12,1).
n_activities(13,4).
n_activities(14,2).
n_activities(15,2).
n_activities(16,1).
n_activities(17,1).
n_activities(18,1).
n_activities(19,2).
n_activities(2,1).
n_activities(20,1).
n_activities(21,1).
n_activities(22,1).
n_activities(23,2).
n_activities(24,1).
n_activities(25,2).
n_activities(26,1).
n_activities(27,1).
n_activities(28,1).
n_activities(29,3).
n_activities(3,1).
n_activities(30,1).
n_activities(31,1).
n_activities(32,1).
n_activities(33,1).
n_activities(34,1).
n_activities(35,1).
n_activities(36,1).
n_activities(37,1).
n_activities(38,1).
n_activities(39,3).
n_activities(4,1).
n_activities(40,1).
n_activities(41,2).
n_activities(42,1).
n_activities(43,1).
n_activities(5,1).
n_activities(6,1).
n_activities(7,1).
n_activities(8,1).
n_activities(9,1).
n_api_calls(0,0).
n_api_calls(1,2).
n_api_calls(10,0).
n_api_calls(11,4).
n_api_calls(12,0).
n_api_calls(13,0).
n_api_calls(14,3).
n_api_calls(15,3).
n_api_calls(16,1).
n_api_calls(17,1).
n_api_calls(18,0).
n_api_calls(19,2).
n_api_calls(2,2).
n_api_calls(20,0).
n_api_calls(21,2).
n_api_calls(22,4).
n_api_calls(23,4).
n_api_calls(24,0).
n_api_calls(25,0).
n_api_calls(26,0).
n_api_calls(27,0).
n_api_calls(28,3).
n_api_calls(29,1).
n_api_calls(3,0).
n_api_calls(30,1).
n_api_calls(31,1).
n_api_calls(32,3).
n_api_calls(33,1).
n_api_calls(34,1).
n_api_calls(35,2).
n_api_calls(36,2).
n_api_calls(37,1).
n_api_calls(38,3).
n_api_calls(39,2).
n_api_calls(4,1).
n_api_calls(40,0).
n_api_calls(41,0).
n_api_calls(42,1).
n_api_calls(43,3).
n_api_calls(5,0).
n_api_calls(6,3).
n_api_calls(7,3).
n_api_calls(8,0).
n_api_calls(9,0).
n_permissions(0,2).
n_permissions(1,5).
n_permissions(10,1).
n_permissions(11,3).
n_permissions(12,0).
n_permissions(13,0).
n_permissions(14,2).
n_permissions(15,3).
n_permissions(16,1).
n_permissions(17,7).
n_permissions(18,1).
n_permissions(19,1).
n_permissions(2,2).
n_permissions(20,2).
n_permissions(21,2).
n_permissions(22,5).
n_permissions(23,4).
n_permissions(24,3).
n_permissions(25,1).
n_permissions(26,2).
n_permissions(27,0).
n_permissions(28,3).
n_permissions(29,3).
n_permissions(3,5).
n_permissions(30,1).
n_permissions(31,0).
n_permissions(32,0).
n_permissions(33,1).
n_permissions(34,3).
n_permissions(35,3).
n_permissions(36,1).
n_permissions(37,2).
n_permissions(38,0).
n_permissions(39,3).
n_permissions(4,0).
n_permissions(40,3).
n_permissions(41,3).
n_permissions(42,1).
n_permissions(43,2).
n_permissions(5,2).
n_permissions(6,0).
n_permissions(7,2).
n_permissions(8,6).
n_permissions(9,7).
n_services(0,0).
n_services(1,0).
n_services(10,1).
n_services(11,0).
n_services(12,0).
n_services(13,0).
n_services(14,0).
n_services(15,0).
n_services(16,0).
n_services(17,0).
n_services(18,0).
n_services(19,0).
n_services(2,0).
n_services(20,0).
n_services(21,0).
n_services(22,0).
n_services(23,0).
n_services(24,1).
n_services(25,0).
n_services(26,0).
n_services(27,1).
n_services(28,0).
n_services(29,0).
n_services(3,0).
n_services(30,0).
n_services(31,0).
n_services(32,0).
n_services(33,0).
n_services(34,0).
n_services(35,0).
n_services(36,0).
n_services(37,0).
n_services(38,0).
n_services(39,0).
n_services(4,0).
n_services(40,0).
n_services(41,0).
n_services(42,0).
n_services(43,0).
n_services(5,0).
n_services(6,0).
n_services(7,0).
n_services(8,0).
n_services(9,0).
n_urls(0,0).
n_urls(1,0).
n_urls(10,0).
n_urls(11,0).
n_urls(12,0).
n_urls(13,2).
n_urls(14,2).
n_urls(15,4).
n_urls(16,1).
n_urls(17,0).
n_urls(18,0).
n_urls(19,3).
n_urls(2,1).
n_urls(20,1).
n_urls(21,1).
n_urls(22,1).
n_urls(23,0).
n_urls(24,0).
n_urls(25,1).
n_urls(26,5).
n_urls(27,0).
n_urls(28,1).
n_urls(29,1).
n_urls(3,1).
n_urls(30,1).
n_urls(31,0).
n_urls(32,1).
n_urls(33,1).
n_urls(34,1).
n_urls(35,3).
n_urls(36,1).
n_urls(37,0).
n_urls(38,0).
n_urls(39,4).
n_urls(4,0).
n_urls(40,1).
n_urls(41,0).
n_urls(42,1).
n_urls(43,1).
n_urls(5,1).
n_urls(6,0).
n_urls(7,1).
n_urls(8,1).
n_urls(9,1).
n_used_permissions(0,0).
n_used_permissions(1,2).
n_used_permissions(10,0).
n_used_permissions(11,3).
n_used_permissions(12,0).
n_used_permissions(13,0).
n_used_permissions(14,2).
n_used_permissions(15,2).
n_used_permissions(16,1).
n_used_permissions(17,1).
n_used_permissions(18,0).
n_used_permissions(19,2).
n_used_permissions(2,2).
n_used_permissions(20,0).
n_used_permissions(21,2).
n_used_permissions(22,2).
n_used_permissions(23,3).
n_used_permissions(24,0).
n_used_permissions(25,0).
n_used_permissions(26,0).
n_used_permissions(27,0).
n_used_permissions(28,2).
n_used_permissions(29,1).
n_used_permissions(3,0).
n_used_permissions(30,1).
n_used_permissions(31,1).
n_used_permissions(32,2).
n_used_permissions(33,1).
n_used_permissions(34,1).
n_used_permissions(35,1).
n_used_permissions(36,1).
n_used_permissions(37,1).
n_used_permissions(38,2).
n_used_permissions(39,2).
n_used_permissions(4,1).
n_used_permissions(40,0).
n_used_permissions(41,0).
n_used_permissions(42,1).
n_used_permissions(43,2).
n_used_permissions(5,0).
n_used_permissions(6,3).
n_used_permissions(7,2).
n_used_permissions(8,0).
n_used_permissions(9,0).
perm_android_permission_access_coarse_location(0,0).
perm_android_permission_access_coarse_location(1,0).
perm_android_permission_access_coarse_location(10,0).
perm_android_permission_access_coarse_location(11,0).
perm_android_permission_access_coarse_location(12,0).
perm_android_permission_access_coarse_location(13,0).
perm_android_permission_access_coarse_location(14,0).
perm_android_permission_access_coarse_location(15,0).
perm_android_permission_access_coarse_location(16,0).
perm_android_permission_access_coarse_location(17,1).
perm_android_permission_access_coarse_location(18,0).
perm_android_permission_access_coarse_location(19,0).
perm_android_permission_access_coarse_location(2,0).
perm_android_permission_access_coarse_location(20,0).
perm_android_permission_access_coarse_location(21,0).
perm_android_permission_access_coarse_location(22,0).
perm_android_permission_access_coarse_location(23,0).
perm_android_permission_access_coarse_location(24,0).
perm_android_permission_access_coarse_location(25,0).
perm_android_permission_access_coarse_location(26,0).
perm_android_permission_access_coarse_location(27,0).
perm_android_permission_access_coarse_location(28,0).
perm_android_permission_access_coarse_location(29,0).
perm_android_permission_access_coarse_location(3,0).
perm_android_permission_access_coarse_location(30,0).
perm_android_permission_access_coarse_location(31,0).
perm_android_permission_access_coarse_location(32,0).
perm_android_permission_access_coarse_location(33,0).
perm_android_permission_access_coarse_location(34,1).
perm_android_permission_access_coarse_location(35,0).
perm_android_permission_access_coarse_location(36,0).
perm_android_permission_access_coarse_location(37,0).
perm_android_permission_access_coarse_location(38,0).
perm_android_permission_access_coarse_location(39,0).
perm_android_permission_access_coarse_location(4,0).
perm_android_permission_access_coarse_location(40,0).
perm_android_permission_access_coarse_location(41,0).
perm_android_permission_access_coarse_location(42,0).
perm_android_permission_access_coarse_location(43,0).
perm_android_permission_access_coarse_location(5,0).
perm_android_permission_access_coarse_location(6,0).
perm_android_permission_access_coarse_location(7,0).
perm_android_permission_access_coarse_location(8,0).
perm_android_permission_access_coarse_location(9,0).
perm_android_permission_access_network_state(0,1).
perm_android_permission_access_network_state(1,1).
perm_android_permission_access_network_state(10,0).
perm_android_permission_access_network_state(11,0).
perm_android_permission_access_network_state(12,0).
perm_android_permission_access_network_state(13,0).
perm_android_permission_access_network_state(14,1).
perm_android_permission_access_network_state(15,1).
perm_android_permission_access_network_state(16,0).
perm_android_permission_access_network_state(17,1).
perm_android_permission_access_network_state(18,0).
perm_android_permission_access_network_state(19,0).
perm_android_permission_access_network_state(2,1).
perm_android_permission_access_network_state(20,0).
perm_android_permission_access_network_state(21,0).
perm_android_permission_access_network_state(22,0).
perm_android_permission_access_network_state(23,1).
perm_android_permission_access_network_state(24,0).
perm_android_permission_access_network_state(25,0).
perm_android_permission_access_network_state(26,0).
perm_android_permission_access_network_state(27,0).
perm_android_permission_access_network_state(28,1).
perm_android_permission_access_network_state(29,0).
perm_android_permission_access_network_state(3,1).
perm_android_permission_access_network_state(30,0).
perm_android_permission_access_network_state(31,0).
perm_android_permission_access_network_state(32,0).
perm_android_permission_access_network_state(33,0).
perm_android_permission_access_network_state(34,0).
perm_android_permission_access_network_state(35,0).
perm_android_permission_access_network_state(36,0).
perm_android_permission_access_network_state(37,1).
perm_android_permission_access_network_state(38,0).
perm_android_permission_access_network_state(39,1).
perm_android_permission_access_network_state(4,0).
perm_android_permission_access_network_state(40,0).
perm_android_permission_access_network_state(41,0).
perm_android_permission_access_network_state(42,0).
perm_android_permission_access_network_state(43,1).
perm_android_permission_access_network_state(5,1).
perm_android_permission_access_network_state(6,0).
perm_android_permission_access_network_state(7,0).
perm_android_permission_access_network_state(8,1).
perm_android_permission_access_network_state(9,1).
perm_android_permission_access_wifi_state(0,0).
perm_android_permission_access_wifi_state(1,0).
perm_android_permission_access_wifi_state(10,0).
perm_android_permission_access_wifi_state(11,0).
perm_android_permission_access_wifi_state(12,0).
perm_android_permission_access_wifi_state(13,0).
perm_android_permission_access_wifi_state(14,0).
perm_android_permission_access_wifi_state(15,0).
perm_android_permission_access_wifi_state(16,0).
perm_android_permission_access_wifi_state(17,0).
perm_android_permission_access_wifi_state(18,0).
perm_android_permission_access_wifi_state(19,0).
perm_android_permission_access_wifi_state(2,0).
perm_android_permission_access_wifi_state(20,0).
perm_android_permission_access_wifi_state(21,0).
perm_android_permission_access_wifi_state(22,0).
perm_android_permission_access_wifi_state(23,0).
perm_android_permission_access_wifi_state(24,0).
perm_android_permission_access_wifi_state(25,0).
perm_android_permission_access_wifi_state(26,0).
perm_android_permission_access_wifi_state(27,0).
perm_android_permission_access_wifi_state(28,1).
perm_android_permission_access_wifi_state(29,0).
perm_android_permission_access_wifi_state(3,0).
perm_android_permission_access_wifi_state(30,0).
perm_android_permission_access_wifi_state(31,0).
perm_android_permission_access_wifi_state(32,0).
perm_android_permission_access_wifi_state(33,0).
perm_android_permission_access_wifi_state(34,0).
perm_android_permission_access_wifi_state(35,0).
perm_android_permission_access_wifi_state(36,0).
perm_android_permission_access_wifi_state(37,0).
perm_android_permission_access_wifi_state(38,0).
perm_android_permission_access_wifi_state(39,0).
perm_android_permission_access_wifi_state(4,0).
perm_android_permission_access_wifi_state(40,0).
perm_android_permission_access_wifi_state(41,0).
perm_android_permission_access_wifi_state(42,0).
perm_android_permission_access_wifi_state(43,0).
perm_android_permission_access_wifi_state(5,0).
perm_android_permission_access_wifi_state(6,0).
perm_android_permission_access_wifi_state(7,0).
perm_android_permission_access_wifi_state(8,0).
perm_android_permission_access_wifi_state(9,0).
perm_android_permission_modify_audio_settings(0,0).
perm_android_permission_modify_audio_settings(1,0).
perm_android_permission_modify_audio_settings(10,1).
perm_android_permission_modify_audio_settings(11,0).
perm_android_permission_modify_audio_settings(12,0).
perm_android_permission_modify_audio_settings(13,0).
perm_android_permission_modify_audio_settings(14,0).
perm_android_permission_modify_audio_settings(15,0).
perm_android_permission_modify_audio_settings(16,0).
perm_android_permission_modify_audio_settings(17,0).
perm_android_permission_modify_audio_settings(18,0).
perm_android_permission_modify_audio_settings(19,0).
perm_android_permission_modify_audio_settings(2,0).
perm_android_permission_modify_audio_settings(20,0).
perm_android_permission_modify_audio_settings(21,0).
perm_android_permission_modify_audio_settings(22,1).
perm_android_permission_modify_audio_settings(23,0).
perm_android_permission_modify_audio_settings(24,0).
perm_android_permission_modify_audio_settings(25,0).
perm_android_permission_modify_audio_settings(26,0).
perm_android_permission_modify_audio_settings(27,0).
perm_android_permission_modify_audio_settings(28,0).
perm_android_permission_modify_audio_settings(29,0).
perm_android_permission_modify_audio_settings(3,0).
perm_android_permission_modify_audio_settings(30,0).
perm_android_permission_modify_audio_settings(31,0).
perm_android_permission_modify_audio_settings(32,0).
perm_android_permission_modify_audio_settings(33,0).
perm_android_permission_modify_audio_settings(34,0).
perm_android_permission_modify_audio_settings(35,0).
perm_android_permission_modify_audio_settings(36,0).
perm_android_permission_modify_audio_settings(37,0).
perm_android_permission_modify_audio_settings(38,0).
perm_android_permission_modify_audio_settings(39,0).
perm_android_permission_modify_audio_settings(4,0).
perm_android_permission_modify_audio_settings(40,0).
perm_android_permission_modify_audio_settings(41,0).
perm_android_permission_modify_audio_settings(42,0).
perm_android_permission_modify_audio_settings(43,0).
perm_android_permission_modify_audio_settings(5,0).
perm_android_permission_modify_audio_settings(6,0).
perm_android_permission_modify_audio_settings(7,0).
perm_android_permission_modify_audio_settings(8,0).
perm_android_permission_modify_audio_settings(9,0).
perm_android_permission_nfc(0,0).
perm_android_permission_nfc(1,0).
perm_android_permission_nfc(10,0).
perm_android_permission_nfc(11,0).
perm_android_permission_nfc(12,0).
perm_android_permission_nfc(13,0).
perm_android_permission_nfc(14,0).
perm_android_permission_nfc(15,0).
perm_android_permission_nfc(16,0).
perm_android_permission_nfc(17,0).
perm_android_permission_nfc(18,0).
perm_android_permission_nfc(19,0).
perm_android_permission_nfc(2,0).
perm_android_permission_nfc(20,0).
perm_android_permission_nfc(21,0).
perm_android_permission_nfc(22,0).
perm_android_permission_nfc(23,0).
perm_android_permission_nfc(24,0).
perm_android_permission_nfc(25,0).
perm_android_permission_nfc(26,0).
perm_android_permission_nfc(27,0).
perm_android_permission_nfc(28,0).
perm_android_permission_nfc(29,0).
perm_android_permission_nfc(3,0).
perm_android_permission_nfc(30,0).
perm_android_permission_nfc(31,0).
perm_android_permission_nfc(32,0).
perm_android_permission_nfc(33,0).
perm_android_permission_nfc(34,0).
perm_android_permission_nfc(35,0).
perm_android_permission_nfc(36,0).
perm_android_permission_nfc(37,0).
perm_android_permission_nfc(38,0).
perm_android_permission_nfc(39,0).
perm_android_permission_nfc(4,0).
perm_android_permission_nfc(40,0).
perm_android_permission_nfc(41,0).
perm_android_permission_nfc(42,0).
perm_android_permission_nfc(43,0).
perm_android_permission_nfc(5,0).
perm_android_permission_nfc(6,0).
perm_android_permission_nfc(7,0).
perm_android_permission_nfc(8,0).
perm_android_permission_nfc(9,0).
perm_android_permission_read_external_storage(0,0).
perm_android_permission_read_external_storage(1,1).
perm_android_permission_read_external_storage(10,0).
perm_android_permission_read_external_storage(11,0).
perm_android_permission_read_external_storage(12,0).
perm_android_permission_read_external_storage(13,0).
perm_android_permission_read_external_storage(14,0).
perm_android_permission_read_external_storage(15,0).
perm_android_permission_read_external_storage(16,0).
perm_android_permission_read_external_storage(17,1).
perm_android_permission_read_external_storage(18,0).
perm_android_permission_read_external_storage(19,0).
perm_android_permission_read_external_storage(2,0).
perm_android_permission_read_external_storage(20,0).
perm_android_permission_read_external_storage(21,0).
perm_android_permission_read_external_storage(22,0).
perm_android_permission_read_external_storage(23,0).
perm_android_permission_read_external_storage(24,0).
perm_android_permission_read_external_storage(25,0).
perm_android_permission_read_external_storage(26,0).
perm_android_permission_read_external_storage(27,0).
perm_android_permission_read_external_storage(28,0).
perm_android_permission_read_external_storage(29,0).
perm_android_permission_read_external_storage(3,1).
perm_android_permission_read_external_storage(30,0).
perm_android_permission_read_external_storage(31,0).
perm_android_permission_read_external_storage(32,0).
perm_android_permission_read_external_storage(33,0).
perm_android_permission_read_external_storage(34,0).
perm_android_permission_read_external_storage(35,1).
perm_android_permission_read_external_storage(36,0).
perm_android_permission_read_external_storage(37,0).
perm_android_permission_read_external_storage(38,0).
perm_android_permission_read_external_storage(39,0).
perm_android_permission_read_external_storage(4,0).
perm_android_permission_read_external_storage(40,1).
perm_android_permission_read_external_storage(41,0).
perm_android_permission_read_external_storage(42,0).
perm_android_permission_read_external_storage(43,0).
perm_android_permission_read_external_storage(5,0).
perm_android_permission_read_external_storage(6,0).
perm_android_permission_read_external_storage(7,0).
perm_android_permission_read_external_storage(8,1).
perm_android_permission_read_external_storage(9,1).
perm_android_permission_record_audio(0,0).
perm_android_permission_record_audio(1,0).
perm_android_permission_record_audio(10,0).
perm_android_permission_record_audio(11,0).
perm_android_permission_record_audio(12,0).
perm_android_permission_record_audio(13,0).
perm_android_permission_record_audio(14,0).
perm_android_permission_record_audio(15,0).
perm_android_permission_record_audio(16,0).
perm_android_permission_record_audio(17,0).
perm_android_permission_record_audio(18,0).
perm_android_permission_record_audio(19,0).
perm_android_permission_record_audio(2,0).
perm_android_permission_record_audio(20,0).
perm_android_permission_record_audio(21,0).
perm_android_permission_record_audio(22,1).
perm_android_permission_record_audio(23,0).
perm_android_permission_record_audio(24,0).
perm_android_permission_record_audio(25,0).
perm_android_permission_record_audio(26,0).
perm_android_permission_record_audio(27,0).
perm_android_permission_record_audio(28,0).
perm_android_permission_record_audio(29,0).
perm_android_permission_record_audio(3,0).
perm_android_permission_record_audio(30,0).
perm_android_permission_record_audio(31,0).
perm_android_permission_record_audio(32,0).
perm_android_permission_record_audio(33,0).
perm_android_permission_record_audio(34,0).
perm_android_permission_record_audio(35,0).
perm_android_permission_record_audio(36,0).
perm_android_permission_record_audio(37,0).
perm_android_permission_record_audio(38,0).
perm_android_permission_record_audio(39,0).
perm_android_permission_record_audio(4,0).
perm_android_permission_record_audio(40,0).
perm_android_permission_record_audio(41,0).
perm_android_permission_record_audio(42,0).
perm_android_permission_record_audio(43,0).
perm_android_permission_record_audio(5,0).
perm_android_permission_record_audio(6,0).
perm_android_permission_record_audio(7,0).
perm_android_permission_record_audio(8,0).
perm_android_permission_record_audio(9,0).
perm_android_permission_send_sms(0,0).
perm_android_permission_send_sms(1,0).
perm_android_permission_send_sms(10,0).
perm_android_permission_send_sms(11,1).
perm_android_permission_send_sms(12,0).
perm_android_permission_send_sms(13,0).
perm_android_permission_send_sms(14,0).
perm_android_permission_send_sms(15,0).
perm_android_permission_send_sms(16,0).
perm_android_permission_send_sms(17,0).
perm_android_permission_send_sms(18,0).
perm_android_permission_send_sms(19,0).
perm_android_permission_send_sms(2,0).
perm_android_permission_send_sms(20,0).
perm_android_permission_send_sms(21,0).
perm_android_permission_send_sms(22,0).
perm_android_permission_send_sms(23,0).
perm_android_permission_send_sms(24,0).
perm_android_permission_send_sms(25,0).
perm_android_permission_send_sms(26,0).
perm_android_permission_send_sms(27,0).
perm_android_permission_send_sms(28,0).
perm_android_permission_send_sms(29,0).
perm_android_permission_send_sms(3,0).
perm_android_permission_send_sms(30,0).
perm_android_permission_send_sms(31,0).
perm_android_permission_send_sms(32,0).
perm_android_permission_send_sms(33,0).
perm_android_permission_send_sms(34,0).
perm_android_permission_send_sms(35,0).
perm_android_permission_send_sms(36,0).
perm_android_permission_send_sms(37,0).
perm_android_permission_send_sms(38,0).
perm_android_permission_send_sms(39,0).
perm_android_permission_send_sms(4,0).
perm_android_permission_send_sms(40,0).
perm_android_permission_send_sms(41,0).
perm_android_permission_send_sms(42,0).
perm_android_permission_send_sms(43,0).
perm_android_permission_send_sms(5,0).
perm_android_permission_send_sms(6,0).
perm_android_permission_send_sms(7,0).
perm_android_permission_send_sms(8,0).
perm_android_permission_send_sms(9,0).
perm_android_permission_set_debug_app(0,0).
perm_android_permission_set_debug_app(1,0).
perm_android_permission_set_debug_app(10,0).
perm_android_permission_set_debug_app(11,0).
perm_android_permission_set_debug_app(12,0).
perm_android_permission_set_debug_app(13,0).
perm_android_permission_set_debug_app(14,0).
perm_android_permission_set_debug_app(15,0).
perm_android_permission_set_debug_app(16,0).
perm_android_permission_set_debug_app(17,0).
perm_android_permission_set_debug_app(18,0).
perm_android_permission_set_debug_app(19,0).
perm_android_permission_set_debug_app(2,0).
perm_android_permission_set_debug_app(20,0).
perm_android_permission_set_debug_app(21,0).
perm_android_permission_set_debug_app(22,0).
perm_android_permission_set_debug_app(23,0).
perm_android_permission_set_debug_app(24,0).
perm_android_permission_set_debug_app(25,0).
perm_android_permission_set_debug_app(26,0).
perm_android_permission_set_debug_app(27,0).
perm_android_permission_set_debug_app(28,0).
perm_android_permission_set_debug_app(29,0).
perm_android_permission_set_debug_app(3,0).
perm_android_permission_set_debug_app(30,0).
perm_android_permission_set_debug_app(31,0).
perm_android_permission_set_debug_app(32,0).
perm_android_permission_set_debug_app(33,0).
perm_android_permission_set_debug_app(34,0).
perm_android_permission_set_debug_app(35,0).
perm_android_permission_set_debug_app(36,0).
perm_android_permission_set_debug_app(37,0).
perm_android_permission_set_debug_app(38,0).
perm_android_permission_set_debug_app(39,0).
perm_android_permission_set_debug_app(4,0).
perm_android_permission_set_debug_app(40,0).
perm_android_permission_set_debug_app(41,0).
perm_android_permission_set_debug_app(42,0).
perm_android_permission_set_debug_app(43,0).
perm_android_permission_set_debug_app(5,0).
perm_android_permission_set_debug_app(6,0).
perm_android_permission_set_debug_app(7,0).
perm_android_permission_set_debug_app(8,0).
perm_android_permission_set_debug_app(9,0).
perm_com_android_vending_billing(0,0).
perm_com_android_vending_billing(1,0).
perm_com_android_vending_billing(10,0).
perm_com_android_vending_billing(11,0).
perm_com_android_vending_billing(12,0).
perm_com_android_vending_billing(13,0).
perm_com_android_vending_billing(14,0).
perm_com_android_vending_billing(15,0).
perm_com_android_vending_billing(16,0).
perm_com_android_vending_billing(17,0).
perm_com_android_vending_billing(18,0).
perm_com_android_vending_billing(19,0).
perm_com_android_vending_billing(2,0).
perm_com_android_vending_billing(20,1).
perm_com_android_vending_billing(21,0).
perm_com_android_vending_billing(22,0).
perm_com_android_vending_billing(23,0).
perm_com_android_vending_billing(24,0).
perm_com_android_vending_billing(25,0).
perm_com_android_vending_billing(26,0).
perm_com_android_vending_billing(27,0).
perm_com_android_vending_billing(28,0).
perm_com_android_vending_billing(29,1).
perm_com_android_vending_billing(3,0).
perm_com_android_vending_billing(30,0).
perm_com_android_vending_billing(31,0).
perm_com_android_vending_billing(32,0).
perm_com_android_vending_billing(33,0).
perm_com_android_vending_billing(34,0).
perm_com_android_vending_billing(35,0).
perm_com_android_vending_billing(36,0).
perm_com_android_vending_billing(37,0).
perm_com_android_vending_billing(38,0).
perm_com_android_vending_billing(39,1).
perm_com_android_vending_billing(4,0).
perm_com_android_vending_billing(40,0).
perm_com_android_vending_billing(41,0).
perm_com_android_vending_billing(42,0).
perm_com_android_vending_billing(43,0).
perm_com_android_vending_billing(5,0).
perm_com_android_vending_billing(6,0).
perm_com_android_vending_billing(7,0).
perm_com_android_vending_billing(8,0).
perm_com_android_vending_billing(9,0).
perm_com_yulong_android_launcher_permission_read_settings(0,0).
perm_com_yulong_android_launcher_permission_read_settings(1,0).
perm_com_yulong_android_launcher_permission_read_settings(10,0).
perm_com_yulong_android_launcher_permission_read_settings(11,0).
perm_com_yulong_android_launcher_permission_read_settings(12,0).
perm_com_yulong_android_launcher_permission_read_settings(13,0).
perm_com_yulong_android_launcher_permission_read_settings(14,0).
perm_com_yulong_android_launcher_permission_read_settings(15,0).
perm_com_yulong_android_launcher_permission_read_settings(16,0).
perm_com_yulong_android_launcher_permission_read_settings(17,0).
perm_com_yulong_android_launcher_permission_read_settings(18,0).
perm_com_yulong_android_launcher_permission_read_settings(19,0).
perm_com_yulong_android_launcher_permission_read_settings(2,0).
perm_com_yulong_android_launcher_permission_read_settings(20,0).
perm_com_yulong_android_launcher_permission_read_settings(21,0).
perm_com_yulong_android_launcher_permission_read_settings(22,0).
perm_com_yulong_android_launcher_permission_read_settings(23,0).
perm_com_yulong_android_launcher_permission_read_settings(24,0).
perm_com_yulong_android_launcher_permission_read_settings(25,0).
perm_com_yulong_android_launcher_permission_read_settings(26,0).
perm_com_yulong_android_launcher_permission_read_settings(27,0).
perm_com_yulong_android_launcher_permission_read_settings(28,0).
perm_com_yulong_android_launcher_permission_read_settings(29,0).
perm_com_yulong_android_launcher_permission_read_settings(3,0).
perm_com_yulong_android_launcher_permission_read_settings(30,0).
perm_com_yulong_android_launcher_permission_read_settings(31,0).
perm_com_yulong_android_launcher_permission_read_settings(32,0).
perm_com_yulong_android_launcher_permission_read_settings(33,0).
perm_com_yulong_android_launcher_permission_read_settings(34,0).
perm_com_yulong_android_launcher_permission_read_settings(35,0).
perm_com_yulong_android_launcher_permission_read_settings(36,0).
perm_com_yulong_android_launcher_permission_read_settings(37,0).
perm_com_yulong_android_launcher_permission_read_settings(38,0).
perm_com_yulong_android_launcher_permission_read_settings(39,0).
perm_com_yulong_android_launcher_permission_read_settings(4,0).
perm_com_yulong_android_launcher_permission_read_settings(40,0).
perm_com_yulong_android_launcher_permission_read_settings(41,0).
perm_com_yulong_android_launcher_permission_read_settings(42,0).
perm_com_yulong_android_launcher_permission_read_settings(43,0).
perm_com_yulong_android_launcher_permission_read_settings(5,0).
perm_com_yulong_android_launcher_permission_read_settings(6,0).
perm_com_yulong_android_launcher_permission_read_settings(7,0).
perm_com_yulong_android_launcher_permission_read_settings(8,0).
perm_com_yulong_android_launcher_permission_read_settings(9,0).
suspicious_base64(0,0).
suspicious_base64(1,0).
suspicious_base64(10,0).
suspicious_base64(11,0).
suspicious_base64(12,0).
suspicious_base64(13,0).
suspicious_base64(14,0).
suspicious_base64(15,0).
suspicious_base64(16,1).
suspicious_base64(17,0).
suspicious_base64(18,0).
suspicious_base64(19,1).
suspicious_base64(2,1).
suspicious_base64(20,1).
suspicious_base64(21,0).
suspicious_base64(22,1).
suspicious_base64(23,0).
suspicious_base64(24,0).
suspicious_base64(25,0).
suspicious_base64(26,0).
suspicious_base64(27,0).
suspicious_base64(28,1).
suspicious_base64(29,0).
suspicious_base64(3,0).
suspicious_base64(30,1).
suspicious_base64(31,0).
suspicious_base64(32,1).
suspicious_base64(33,1).
suspicious_base64(34,1).
suspicious_base64(35,0).
suspicious_base64(36,1).
suspicious_base64(37,0).
suspicious_base64(38,1).
suspicious_base64(39,1).
suspicious_base64(4,0).
suspicious_base64(40,0).
suspicious_base64(41,0).
suspicious_base64(42,1).
suspicious_base64(43,1).
suspicious_base64(5,0).
suspicious_base64(6,1).
suspicious_base64(7,1).
suspicious_base64(8,0).
suspicious_base64(9,0).
suspicious_cipher(0,0).
suspicious_cipher(1,1).
suspicious_cipher(10,0).
suspicious_cipher(11,0).
suspicious_cipher(12,0).
suspicious_cipher(13,0).
suspicious_cipher(14,0).
suspicious_cipher(15,0).
suspicious_cipher(16,0).
suspicious_cipher(17,0).
suspicious_cipher(18,0).
suspicious_cipher(19,1).
suspicious_cipher(2,0).
suspicious_cipher(20,0).
suspicious_cipher(21,0).
suspicious_cipher(22,0).
suspicious_cipher(23,0).
suspicious_cipher(24,0).
suspicious_cipher(25,0).
suspicious_cipher(26,0).
suspicious_cipher(27,0).
suspicious_cipher(28,0).
suspicious_cipher(29,1).
suspicious_cipher(3,0).
suspicious_cipher(30,0).
suspicious_cipher(31,1).
suspicious_cipher(32,0).
suspicious_cipher(33,0).
suspicious_cipher(34,0).
suspicious_cipher(35,0).
suspicious_cipher(36,0).
suspicious_cipher(37,1).
suspicious_cipher(38,0).
suspicious_cipher(39,1).
suspicious_cipher(4,0).
suspicious_cipher(40,0).
suspicious_cipher(41,0).
suspicious_cipher(42,0).
suspicious_cipher(43,0).
suspicious_cipher(5,0).
suspicious_cipher(6,0).
suspicious_cipher(7,0).
suspicious_cipher(8,0).
suspicious_cipher(9,0).
suspicious_getdeviceid(0,0).
suspicious_getdeviceid(1,0).
suspicious_getdeviceid(10,0).
suspicious_getdeviceid(11,0).
suspicious_getdeviceid(12,0).
suspicious_getdeviceid(13,0).
suspicious_getdeviceid(14,0).
suspicious_getdeviceid(15,0).
suspicious_getdeviceid(16,0).
suspicious_getdeviceid(17,0).
suspicious_getdeviceid(18,0).
suspicious_getdeviceid(19,1).
suspicious_getdeviceid(2,0).
suspicious_getdeviceid(20,0).
suspicious_getdeviceid(21,1).
suspicious_getdeviceid(22,1).
suspicious_getdeviceid(23,0).
suspicious_getdeviceid(24,0).
suspicious_getdeviceid(25,0).
suspicious_getdeviceid(26,0).
suspicious_getdeviceid(27,0).
suspicious_getdeviceid(28,0).
suspicious_getdeviceid(29,0).
suspicious_getdeviceid(3,0).
suspicious_getdeviceid(30,0).
suspicious_getdeviceid(31,0).
suspicious_getdeviceid(32,0).
suspicious_getdeviceid(33,0).
suspicious_getdeviceid(34,0).
suspicious_getdeviceid(35,0).
suspicious_getdeviceid(36,0).
suspicious_getdeviceid(37,0).
suspicious_getdeviceid(38,0).
suspicious_getdeviceid(39,0).
suspicious_getdeviceid(4,0).
suspicious_getdeviceid(40,0).
suspicious_getdeviceid(41,0).
suspicious_getdeviceid(42,0).
suspicious_getdeviceid(43,0).
suspicious_getdeviceid(5,0).
suspicious_getdeviceid(6,0).
suspicious_getdeviceid(7,0).
suspicious_getdeviceid(8,0).
suspicious_getdeviceid(9,0).
suspicious_getexternalstoragedirectory(0,0).
suspicious_getexternalstoragedirectory(1,1).
suspicious_getexternalstoragedirectory(10,0).
suspicious_getexternalstoragedirectory(11,0).
suspicious_getexternalstoragedirectory(12,0).
suspicious_getexternalstoragedirectory(13,0).
suspicious_getexternalstoragedirectory(14,1).
suspicious_getexternalstoragedirectory(15,0).
suspicious_getexternalstoragedirectory(16,0).
suspicious_getexternalstoragedirectory(17,0).
suspicious_getexternalstoragedirectory(18,0).
suspicious_getexternalstoragedirectory(19,1).
suspicious_getexternalstoragedirectory(2,0).
suspicious_getexternalstoragedirectory(20,1).
suspicious_getexternalstoragedirectory(21,0).
suspicious_getexternalstoragedirectory(22,1).
suspicious_getexternalstoragedirectory(23,1).
suspicious_getexternalstoragedirectory(24,0).
suspicious_getexternalstoragedirectory(25,0).
suspicious_getexternalstoragedirectory(26,1).
suspicious_getexternalstoragedirectory(27,0).
suspicious_getexternalstoragedirectory(28,0).
suspicious_getexternalstoragedirectory(29,0).
suspicious_getexternalstoragedirectory(3,0).
suspicious_getexternalstoragedirectory(30,0).
suspicious_getexternalstoragedirectory(31,1).
suspicious_getexternalstoragedirectory(32,1).
suspicious_getexternalstoragedirectory(33,0).
suspicious_getexternalstoragedirectory(34,0).
suspicious_getexternalstoragedirectory(35,0).
suspicious_getexternalstoragedirectory(36,0).
suspicious_getexternalstoragedirectory(37,0).
suspicious_getexternalstoragedirectory(38,1).
suspicious_getexternalstoragedirectory(39,0).
suspicious_getexternalstoragedirectory(4,1).
suspicious_getexternalstoragedirectory(40,0).
suspicious_getexternalstoragedirectory(41,0).
suspicious_getexternalstoragedirectory(42,0).
suspicious_getexternalstoragedirectory(43,0).
suspicious_getexternalstoragedirectory(5,0).
suspicious_getexternalstoragedirectory(6,1).
suspicious_getexternalstoragedirectory(7,0).
suspicious_getexternalstoragedirectory(8,0).
suspicious_getexternalstoragedirectory(9,0).
suspicious_getpackageinfo(0,0).
suspicious_getpackageinfo(1,1).
suspicious_getpackageinfo(10,0).
suspicious_getpackageinfo(11,1).
suspicious_getpackageinfo(12,0).
suspicious_getpackageinfo(13,0).
suspicious_getpackageinfo(14,1).
suspicious_getpackageinfo(15,1).
suspicious_getpackageinfo(16,0).
suspicious_getpackageinfo(17,0).
suspicious_getpackageinfo(18,0).
suspicious_getpackageinfo(19,1).
suspicious_getpackageinfo(2,0).
suspicious_getpackageinfo(20,1).
suspicious_getpackageinfo(21,1).
suspicious_getpackageinfo(22,0).
suspicious_getpackageinfo(23,1).
suspicious_getpackageinfo(24,1).
suspicious_getpackageinfo(25,0).
suspicious_getpackageinfo(26,0).
suspicious_getpackageinfo(27,0).
suspicious_getpackageinfo(28,0).
suspicious_getpackageinfo(29,0).
suspicious_getpackageinfo(3,0).
suspicious_getpackageinfo(30,1).
suspicious_getpackageinfo(31,1).
suspicious_getpackageinfo(32,0).
suspicious_getpackageinfo(33,0).
suspicious_getpackageinfo(34,0).
suspicious_getpackageinfo(35,1).
suspicious_getpackageinfo(36,0).
suspicious_getpackageinfo(37,0).
suspicious_getpackageinfo(38,0).
suspicious_getpackageinfo(39,1).
suspicious_getpackageinfo(4,1).
suspicious_getpackageinfo(40,0).
suspicious_getpackageinfo(41,0).
suspicious_getpackageinfo(42,0).
suspicious_getpackageinfo(43,0).
suspicious_getpackageinfo(5,0).
suspicious_getpackageinfo(6,1).
suspicious_getpackageinfo(7,0).
suspicious_getpackageinfo(8,0).
suspicious_getpackageinfo(9,0).
suspicious_getsystemservice(0,0).
suspicious_getsystemservice(1,1).
suspicious_getsystemservice(10,1).
suspicious_getsystemservice(11,1).
suspicious_getsystemservice(12,0).
suspicious_getsystemservice(13,0).
suspicious_getsystemservice(14,1).
suspicious_getsystemservice(15,1).
suspicious_getsystemservice(16,1).
suspicious_getsystemservice(17,1).
suspicious_getsystemservice(18,0).
suspicious_getsystemservice(19,1).
suspicious_getsystemservice(2,1).
suspicious_getsystemservice(20,1).
suspicious_getsystemservice(21,1).
suspicious_getsystemservice(22,1).
suspicious_getsystemservice(23,1).
suspicious_getsystemservice(24,1).
suspicious_getsystemservice(25,1).
suspicious_getsystemservice(26,0).
suspicious_getsystemservice(27,1).
suspicious_getsystemservice(28,1).
suspicious_getsystemservice(29,1).
suspicious_getsystemservice(3,0).
suspicious_getsystemservice(30,1).
suspicious_getsystemservice(31,1).
suspicious_getsystemservice(32,1).
suspicious_getsystemservice(33,0).
suspicious_getsystemservice(34,1).
suspicious_getsystemservice(35,0).
suspicious_getsystemservice(36,0).
suspicious_getsystemservice(37,1).
suspicious_getsystemservice(38,1).
suspicious_getsystemservice(39,1).
suspicious_getsystemservice(4,1).
suspicious_getsystemservice(40,0).
suspicious_getsystemservice(41,1).
suspicious_getsystemservice(42,1).
suspicious_getsystemservice(43,1).
suspicious_getsystemservice(5,0).
suspicious_getsystemservice(6,1).
suspicious_getsystemservice(7,1).
suspicious_getsystemservice(8,0).
suspicious_getsystemservice(9,0).
suspicious_ljava_lang_runtime___exec(0,0).
suspicious_ljava_lang_runtime___exec(1,0).
suspicious_ljava_lang_runtime___exec(10,0).
suspicious_ljava_lang_runtime___exec(11,0).
suspicious_ljava_lang_runtime___exec(12,0).
suspicious_ljava_lang_runtime___exec(13,0).
suspicious_ljava_lang_runtime___exec(14,0).
suspicious_ljava_lang_runtime___exec(15,0).
suspicious_ljava_lang_runtime___exec(16,0).
suspicious_ljava_lang_runtime___exec(17,0).
suspicious_ljava_lang_runtime___exec(18,0).
suspicious_ljava_lang_runtime___exec(19,0).
suspicious_ljava_lang_runtime___exec(2,0).
suspicious_ljava_lang_runtime___exec(20,0).
suspicious_ljava_lang_runtime___exec(21,0).
suspicious_ljava_lang_runtime___exec(22,0).
suspicious_ljava_lang_runtime___exec(23,0).
suspicious_ljava_lang_runtime___exec(24,1).
suspicious_ljava_lang_runtime___exec(25,1).
suspicious_ljava_lang_runtime___exec(26,0).
suspicious_ljava_lang_runtime___exec(27,0).
suspicious_ljava_lang_runtime___exec(28,0).
suspicious_ljava_lang_runtime___exec(29,0).
suspicious_ljava_lang_runtime___exec(3,0).
suspicious_ljava_lang_runtime___exec(30,0).
suspicious_ljava_lang_runtime___exec(31,0).
suspicious_ljava_lang_runtime___exec(32,0).
suspicious_ljava_lang_runtime___exec(33,0).
suspicious_ljava_lang_runtime___exec(34,0).
suspicious_ljava_lang_runtime___exec(35,1).
suspicious_ljava_lang_runtime___exec(36,0).
suspicious_ljava_lang_runtime___exec(37,0).
suspicious_ljava_lang_runtime___exec(38,0).
suspicious_ljava_lang_runtime___exec(39,0).
suspicious_ljava_lang_runtime___exec(4,0).
suspicious_ljava_lang_runtime___exec(40,0).
suspicious_ljava_lang_runtime___exec(41,0).
suspicious_ljava_lang_runtime___exec(42,0).
suspicious_ljava_lang_runtime___exec(43,0).
suspicious_ljava_lang_runtime___exec(5,0).
suspicious_ljava_lang_runtime___exec(6,0).
suspicious_ljava_lang_runtime___exec(7,0).
suspicious_ljava_lang_runtime___exec(8,0).
suspicious_ljava_lang_runtime___exec(9,0).
suspicious_ljava_lang_system___load(0,0).
suspicious_ljava_lang_system___load(1,1).
suspicious_ljava_lang_system___load(10,0).
suspicious_ljava_lang_system___load(11,0).
suspicious_ljava_lang_system___load(12,0).
suspicious_ljava_lang_system___load(13,0).
suspicious_ljava_lang_system___load(14,1).
suspicious_ljava_lang_system___load(15,0).
suspicious_ljava_lang_system___load(16,0).
suspicious_ljava_lang_system___load(17,0).
suspicious_ljava_lang_system___load(18,0).
suspicious_ljava_lang_system___load(19,0).
suspicious_ljava_lang_system___load(2,0).
suspicious_ljava_lang_system___load(20,0).
suspicious_ljava_lang_system___load(21,0).
suspicious_ljava_lang_system___load(22,0).
suspicious_ljava_lang_system___load(23,1).
suspicious_ljava_lang_system___load(24,0).
suspicious_ljava_lang_system___load(25,0).
suspicious_ljava_lang_system___load(26,1).
suspicious_ljava_lang_system___load(27,0).
suspicious_ljava_lang_system___load(28,0).
suspicious_ljava_lang_system___load(29,1).
suspicious_ljava_lang_system___load(3,0).
suspicious_ljava_lang_system___load(30,0).
suspicious_ljava_lang_system___load(31,1).
suspicious_ljava_lang_system___load(32,1).
suspicious_ljava_lang_system___load(33,0).
suspicious_ljava_lang_system___load(34,0).
suspicious_ljava_lang_system___load(35,0).
suspicious_ljava_lang_system___load(36,0).
suspicious_ljava_lang_system___load(37,1).
suspicious_ljava_lang_system___load(38,1).
suspicious_ljava_lang_system___load(39,1).
suspicious_ljava_lang_system___load(4,1).
suspicious_ljava_lang_system___load(40,0).
suspicious_ljava_lang_system___load(41,1).
suspicious_ljava_lang_system___load(42,1).
suspicious_ljava_lang_system___load(43,0).
suspicious_ljava_lang_system___load(5,0).
suspicious_ljava_lang_system___load(6,0).
suspicious_ljava_lang_system___load(7,0).
suspicious_ljava_lang_system___load(8,0).
suspicious_ljava_lang_system___load(9,0).
suspicious_ljava_lang_system___loadlibrary(0,0).
suspicious_ljava_lang_system___loadlibrary(1,1).
suspicious_ljava_lang_system___loadlibrary(10,0).
suspicious_ljava_lang_system___loadlibrary(11,0).
suspicious_ljava_lang_system___loadlibrary(12,0).
suspicious_ljava_lang_system___loadlibrary(13,0).
suspicious_ljava_lang_system___loadlibrary(14,1).
suspicious_ljava_lang_system___loadlibrary(15,0).
suspicious_ljava_lang_system___loadlibrary(16,0).
suspicious_ljava_lang_system___loadlibrary(17,0).
suspicious_ljava_lang_system___loadlibrary(18,0).
suspicious_ljava_lang_system___loadlibrary(19,0).
suspicious_ljava_lang_system___loadlibrary(2,0).
suspicious_ljava_lang_system___loadlibrary(20,0).
suspicious_ljava_lang_system___loadlibrary(21,0).
suspicious_ljava_lang_system___loadlibrary(22,0).
suspicious_ljava_lang_system___loadlibrary(23,1).
suspicious_ljava_lang_system___loadlibrary(24,0).
suspicious_ljava_lang_system___loadlibrary(25,0).
suspicious_ljava_lang_system___loadlibrary(26,1).
suspicious_ljava_lang_system___loadlibrary(27,0).
suspicious_ljava_lang_system___loadlibrary(28,0).
suspicious_ljava_lang_system___loadlibrary(29,1).
suspicious_ljava_lang_system___loadlibrary(3,0).
suspicious_ljava_lang_system___loadlibrary(30,0).
suspicious_ljava_lang_system___loadlibrary(31,1).
suspicious_ljava_lang_system___loadlibrary(32,1).
suspicious_ljava_lang_system___loadlibrary(33,0).
suspicious_ljava_lang_system___loadlibrary(34,0).
suspicious_ljava_lang_system___loadlibrary(35,0).
suspicious_ljava_lang_system___loadlibrary(36,0).
suspicious_ljava_lang_system___loadlibrary(37,1).
suspicious_ljava_lang_system___loadlibrary(38,1).
suspicious_ljava_lang_system___loadlibrary(39,1).
suspicious_ljava_lang_system___loadlibrary(4,1).
suspicious_ljava_lang_system___loadlibrary(40,0).
suspicious_ljava_lang_system___loadlibrary(41,1).
suspicious_ljava_lang_system___loadlibrary(42,1).
suspicious_ljava_lang_system___loadlibrary(43,0).
suspicious_ljava_lang_system___loadlibrary(5,0).
suspicious_ljava_lang_system___loadlibrary(6,0).
suspicious_ljava_lang_system___loadlibrary(7,0).
suspicious_ljava_lang_system___loadlibrary(8,0).
suspicious_ljava_lang_system___loadlibrary(9,0).
non_functional(Atom1):-
	Atom1=..[label,A,B],
	Atom2=..[label,A,C],
	call(Atom2),
	B \= C.
