constant(int_0,int).
constant(int_25,int).
constant(int_1,int).
constant(int_10,int).
constant(int_40,int).
constant(int_141,int).
constant(int_22,int).
constant(int_38,int).
constant(int_7,int).
constant(int_32,int).
constant(int_168,int).
constant(int_31,int).
constant(int_61,int).
constant(int_175,int).
constant(int_6,int).
constant(int_14,int).
constant(int_3,int).
constant(int_18,int).
constant(int_362,int).
constant(int_11,int).
constant(int_149,int).
constant(int_79,int).
constant(int_589,int).
constant(int_68,int).
constant(int_46,int).
constant(int_48,int).
constant(int_155,int).
constant(int_19,int).
constant(int_37,int).
constant(int_2,int).
constant(int_162,int).
constant(int_24,int).
constant(int_124,int).
constant(int_17,int).
constant(int_69,int).
constant(int_419,int).
constant(int_56,int).
constant(int_125,int).
constant(int_421,int).
constant(int_57,int).
constant(int_44,int).
constant(int_82,int).
constant(int_156,int).
constant(int_210,int).
constant(int_43,int).
constant(int_437,int).
constant(int_35,int).
constant(int_376,int).
constant(int_51,int).
constant(int_28,int).
constant(int_562,int).
constant(int_89,int).
constant(int_5,int).
constant(int_142,int).
constant(int_39,int).
constant(int_49,int).
constant(int_59,int).
constant(int_147,int).
constant(int_356,int).
constant(int_235,int).
constant(int_113,int).
constant(int_345,int).
constant(int_128,int).
constant(int_34,int).
constant(int_257,int).
constant(int_78,int).
constant(int_23,int).
constant(int_367,int).
constant(int_131,int).
constant(int_72,int).
constant(int_431,int).
constant(int_54,int).
constant(int_180,int).
constant(int_13,int).
constant(int_42,int).
constant(int_4,int).
constant(int_264,int).
constant(int_29,int).
constant(int_71,int).
constant(int_146,int).
constant(int_55,int).
constant(int_16,int).
constant(int_60,int).
constant(int_277,int).
constant(int_86,int).
constant(int_225,int).
constant(int_299,int).
constant(int_306,int).
constant(int_45,int).
constant(int_215,int).
constant(int_52,int).
constant(int_21,int).
constant(int_92,int).
constant(int_138,int).
constant(int_207,int).
constant(int_33,int).
constant(int_76,int).
constant(int_348,int).
constant(int_15,int).
constant(int_268,int).
constant(int_12,int).
constant(int_50,int).
constant(int_8,int).
constant(int_161,int).
constant(int_217,int).
constant(int_30,int).
constant(int_9,int).
constant(int_317,int).
constant(int_36,int).
constant(int_353,int).
constant(int_27,int).
constant(int_87,int).
constant(int_120,int).
constant(int_148,int).
constant(int_223,int).
constant(int_188,int).
constant(int_248,int).
constant(int_112,int).
constant(int_129,int).
constant(int_396,int).
constant(int_230,int).
constant(int_107,int).
constant(int_332,int).
constant(int_114,int).
constant(int_269,int).
constant(int_369,int).
constant(int_267,int).
constant(int_263,int).
constant(int_62,int).
constant(int_312,int).
constant(int_371,int).
constant(int_64,int).
constant(int_170,int).
constant(int_41,int).
constant(int_152,int).
constant(int_206,int).
constant(int_20,int).
constant(int_159,int).
constant(int_143,int).
constant(int_288,int).
constant(int_240,int).
constant(int_99,int).
constant(int_220,int).
constant(int_250,int).
constant(int_157,int).
constant(int_106,int).
constant(int_226,int).
constant(int_105,int).
constant(int_463,int).
constant(int_237,int).
constant(int_195,int).
constant(int_292,int).
constant(int_132,int).
constant(int_236,int).
constant(int_63,int).
constant(int_316,int).
constant(int_26,int).
constant(int_77,int).
constant(int_282,int).
constant(int_167,int).
constant(int_169,int).
head_pred(label,2).
body_pred(perm_android_permission_device_power,2).
body_pred(perm_android_permission_clear_app_cache,2).
body_pred(perm_android_permission_process_outgoing_calls,2).
body_pred(n_permissions,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(perm_android_permission_disable_keyguard,2).
body_pred(perm_com_android_launcher_permission_read_settings,2).
body_pred(intent_com_morgoo_droidplugin_action_shortcut_proxy,2).
body_pred(perm_com_android_launcher_permission_write_settings,2).
body_pred(perm_android_permission_install_packages,2).
body_pred(perm_com_android_launcher2_permission_read_settings,2).
body_pred(perm_android_permission_read_logs,2).
body_pred(perm_android_permission_battery_stats,2).
body_pred(n_providers,2).
body_pred(n_api_calls,2).
body_pred(perm_android_permission_set_wallpaper,2).
body_pred(perm_cn_nubia_launcher_permission_read_settings,2).
body_pred(perm_android_permission_reorder_tasks,2).
body_pred(n_activities,2).
body_pred(n_services,2).
body_pred(perm_android_permission_change_wifi_state,2).
body_pred(perm_android_permission_delete_packages,2).
body_pred(perm_android_permission_write_call_log,2).
body_pred(perm_android_permission_access_cache_filesystem,2).
body_pred(perm_android_permission_write_sms,2).
body_pred(perm_android_permission_read_call_log,2).
body_pred(perm_android_permission_write_media_storage,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(perm_android_permission_get_package_size,2).
body_pred(perm_android_permission_change_configuration,2).
type(label,(ex,int)).
type(perm_android_permission_device_power,(ex,int)).
type(perm_android_permission_clear_app_cache,(ex,int)).
type(perm_android_permission_process_outgoing_calls,(ex,int)).
type(n_permissions,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(perm_android_permission_disable_keyguard,(ex,int)).
type(perm_com_android_launcher_permission_read_settings,(ex,int)).
type(intent_com_morgoo_droidplugin_action_shortcut_proxy,(ex,int)).
type(perm_com_android_launcher_permission_write_settings,(ex,int)).
type(perm_android_permission_install_packages,(ex,int)).
type(perm_com_android_launcher2_permission_read_settings,(ex,int)).
type(perm_android_permission_read_logs,(ex,int)).
type(perm_android_permission_battery_stats,(ex,int)).
type(n_providers,(ex,int)).
type(n_api_calls,(ex,int)).
type(perm_android_permission_set_wallpaper,(ex,int)).
type(perm_cn_nubia_launcher_permission_read_settings,(ex,int)).
type(perm_android_permission_reorder_tasks,(ex,int)).
type(n_activities,(ex,int)).
type(n_services,(ex,int)).
type(perm_android_permission_change_wifi_state,(ex,int)).
type(perm_android_permission_delete_packages,(ex,int)).
type(perm_android_permission_write_call_log,(ex,int)).
type(perm_android_permission_access_cache_filesystem,(ex,int)).
type(perm_android_permission_write_sms,(ex,int)).
type(perm_android_permission_read_call_log,(ex,int)).
type(perm_android_permission_write_media_storage,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(perm_android_permission_get_package_size,(ex,int)).
type(perm_android_permission_change_configuration,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
