int_0(0).
int_1(1).
int_10(10).
int_105(105).
int_106(106).
int_107(107).
int_11(11).
int_112(112).
int_113(113).
int_114(114).
int_12(12).
int_120(120).
int_124(124).
int_125(125).
int_128(128).
int_129(129).
int_13(13).
int_131(131).
int_132(132).
int_138(138).
int_14(14).
int_141(141).
int_142(142).
int_143(143).
int_146(146).
int_147(147).
int_148(148).
int_149(149).
int_15(15).
int_152(152).
int_155(155).
int_156(156).
int_157(157).
int_159(159).
int_16(16).
int_161(161).
int_162(162).
int_167(167).
int_168(168).
int_169(169).
int_17(17).
int_170(170).
int_175(175).
int_18(18).
int_180(180).
int_188(188).
int_19(19).
int_195(195).
int_2(2).
int_20(20).
int_206(206).
int_207(207).
int_21(21).
int_210(210).
int_215(215).
int_217(217).
int_22(22).
int_220(220).
int_223(223).
int_225(225).
int_226(226).
int_23(23).
int_230(230).
int_235(235).
int_236(236).
int_237(237).
int_24(24).
int_240(240).
int_248(248).
int_25(25).
int_250(250).
int_257(257).
int_26(26).
int_263(263).
int_264(264).
int_267(267).
int_268(268).
int_269(269).
int_27(27).
int_277(277).
int_28(28).
int_282(282).
int_288(288).
int_29(29).
int_292(292).
int_299(299).
int_3(3).
int_30(30).
int_306(306).
int_31(31).
int_312(312).
int_316(316).
int_317(317).
int_32(32).
int_33(33).
int_332(332).
int_34(34).
int_345(345).
int_348(348).
int_35(35).
int_353(353).
int_356(356).
int_36(36).
int_362(362).
int_367(367).
int_369(369).
int_37(37).
int_371(371).
int_376(376).
int_38(38).
int_39(39).
int_396(396).
int_4(4).
int_40(40).
int_41(41).
int_419(419).
int_42(42).
int_421(421).
int_43(43).
int_431(431).
int_437(437).
int_44(44).
int_45(45).
int_46(46).
int_463(463).
int_48(48).
int_49(49).
int_5(5).
int_50(50).
int_51(51).
int_52(52).
int_54(54).
int_55(55).
int_56(56).
int_562(562).
int_57(57).
int_589(589).
int_59(59).
int_6(6).
int_60(60).
int_61(61).
int_62(62).
int_63(63).
int_64(64).
int_68(68).
int_69(69).
int_7(7).
int_71(71).
int_72(72).
int_76(76).
int_77(77).
int_78(78).
int_79(79).
int_8(8).
int_82(82).
int_86(86).
int_87(87).
int_89(89).
int_9(9).
int_92(92).
int_99(99).
intent_com_morgoo_droidplugin_action_shortcut_proxy(0,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(1,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(10,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(11,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(12,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(13,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(14,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(15,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(16,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(17,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(18,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(19,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(2,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(20,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(21,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(22,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(23,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(24,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(25,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(26,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(27,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(28,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(29,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(3,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(30,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(31,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(32,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(33,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(34,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(35,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(36,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(37,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(38,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(39,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(4,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(40,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(41,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(42,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(43,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(44,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(45,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(46,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(47,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(48,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(49,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(5,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(50,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(51,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(52,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(53,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(54,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(55,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(56,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(57,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(58,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(59,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(6,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(60,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(61,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(62,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(63,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(64,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(65,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(66,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(67,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(68,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(69,0).
intent_com_morgoo_droidplugin_action_shortcut_proxy(7,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(8,1).
intent_com_morgoo_droidplugin_action_shortcut_proxy(9,0).
n_activities(0,141).
n_activities(1,168).
n_activities(10,437).
n_activities(11,376).
n_activities(12,562).
n_activities(13,142).
n_activities(14,147).
n_activities(15,356).
n_activities(16,345).
n_activities(17,257).
n_activities(18,589).
n_activities(19,367).
n_activities(2,175).
n_activities(20,431).
n_activities(21,180).
n_activities(22,264).
n_activities(23,146).
n_activities(24,277).
n_activities(25,225).
n_activities(26,299).
n_activities(27,306).
n_activities(28,215).
n_activities(29,138).
n_activities(3,362).
n_activities(30,348).
n_activities(31,268).
n_activities(32,161).
n_activities(33,217).
n_activities(34,317).
n_activities(35,353).
n_activities(36,146).
n_activities(37,148).
n_activities(38,223).
n_activities(39,248).
n_activities(4,589).
n_activities(40,129).
n_activities(41,396).
n_activities(42,332).
n_activities(43,269).
n_activities(44,369).
n_activities(45,267).
n_activities(46,263).
n_activities(47,312).
n_activities(48,141).
n_activities(49,371).
n_activities(5,155).
n_activities(50,170).
n_activities(51,152).
n_activities(52,206).
n_activities(53,159).
n_activities(54,143).
n_activities(55,288).
n_activities(56,240).
n_activities(57,220).
n_activities(58,250).
n_activities(59,226).
n_activities(6,162).
n_activities(60,463).
n_activities(61,237).
n_activities(62,292).
n_activities(63,236).
n_activities(64,316).
n_activities(65,143).
n_activities(66,282).
n_activities(67,269).
n_activities(68,167).
n_activities(69,169).
n_activities(7,419).
n_activities(8,421).
n_activities(9,156).
n_api_calls(0,40).
n_api_calls(1,32).
n_api_calls(10,43).
n_api_calls(11,0).
n_api_calls(12,51).
n_api_calls(13,48).
n_api_calls(14,59).
n_api_calls(15,18).
n_api_calls(16,28).
n_api_calls(17,22).
n_api_calls(18,78).
n_api_calls(19,0).
n_api_calls(2,61).
n_api_calls(20,72).
n_api_calls(21,54).
n_api_calls(22,4).
n_api_calls(23,71).
n_api_calls(24,60).
n_api_calls(25,0).
n_api_calls(26,31).
n_api_calls(27,31).
n_api_calls(28,69).
n_api_calls(29,92).
n_api_calls(3,18).
n_api_calls(30,76).
n_api_calls(31,28).
n_api_calls(32,71).
n_api_calls(33,72).
n_api_calls(34,68).
n_api_calls(35,0).
n_api_calls(36,87).
n_api_calls(37,49).
n_api_calls(38,28).
n_api_calls(39,56).
n_api_calls(4,79).
n_api_calls(40,69).
n_api_calls(41,0).
n_api_calls(42,29).
n_api_calls(43,45).
n_api_calls(44,0).
n_api_calls(45,50).
n_api_calls(46,61).
n_api_calls(47,30).
n_api_calls(48,49).
n_api_calls(49,0).
n_api_calls(5,48).
n_api_calls(50,64).
n_api_calls(51,72).
n_api_calls(52,79).
n_api_calls(53,69).
n_api_calls(54,25).
n_api_calls(55,31).
n_api_calls(56,0).
n_api_calls(57,42).
n_api_calls(58,39).
n_api_calls(59,34).
n_api_calls(6,61).
n_api_calls(60,0).
n_api_calls(61,15).
n_api_calls(62,41).
n_api_calls(63,55).
n_api_calls(64,63).
n_api_calls(65,35).
n_api_calls(66,77).
n_api_calls(67,51).
n_api_calls(68,44).
n_api_calls(69,72).
n_api_calls(7,69).
n_api_calls(8,69).
n_api_calls(9,82).
n_permissions(0,25).
n_permissions(1,38).
n_permissions(10,210).
n_permissions(11,35).
n_permissions(12,51).
n_permissions(13,22).
n_permissions(14,49).
n_permissions(15,3).
n_permissions(16,235).
n_permissions(17,34).
n_permissions(18,149).
n_permissions(19,38).
n_permissions(2,40).
n_permissions(20,131).
n_permissions(21,22).
n_permissions(22,42).
n_permissions(23,24).
n_permissions(24,55).
n_permissions(25,86).
n_permissions(26,39).
n_permissions(27,39).
n_permissions(28,45).
n_permissions(29,21).
n_permissions(3,14).
n_permissions(30,207).
n_permissions(31,15).
n_permissions(32,50).
n_permissions(33,38).
n_permissions(34,31).
n_permissions(35,36).
n_permissions(36,40).
n_permissions(37,120).
n_permissions(38,30).
n_permissions(39,188).
n_permissions(4,149).
n_permissions(40,112).
n_permissions(41,40).
n_permissions(42,230).
n_permissions(43,36).
n_permissions(44,34).
n_permissions(45,24).
n_permissions(46,43).
n_permissions(47,40).
n_permissions(48,120).
n_permissions(49,34).
n_permissions(5,46).
n_permissions(50,56).
n_permissions(51,30).
n_permissions(52,44).
n_permissions(53,38).
n_permissions(54,21).
n_permissions(55,39).
n_permissions(56,32).
n_permissions(57,99).
n_permissions(58,57).
n_permissions(59,157).
n_permissions(6,37).
n_permissions(60,39).
n_permissions(61,146).
n_permissions(62,195).
n_permissions(63,175).
n_permissions(64,31).
n_permissions(65,36).
n_permissions(66,57).
n_permissions(67,51).
n_permissions(68,36).
n_permissions(69,38).
n_permissions(7,124).
n_permissions(8,125).
n_permissions(9,44).
n_providers(0,10).
n_providers(1,7).
n_providers(10,37).
n_providers(11,25).
n_providers(12,28).
n_providers(13,5).
n_providers(14,6).
n_providers(15,0).
n_providers(16,113).
n_providers(17,1).
n_providers(18,31).
n_providers(19,23).
n_providers(2,0).
n_providers(20,17).
n_providers(21,1).
n_providers(22,3).
n_providers(23,7).
n_providers(24,16).
n_providers(25,5).
n_providers(26,4).
n_providers(27,1).
n_providers(28,17).
n_providers(29,0).
n_providers(3,3).
n_providers(30,33).
n_providers(31,11).
n_providers(32,8).
n_providers(33,24).
n_providers(34,9).
n_providers(35,19).
n_providers(36,1).
n_providers(37,4).
n_providers(38,4).
n_providers(39,27).
n_providers(4,32).
n_providers(40,2).
n_providers(41,18).
n_providers(42,107).
n_providers(43,16).
n_providers(44,22).
n_providers(45,1).
n_providers(46,23).
n_providers(47,2).
n_providers(48,4).
n_providers(49,23).
n_providers(5,3).
n_providers(50,16).
n_providers(51,1).
n_providers(52,4).
n_providers(53,1).
n_providers(54,4).
n_providers(55,4).
n_providers(56,1).
n_providers(57,41).
n_providers(58,27).
n_providers(59,106).
n_providers(6,2).
n_providers(60,7).
n_providers(61,10).
n_providers(62,105).
n_providers(63,114).
n_providers(64,9).
n_providers(65,5).
n_providers(66,18).
n_providers(67,15).
n_providers(68,2).
n_providers(69,0).
n_providers(7,17).
n_providers(8,17).
n_providers(9,0).
n_services(0,22).
n_services(1,31).
n_services(10,48).
n_services(11,40).
n_services(12,89).
n_services(13,39).
n_services(14,40).
n_services(15,0).
n_services(16,128).
n_services(17,18).
n_services(18,68).
n_services(19,32).
n_services(2,6).
n_services(20,57).
n_services(21,13).
n_services(22,29).
n_services(23,14).
n_services(24,24).
n_services(25,25).
n_services(26,19).
n_services(27,18).
n_services(28,52).
n_services(29,13).
n_services(3,11).
n_services(30,33).
n_services(31,12).
n_services(32,29).
n_services(33,30).
n_services(34,25).
n_services(35,27).
n_services(36,9).
n_services(37,36).
n_services(38,12).
n_services(39,29).
n_services(4,68).
n_services(40,30).
n_services(41,16).
n_services(42,114).
n_services(43,34).
n_services(44,31).
n_services(45,18).
n_services(46,62).
n_services(47,22).
n_services(48,36).
n_services(49,39).
n_services(5,19).
n_services(50,41).
n_services(51,11).
n_services(52,20).
n_services(53,12).
n_services(54,13).
n_services(55,20).
n_services(56,28).
n_services(57,25).
n_services(58,28).
n_services(59,105).
n_services(6,24).
n_services(60,17).
n_services(61,20).
n_services(62,132).
n_services(63,24).
n_services(64,26).
n_services(65,11).
n_services(66,28).
n_services(67,38).
n_services(68,5).
n_services(69,12).
n_services(7,56).
n_services(8,57).
n_services(9,11).
perm_android_permission_access_cache_filesystem(0,0).
perm_android_permission_access_cache_filesystem(1,0).
perm_android_permission_access_cache_filesystem(10,1).
perm_android_permission_access_cache_filesystem(11,0).
perm_android_permission_access_cache_filesystem(12,0).
perm_android_permission_access_cache_filesystem(13,0).
perm_android_permission_access_cache_filesystem(14,0).
perm_android_permission_access_cache_filesystem(15,0).
perm_android_permission_access_cache_filesystem(16,1).
perm_android_permission_access_cache_filesystem(17,0).
perm_android_permission_access_cache_filesystem(18,1).
perm_android_permission_access_cache_filesystem(19,0).
perm_android_permission_access_cache_filesystem(2,0).
perm_android_permission_access_cache_filesystem(20,1).
perm_android_permission_access_cache_filesystem(21,0).
perm_android_permission_access_cache_filesystem(22,0).
perm_android_permission_access_cache_filesystem(23,0).
perm_android_permission_access_cache_filesystem(24,0).
perm_android_permission_access_cache_filesystem(25,0).
perm_android_permission_access_cache_filesystem(26,0).
perm_android_permission_access_cache_filesystem(27,0).
perm_android_permission_access_cache_filesystem(28,0).
perm_android_permission_access_cache_filesystem(29,0).
perm_android_permission_access_cache_filesystem(3,0).
perm_android_permission_access_cache_filesystem(30,1).
perm_android_permission_access_cache_filesystem(31,0).
perm_android_permission_access_cache_filesystem(32,0).
perm_android_permission_access_cache_filesystem(33,0).
perm_android_permission_access_cache_filesystem(34,0).
perm_android_permission_access_cache_filesystem(35,0).
perm_android_permission_access_cache_filesystem(36,0).
perm_android_permission_access_cache_filesystem(37,0).
perm_android_permission_access_cache_filesystem(38,0).
perm_android_permission_access_cache_filesystem(39,1).
perm_android_permission_access_cache_filesystem(4,1).
perm_android_permission_access_cache_filesystem(40,0).
perm_android_permission_access_cache_filesystem(41,0).
perm_android_permission_access_cache_filesystem(42,1).
perm_android_permission_access_cache_filesystem(43,0).
perm_android_permission_access_cache_filesystem(44,0).
perm_android_permission_access_cache_filesystem(45,0).
perm_android_permission_access_cache_filesystem(46,0).
perm_android_permission_access_cache_filesystem(47,0).
perm_android_permission_access_cache_filesystem(48,0).
perm_android_permission_access_cache_filesystem(49,0).
perm_android_permission_access_cache_filesystem(5,0).
perm_android_permission_access_cache_filesystem(50,0).
perm_android_permission_access_cache_filesystem(51,0).
perm_android_permission_access_cache_filesystem(52,0).
perm_android_permission_access_cache_filesystem(53,0).
perm_android_permission_access_cache_filesystem(54,0).
perm_android_permission_access_cache_filesystem(55,0).
perm_android_permission_access_cache_filesystem(56,0).
perm_android_permission_access_cache_filesystem(57,0).
perm_android_permission_access_cache_filesystem(58,0).
perm_android_permission_access_cache_filesystem(59,1).
perm_android_permission_access_cache_filesystem(6,0).
perm_android_permission_access_cache_filesystem(60,0).
perm_android_permission_access_cache_filesystem(61,0).
perm_android_permission_access_cache_filesystem(62,1).
perm_android_permission_access_cache_filesystem(63,1).
perm_android_permission_access_cache_filesystem(64,0).
perm_android_permission_access_cache_filesystem(65,0).
perm_android_permission_access_cache_filesystem(66,0).
perm_android_permission_access_cache_filesystem(67,0).
perm_android_permission_access_cache_filesystem(68,0).
perm_android_permission_access_cache_filesystem(69,0).
perm_android_permission_access_cache_filesystem(7,1).
perm_android_permission_access_cache_filesystem(8,1).
perm_android_permission_access_cache_filesystem(9,0).
perm_android_permission_battery_stats(0,1).
perm_android_permission_battery_stats(1,0).
perm_android_permission_battery_stats(10,1).
perm_android_permission_battery_stats(11,0).
perm_android_permission_battery_stats(12,0).
perm_android_permission_battery_stats(13,0).
perm_android_permission_battery_stats(14,0).
perm_android_permission_battery_stats(15,0).
perm_android_permission_battery_stats(16,1).
perm_android_permission_battery_stats(17,0).
perm_android_permission_battery_stats(18,1).
perm_android_permission_battery_stats(19,0).
perm_android_permission_battery_stats(2,0).
perm_android_permission_battery_stats(20,1).
perm_android_permission_battery_stats(21,0).
perm_android_permission_battery_stats(22,1).
perm_android_permission_battery_stats(23,0).
perm_android_permission_battery_stats(24,1).
perm_android_permission_battery_stats(25,0).
perm_android_permission_battery_stats(26,0).
perm_android_permission_battery_stats(27,1).
perm_android_permission_battery_stats(28,0).
perm_android_permission_battery_stats(29,0).
perm_android_permission_battery_stats(3,0).
perm_android_permission_battery_stats(30,1).
perm_android_permission_battery_stats(31,0).
perm_android_permission_battery_stats(32,0).
perm_android_permission_battery_stats(33,1).
perm_android_permission_battery_stats(34,0).
perm_android_permission_battery_stats(35,0).
perm_android_permission_battery_stats(36,0).
perm_android_permission_battery_stats(37,1).
perm_android_permission_battery_stats(38,1).
perm_android_permission_battery_stats(39,1).
perm_android_permission_battery_stats(4,1).
perm_android_permission_battery_stats(40,1).
perm_android_permission_battery_stats(41,1).
perm_android_permission_battery_stats(42,1).
perm_android_permission_battery_stats(43,0).
perm_android_permission_battery_stats(44,0).
perm_android_permission_battery_stats(45,0).
perm_android_permission_battery_stats(46,0).
perm_android_permission_battery_stats(47,1).
perm_android_permission_battery_stats(48,1).
perm_android_permission_battery_stats(49,0).
perm_android_permission_battery_stats(5,0).
perm_android_permission_battery_stats(50,0).
perm_android_permission_battery_stats(51,1).
perm_android_permission_battery_stats(52,1).
perm_android_permission_battery_stats(53,0).
perm_android_permission_battery_stats(54,0).
perm_android_permission_battery_stats(55,0).
perm_android_permission_battery_stats(56,1).
perm_android_permission_battery_stats(57,1).
perm_android_permission_battery_stats(58,1).
perm_android_permission_battery_stats(59,1).
perm_android_permission_battery_stats(6,1).
perm_android_permission_battery_stats(60,1).
perm_android_permission_battery_stats(61,1).
perm_android_permission_battery_stats(62,1).
perm_android_permission_battery_stats(63,1).
perm_android_permission_battery_stats(64,0).
perm_android_permission_battery_stats(65,0).
perm_android_permission_battery_stats(66,1).
perm_android_permission_battery_stats(67,0).
perm_android_permission_battery_stats(68,0).
perm_android_permission_battery_stats(69,1).
perm_android_permission_battery_stats(7,1).
perm_android_permission_battery_stats(8,1).
perm_android_permission_battery_stats(9,0).
perm_android_permission_change_configuration(0,0).
perm_android_permission_change_configuration(1,0).
perm_android_permission_change_configuration(10,1).
perm_android_permission_change_configuration(11,1).
perm_android_permission_change_configuration(12,0).
perm_android_permission_change_configuration(13,0).
perm_android_permission_change_configuration(14,0).
perm_android_permission_change_configuration(15,0).
perm_android_permission_change_configuration(16,0).
perm_android_permission_change_configuration(17,0).
perm_android_permission_change_configuration(18,1).
perm_android_permission_change_configuration(19,1).
perm_android_permission_change_configuration(2,0).
perm_android_permission_change_configuration(20,1).
perm_android_permission_change_configuration(21,0).
perm_android_permission_change_configuration(22,1).
perm_android_permission_change_configuration(23,0).
perm_android_permission_change_configuration(24,1).
perm_android_permission_change_configuration(25,0).
perm_android_permission_change_configuration(26,0).
perm_android_permission_change_configuration(27,0).
perm_android_permission_change_configuration(28,1).
perm_android_permission_change_configuration(29,1).
perm_android_permission_change_configuration(3,0).
perm_android_permission_change_configuration(30,1).
perm_android_permission_change_configuration(31,0).
perm_android_permission_change_configuration(32,1).
perm_android_permission_change_configuration(33,1).
perm_android_permission_change_configuration(34,0).
perm_android_permission_change_configuration(35,1).
perm_android_permission_change_configuration(36,0).
perm_android_permission_change_configuration(37,1).
perm_android_permission_change_configuration(38,1).
perm_android_permission_change_configuration(39,1).
perm_android_permission_change_configuration(4,1).
perm_android_permission_change_configuration(40,1).
perm_android_permission_change_configuration(41,0).
perm_android_permission_change_configuration(42,1).
perm_android_permission_change_configuration(43,1).
perm_android_permission_change_configuration(44,1).
perm_android_permission_change_configuration(45,0).
perm_android_permission_change_configuration(46,0).
perm_android_permission_change_configuration(47,0).
perm_android_permission_change_configuration(48,1).
perm_android_permission_change_configuration(49,1).
perm_android_permission_change_configuration(5,0).
perm_android_permission_change_configuration(50,1).
perm_android_permission_change_configuration(51,0).
perm_android_permission_change_configuration(52,1).
perm_android_permission_change_configuration(53,0).
perm_android_permission_change_configuration(54,0).
perm_android_permission_change_configuration(55,0).
perm_android_permission_change_configuration(56,0).
perm_android_permission_change_configuration(57,0).
perm_android_permission_change_configuration(58,1).
perm_android_permission_change_configuration(59,1).
perm_android_permission_change_configuration(6,0).
perm_android_permission_change_configuration(60,0).
perm_android_permission_change_configuration(61,1).
perm_android_permission_change_configuration(62,1).
perm_android_permission_change_configuration(63,1).
perm_android_permission_change_configuration(64,0).
perm_android_permission_change_configuration(65,1).
perm_android_permission_change_configuration(66,1).
perm_android_permission_change_configuration(67,0).
perm_android_permission_change_configuration(68,1).
perm_android_permission_change_configuration(69,1).
perm_android_permission_change_configuration(7,1).
perm_android_permission_change_configuration(8,1).
perm_android_permission_change_configuration(9,1).
perm_android_permission_change_wifi_state(0,0).
perm_android_permission_change_wifi_state(1,0).
perm_android_permission_change_wifi_state(10,1).
perm_android_permission_change_wifi_state(11,1).
perm_android_permission_change_wifi_state(12,1).
perm_android_permission_change_wifi_state(13,0).
perm_android_permission_change_wifi_state(14,1).
perm_android_permission_change_wifi_state(15,0).
perm_android_permission_change_wifi_state(16,1).
perm_android_permission_change_wifi_state(17,1).
perm_android_permission_change_wifi_state(18,1).
perm_android_permission_change_wifi_state(19,1).
perm_android_permission_change_wifi_state(2,1).
perm_android_permission_change_wifi_state(20,1).
perm_android_permission_change_wifi_state(21,1).
perm_android_permission_change_wifi_state(22,1).
perm_android_permission_change_wifi_state(23,1).
perm_android_permission_change_wifi_state(24,1).
perm_android_permission_change_wifi_state(25,1).
perm_android_permission_change_wifi_state(26,1).
perm_android_permission_change_wifi_state(27,1).
perm_android_permission_change_wifi_state(28,1).
perm_android_permission_change_wifi_state(29,0).
perm_android_permission_change_wifi_state(3,0).
perm_android_permission_change_wifi_state(30,1).
perm_android_permission_change_wifi_state(31,0).
perm_android_permission_change_wifi_state(32,1).
perm_android_permission_change_wifi_state(33,1).
perm_android_permission_change_wifi_state(34,1).
perm_android_permission_change_wifi_state(35,1).
perm_android_permission_change_wifi_state(36,1).
perm_android_permission_change_wifi_state(37,1).
perm_android_permission_change_wifi_state(38,1).
perm_android_permission_change_wifi_state(39,1).
perm_android_permission_change_wifi_state(4,1).
perm_android_permission_change_wifi_state(40,1).
perm_android_permission_change_wifi_state(41,1).
perm_android_permission_change_wifi_state(42,1).
perm_android_permission_change_wifi_state(43,1).
perm_android_permission_change_wifi_state(44,1).
perm_android_permission_change_wifi_state(45,0).
perm_android_permission_change_wifi_state(46,1).
perm_android_permission_change_wifi_state(47,1).
perm_android_permission_change_wifi_state(48,1).
perm_android_permission_change_wifi_state(49,1).
perm_android_permission_change_wifi_state(5,1).
perm_android_permission_change_wifi_state(50,1).
perm_android_permission_change_wifi_state(51,1).
perm_android_permission_change_wifi_state(52,1).
perm_android_permission_change_wifi_state(53,1).
perm_android_permission_change_wifi_state(54,0).
perm_android_permission_change_wifi_state(55,1).
perm_android_permission_change_wifi_state(56,1).
perm_android_permission_change_wifi_state(57,0).
perm_android_permission_change_wifi_state(58,1).
perm_android_permission_change_wifi_state(59,1).
perm_android_permission_change_wifi_state(6,1).
perm_android_permission_change_wifi_state(60,1).
perm_android_permission_change_wifi_state(61,1).
perm_android_permission_change_wifi_state(62,1).
perm_android_permission_change_wifi_state(63,1).
perm_android_permission_change_wifi_state(64,1).
perm_android_permission_change_wifi_state(65,1).
perm_android_permission_change_wifi_state(66,1).
perm_android_permission_change_wifi_state(67,1).
perm_android_permission_change_wifi_state(68,1).
perm_android_permission_change_wifi_state(69,1).
perm_android_permission_change_wifi_state(7,1).
perm_android_permission_change_wifi_state(8,1).
perm_android_permission_change_wifi_state(9,1).
perm_android_permission_clear_app_cache(0,0).
perm_android_permission_clear_app_cache(1,0).
perm_android_permission_clear_app_cache(10,1).
perm_android_permission_clear_app_cache(11,0).
perm_android_permission_clear_app_cache(12,0).
perm_android_permission_clear_app_cache(13,0).
perm_android_permission_clear_app_cache(14,1).
perm_android_permission_clear_app_cache(15,0).
perm_android_permission_clear_app_cache(16,1).
perm_android_permission_clear_app_cache(17,0).
perm_android_permission_clear_app_cache(18,1).
perm_android_permission_clear_app_cache(19,0).
perm_android_permission_clear_app_cache(2,0).
perm_android_permission_clear_app_cache(20,1).
perm_android_permission_clear_app_cache(21,0).
perm_android_permission_clear_app_cache(22,0).
perm_android_permission_clear_app_cache(23,0).
perm_android_permission_clear_app_cache(24,0).
perm_android_permission_clear_app_cache(25,0).
perm_android_permission_clear_app_cache(26,0).
perm_android_permission_clear_app_cache(27,0).
perm_android_permission_clear_app_cache(28,1).
perm_android_permission_clear_app_cache(29,0).
perm_android_permission_clear_app_cache(3,0).
perm_android_permission_clear_app_cache(30,1).
perm_android_permission_clear_app_cache(31,0).
perm_android_permission_clear_app_cache(32,0).
perm_android_permission_clear_app_cache(33,0).
perm_android_permission_clear_app_cache(34,0).
perm_android_permission_clear_app_cache(35,0).
perm_android_permission_clear_app_cache(36,0).
perm_android_permission_clear_app_cache(37,1).
perm_android_permission_clear_app_cache(38,0).
perm_android_permission_clear_app_cache(39,1).
perm_android_permission_clear_app_cache(4,1).
perm_android_permission_clear_app_cache(40,1).
perm_android_permission_clear_app_cache(41,0).
perm_android_permission_clear_app_cache(42,1).
perm_android_permission_clear_app_cache(43,0).
perm_android_permission_clear_app_cache(44,0).
perm_android_permission_clear_app_cache(45,0).
perm_android_permission_clear_app_cache(46,1).
perm_android_permission_clear_app_cache(47,0).
perm_android_permission_clear_app_cache(48,1).
perm_android_permission_clear_app_cache(49,0).
perm_android_permission_clear_app_cache(5,0).
perm_android_permission_clear_app_cache(50,0).
perm_android_permission_clear_app_cache(51,0).
perm_android_permission_clear_app_cache(52,0).
perm_android_permission_clear_app_cache(53,1).
perm_android_permission_clear_app_cache(54,0).
perm_android_permission_clear_app_cache(55,0).
perm_android_permission_clear_app_cache(56,0).
perm_android_permission_clear_app_cache(57,1).
perm_android_permission_clear_app_cache(58,0).
perm_android_permission_clear_app_cache(59,1).
perm_android_permission_clear_app_cache(6,0).
perm_android_permission_clear_app_cache(60,0).
perm_android_permission_clear_app_cache(61,1).
perm_android_permission_clear_app_cache(62,1).
perm_android_permission_clear_app_cache(63,1).
perm_android_permission_clear_app_cache(64,0).
perm_android_permission_clear_app_cache(65,0).
perm_android_permission_clear_app_cache(66,0).
perm_android_permission_clear_app_cache(67,1).
perm_android_permission_clear_app_cache(68,0).
perm_android_permission_clear_app_cache(69,0).
perm_android_permission_clear_app_cache(7,1).
perm_android_permission_clear_app_cache(8,1).
perm_android_permission_clear_app_cache(9,0).
perm_android_permission_delete_packages(0,0).
perm_android_permission_delete_packages(1,0).
perm_android_permission_delete_packages(10,1).
perm_android_permission_delete_packages(11,0).
perm_android_permission_delete_packages(12,0).
perm_android_permission_delete_packages(13,0).
perm_android_permission_delete_packages(14,0).
perm_android_permission_delete_packages(15,0).
perm_android_permission_delete_packages(16,1).
perm_android_permission_delete_packages(17,0).
perm_android_permission_delete_packages(18,1).
perm_android_permission_delete_packages(19,0).
perm_android_permission_delete_packages(2,0).
perm_android_permission_delete_packages(20,1).
perm_android_permission_delete_packages(21,0).
perm_android_permission_delete_packages(22,0).
perm_android_permission_delete_packages(23,0).
perm_android_permission_delete_packages(24,0).
perm_android_permission_delete_packages(25,0).
perm_android_permission_delete_packages(26,0).
perm_android_permission_delete_packages(27,0).
perm_android_permission_delete_packages(28,0).
perm_android_permission_delete_packages(29,0).
perm_android_permission_delete_packages(3,0).
perm_android_permission_delete_packages(30,1).
perm_android_permission_delete_packages(31,0).
perm_android_permission_delete_packages(32,0).
perm_android_permission_delete_packages(33,0).
perm_android_permission_delete_packages(34,0).
perm_android_permission_delete_packages(35,0).
perm_android_permission_delete_packages(36,0).
perm_android_permission_delete_packages(37,0).
perm_android_permission_delete_packages(38,0).
perm_android_permission_delete_packages(39,1).
perm_android_permission_delete_packages(4,1).
perm_android_permission_delete_packages(40,0).
perm_android_permission_delete_packages(41,0).
perm_android_permission_delete_packages(42,1).
perm_android_permission_delete_packages(43,0).
perm_android_permission_delete_packages(44,0).
perm_android_permission_delete_packages(45,0).
perm_android_permission_delete_packages(46,0).
perm_android_permission_delete_packages(47,0).
perm_android_permission_delete_packages(48,0).
perm_android_permission_delete_packages(49,0).
perm_android_permission_delete_packages(5,0).
perm_android_permission_delete_packages(50,0).
perm_android_permission_delete_packages(51,0).
perm_android_permission_delete_packages(52,0).
perm_android_permission_delete_packages(53,0).
perm_android_permission_delete_packages(54,0).
perm_android_permission_delete_packages(55,0).
perm_android_permission_delete_packages(56,0).
perm_android_permission_delete_packages(57,0).
perm_android_permission_delete_packages(58,0).
perm_android_permission_delete_packages(59,1).
perm_android_permission_delete_packages(6,0).
perm_android_permission_delete_packages(60,0).
perm_android_permission_delete_packages(61,0).
perm_android_permission_delete_packages(62,1).
perm_android_permission_delete_packages(63,1).
perm_android_permission_delete_packages(64,0).
perm_android_permission_delete_packages(65,0).
perm_android_permission_delete_packages(66,0).
perm_android_permission_delete_packages(67,0).
perm_android_permission_delete_packages(68,0).
perm_android_permission_delete_packages(69,0).
perm_android_permission_delete_packages(7,1).
perm_android_permission_delete_packages(8,1).
perm_android_permission_delete_packages(9,0).
perm_android_permission_device_power(0,0).
perm_android_permission_device_power(1,0).
perm_android_permission_device_power(10,1).
perm_android_permission_device_power(11,1).
perm_android_permission_device_power(12,0).
perm_android_permission_device_power(13,0).
perm_android_permission_device_power(14,0).
perm_android_permission_device_power(15,0).
perm_android_permission_device_power(16,1).
perm_android_permission_device_power(17,0).
perm_android_permission_device_power(18,1).
perm_android_permission_device_power(19,1).
perm_android_permission_device_power(2,0).
perm_android_permission_device_power(20,1).
perm_android_permission_device_power(21,0).
perm_android_permission_device_power(22,0).
perm_android_permission_device_power(23,0).
perm_android_permission_device_power(24,0).
perm_android_permission_device_power(25,0).
perm_android_permission_device_power(26,0).
perm_android_permission_device_power(27,0).
perm_android_permission_device_power(28,0).
perm_android_permission_device_power(29,0).
perm_android_permission_device_power(3,0).
perm_android_permission_device_power(30,1).
perm_android_permission_device_power(31,0).
perm_android_permission_device_power(32,0).
perm_android_permission_device_power(33,0).
perm_android_permission_device_power(34,0).
perm_android_permission_device_power(35,1).
perm_android_permission_device_power(36,0).
perm_android_permission_device_power(37,0).
perm_android_permission_device_power(38,0).
perm_android_permission_device_power(39,1).
perm_android_permission_device_power(4,1).
perm_android_permission_device_power(40,0).
perm_android_permission_device_power(41,0).
perm_android_permission_device_power(42,1).
perm_android_permission_device_power(43,0).
perm_android_permission_device_power(44,1).
perm_android_permission_device_power(45,0).
perm_android_permission_device_power(46,0).
perm_android_permission_device_power(47,0).
perm_android_permission_device_power(48,0).
perm_android_permission_device_power(49,1).
perm_android_permission_device_power(5,0).
perm_android_permission_device_power(50,0).
perm_android_permission_device_power(51,0).
perm_android_permission_device_power(52,0).
perm_android_permission_device_power(53,0).
perm_android_permission_device_power(54,0).
perm_android_permission_device_power(55,0).
perm_android_permission_device_power(56,0).
perm_android_permission_device_power(57,0).
perm_android_permission_device_power(58,0).
perm_android_permission_device_power(59,1).
perm_android_permission_device_power(6,0).
perm_android_permission_device_power(60,0).
perm_android_permission_device_power(61,0).
perm_android_permission_device_power(62,1).
perm_android_permission_device_power(63,1).
perm_android_permission_device_power(64,0).
perm_android_permission_device_power(65,0).
perm_android_permission_device_power(66,0).
perm_android_permission_device_power(67,0).
perm_android_permission_device_power(68,0).
perm_android_permission_device_power(69,0).
perm_android_permission_device_power(7,1).
perm_android_permission_device_power(8,1).
perm_android_permission_device_power(9,0).
perm_android_permission_disable_keyguard(0,1).
perm_android_permission_disable_keyguard(1,0).
perm_android_permission_disable_keyguard(10,1).
perm_android_permission_disable_keyguard(11,1).
perm_android_permission_disable_keyguard(12,1).
perm_android_permission_disable_keyguard(13,0).
perm_android_permission_disable_keyguard(14,1).
perm_android_permission_disable_keyguard(15,0).
perm_android_permission_disable_keyguard(16,1).
perm_android_permission_disable_keyguard(17,0).
perm_android_permission_disable_keyguard(18,1).
perm_android_permission_disable_keyguard(19,1).
perm_android_permission_disable_keyguard(2,0).
perm_android_permission_disable_keyguard(20,1).
perm_android_permission_disable_keyguard(21,0).
perm_android_permission_disable_keyguard(22,1).
perm_android_permission_disable_keyguard(23,0).
perm_android_permission_disable_keyguard(24,1).
perm_android_permission_disable_keyguard(25,0).
perm_android_permission_disable_keyguard(26,0).
perm_android_permission_disable_keyguard(27,0).
perm_android_permission_disable_keyguard(28,1).
perm_android_permission_disable_keyguard(29,0).
perm_android_permission_disable_keyguard(3,0).
perm_android_permission_disable_keyguard(30,1).
perm_android_permission_disable_keyguard(31,0).
perm_android_permission_disable_keyguard(32,0).
perm_android_permission_disable_keyguard(33,0).
perm_android_permission_disable_keyguard(34,1).
perm_android_permission_disable_keyguard(35,1).
perm_android_permission_disable_keyguard(36,1).
perm_android_permission_disable_keyguard(37,1).
perm_android_permission_disable_keyguard(38,0).
perm_android_permission_disable_keyguard(39,1).
perm_android_permission_disable_keyguard(4,1).
perm_android_permission_disable_keyguard(40,1).
perm_android_permission_disable_keyguard(41,1).
perm_android_permission_disable_keyguard(42,1).
perm_android_permission_disable_keyguard(43,0).
perm_android_permission_disable_keyguard(44,1).
perm_android_permission_disable_keyguard(45,0).
perm_android_permission_disable_keyguard(46,0).
perm_android_permission_disable_keyguard(47,0).
perm_android_permission_disable_keyguard(48,1).
perm_android_permission_disable_keyguard(49,1).
perm_android_permission_disable_keyguard(5,0).
perm_android_permission_disable_keyguard(50,0).
perm_android_permission_disable_keyguard(51,1).
perm_android_permission_disable_keyguard(52,1).
perm_android_permission_disable_keyguard(53,0).
perm_android_permission_disable_keyguard(54,0).
perm_android_permission_disable_keyguard(55,0).
perm_android_permission_disable_keyguard(56,0).
perm_android_permission_disable_keyguard(57,1).
perm_android_permission_disable_keyguard(58,1).
perm_android_permission_disable_keyguard(59,1).
perm_android_permission_disable_keyguard(6,0).
perm_android_permission_disable_keyguard(60,1).
perm_android_permission_disable_keyguard(61,1).
perm_android_permission_disable_keyguard(62,1).
perm_android_permission_disable_keyguard(63,1).
perm_android_permission_disable_keyguard(64,1).
perm_android_permission_disable_keyguard(65,1).
perm_android_permission_disable_keyguard(66,1).
perm_android_permission_disable_keyguard(67,0).
perm_android_permission_disable_keyguard(68,1).
perm_android_permission_disable_keyguard(69,1).
perm_android_permission_disable_keyguard(7,1).
perm_android_permission_disable_keyguard(8,1).
perm_android_permission_disable_keyguard(9,0).
perm_android_permission_get_package_size(0,0).
perm_android_permission_get_package_size(1,1).
perm_android_permission_get_package_size(10,1).
perm_android_permission_get_package_size(11,0).
perm_android_permission_get_package_size(12,0).
perm_android_permission_get_package_size(13,0).
perm_android_permission_get_package_size(14,1).
perm_android_permission_get_package_size(15,0).
perm_android_permission_get_package_size(16,1).
perm_android_permission_get_package_size(17,0).
perm_android_permission_get_package_size(18,1).
perm_android_permission_get_package_size(19,0).
perm_android_permission_get_package_size(2,0).
perm_android_permission_get_package_size(20,1).
perm_android_permission_get_package_size(21,0).
perm_android_permission_get_package_size(22,1).
perm_android_permission_get_package_size(23,0).
perm_android_permission_get_package_size(24,0).
perm_android_permission_get_package_size(25,0).
perm_android_permission_get_package_size(26,0).
perm_android_permission_get_package_size(27,0).
perm_android_permission_get_package_size(28,1).
perm_android_permission_get_package_size(29,0).
perm_android_permission_get_package_size(3,0).
perm_android_permission_get_package_size(30,1).
perm_android_permission_get_package_size(31,0).
perm_android_permission_get_package_size(32,0).
perm_android_permission_get_package_size(33,1).
perm_android_permission_get_package_size(34,0).
perm_android_permission_get_package_size(35,0).
perm_android_permission_get_package_size(36,0).
perm_android_permission_get_package_size(37,1).
perm_android_permission_get_package_size(38,0).
perm_android_permission_get_package_size(39,1).
perm_android_permission_get_package_size(4,1).
perm_android_permission_get_package_size(40,1).
perm_android_permission_get_package_size(41,0).
perm_android_permission_get_package_size(42,1).
perm_android_permission_get_package_size(43,0).
perm_android_permission_get_package_size(44,0).
perm_android_permission_get_package_size(45,0).
perm_android_permission_get_package_size(46,1).
perm_android_permission_get_package_size(47,0).
perm_android_permission_get_package_size(48,1).
perm_android_permission_get_package_size(49,0).
perm_android_permission_get_package_size(5,1).
perm_android_permission_get_package_size(50,0).
perm_android_permission_get_package_size(51,0).
perm_android_permission_get_package_size(52,1).
perm_android_permission_get_package_size(53,0).
perm_android_permission_get_package_size(54,0).
perm_android_permission_get_package_size(55,0).
perm_android_permission_get_package_size(56,1).
perm_android_permission_get_package_size(57,1).
perm_android_permission_get_package_size(58,0).
perm_android_permission_get_package_size(59,1).
perm_android_permission_get_package_size(6,0).
perm_android_permission_get_package_size(60,0).
perm_android_permission_get_package_size(61,1).
perm_android_permission_get_package_size(62,1).
perm_android_permission_get_package_size(63,1).
perm_android_permission_get_package_size(64,0).
perm_android_permission_get_package_size(65,0).
perm_android_permission_get_package_size(66,0).
perm_android_permission_get_package_size(67,1).
perm_android_permission_get_package_size(68,0).
perm_android_permission_get_package_size(69,1).
perm_android_permission_get_package_size(7,1).
perm_android_permission_get_package_size(8,1).
perm_android_permission_get_package_size(9,0).
perm_android_permission_install_packages(0,0).
perm_android_permission_install_packages(1,0).
perm_android_permission_install_packages(10,1).
perm_android_permission_install_packages(11,0).
perm_android_permission_install_packages(12,0).
perm_android_permission_install_packages(13,0).
perm_android_permission_install_packages(14,0).
perm_android_permission_install_packages(15,0).
perm_android_permission_install_packages(16,1).
perm_android_permission_install_packages(17,0).
perm_android_permission_install_packages(18,1).
perm_android_permission_install_packages(19,0).
perm_android_permission_install_packages(2,0).
perm_android_permission_install_packages(20,1).
perm_android_permission_install_packages(21,0).
perm_android_permission_install_packages(22,0).
perm_android_permission_install_packages(23,0).
perm_android_permission_install_packages(24,0).
perm_android_permission_install_packages(25,0).
perm_android_permission_install_packages(26,0).
perm_android_permission_install_packages(27,0).
perm_android_permission_install_packages(28,0).
perm_android_permission_install_packages(29,0).
perm_android_permission_install_packages(3,0).
perm_android_permission_install_packages(30,1).
perm_android_permission_install_packages(31,0).
perm_android_permission_install_packages(32,0).
perm_android_permission_install_packages(33,0).
perm_android_permission_install_packages(34,0).
perm_android_permission_install_packages(35,0).
perm_android_permission_install_packages(36,0).
perm_android_permission_install_packages(37,0).
perm_android_permission_install_packages(38,0).
perm_android_permission_install_packages(39,1).
perm_android_permission_install_packages(4,1).
perm_android_permission_install_packages(40,0).
perm_android_permission_install_packages(41,0).
perm_android_permission_install_packages(42,1).
perm_android_permission_install_packages(43,0).
perm_android_permission_install_packages(44,0).
perm_android_permission_install_packages(45,0).
perm_android_permission_install_packages(46,0).
perm_android_permission_install_packages(47,0).
perm_android_permission_install_packages(48,0).
perm_android_permission_install_packages(49,0).
perm_android_permission_install_packages(5,0).
perm_android_permission_install_packages(50,0).
perm_android_permission_install_packages(51,0).
perm_android_permission_install_packages(52,0).
perm_android_permission_install_packages(53,0).
perm_android_permission_install_packages(54,0).
perm_android_permission_install_packages(55,0).
perm_android_permission_install_packages(56,0).
perm_android_permission_install_packages(57,0).
perm_android_permission_install_packages(58,0).
perm_android_permission_install_packages(59,1).
perm_android_permission_install_packages(6,0).
perm_android_permission_install_packages(60,0).
perm_android_permission_install_packages(61,0).
perm_android_permission_install_packages(62,1).
perm_android_permission_install_packages(63,1).
perm_android_permission_install_packages(64,0).
perm_android_permission_install_packages(65,0).
perm_android_permission_install_packages(66,0).
perm_android_permission_install_packages(67,0).
perm_android_permission_install_packages(68,0).
perm_android_permission_install_packages(69,0).
perm_android_permission_install_packages(7,1).
perm_android_permission_install_packages(8,1).
perm_android_permission_install_packages(9,0).
perm_android_permission_mount_unmount_filesystems(0,0).
perm_android_permission_mount_unmount_filesystems(1,0).
perm_android_permission_mount_unmount_filesystems(10,1).
perm_android_permission_mount_unmount_filesystems(11,1).
perm_android_permission_mount_unmount_filesystems(12,0).
perm_android_permission_mount_unmount_filesystems(13,0).
perm_android_permission_mount_unmount_filesystems(14,1).
perm_android_permission_mount_unmount_filesystems(15,0).
perm_android_permission_mount_unmount_filesystems(16,1).
perm_android_permission_mount_unmount_filesystems(17,1).
perm_android_permission_mount_unmount_filesystems(18,1).
perm_android_permission_mount_unmount_filesystems(19,1).
perm_android_permission_mount_unmount_filesystems(2,1).
perm_android_permission_mount_unmount_filesystems(20,1).
perm_android_permission_mount_unmount_filesystems(21,1).
perm_android_permission_mount_unmount_filesystems(22,1).
perm_android_permission_mount_unmount_filesystems(23,1).
perm_android_permission_mount_unmount_filesystems(24,1).
perm_android_permission_mount_unmount_filesystems(25,1).
perm_android_permission_mount_unmount_filesystems(26,0).
perm_android_permission_mount_unmount_filesystems(27,0).
perm_android_permission_mount_unmount_filesystems(28,1).
perm_android_permission_mount_unmount_filesystems(29,1).
perm_android_permission_mount_unmount_filesystems(3,0).
perm_android_permission_mount_unmount_filesystems(30,1).
perm_android_permission_mount_unmount_filesystems(31,1).
perm_android_permission_mount_unmount_filesystems(32,0).
perm_android_permission_mount_unmount_filesystems(33,1).
perm_android_permission_mount_unmount_filesystems(34,0).
perm_android_permission_mount_unmount_filesystems(35,1).
perm_android_permission_mount_unmount_filesystems(36,1).
perm_android_permission_mount_unmount_filesystems(37,1).
perm_android_permission_mount_unmount_filesystems(38,1).
perm_android_permission_mount_unmount_filesystems(39,1).
perm_android_permission_mount_unmount_filesystems(4,1).
perm_android_permission_mount_unmount_filesystems(40,1).
perm_android_permission_mount_unmount_filesystems(41,1).
perm_android_permission_mount_unmount_filesystems(42,1).
perm_android_permission_mount_unmount_filesystems(43,1).
perm_android_permission_mount_unmount_filesystems(44,1).
perm_android_permission_mount_unmount_filesystems(45,0).
perm_android_permission_mount_unmount_filesystems(46,0).
perm_android_permission_mount_unmount_filesystems(47,0).
perm_android_permission_mount_unmount_filesystems(48,1).
perm_android_permission_mount_unmount_filesystems(49,1).
perm_android_permission_mount_unmount_filesystems(5,1).
perm_android_permission_mount_unmount_filesystems(50,0).
perm_android_permission_mount_unmount_filesystems(51,1).
perm_android_permission_mount_unmount_filesystems(52,1).
perm_android_permission_mount_unmount_filesystems(53,1).
perm_android_permission_mount_unmount_filesystems(54,0).
perm_android_permission_mount_unmount_filesystems(55,0).
perm_android_permission_mount_unmount_filesystems(56,1).
perm_android_permission_mount_unmount_filesystems(57,1).
perm_android_permission_mount_unmount_filesystems(58,1).
perm_android_permission_mount_unmount_filesystems(59,1).
perm_android_permission_mount_unmount_filesystems(6,1).
perm_android_permission_mount_unmount_filesystems(60,1).
perm_android_permission_mount_unmount_filesystems(61,1).
perm_android_permission_mount_unmount_filesystems(62,1).
perm_android_permission_mount_unmount_filesystems(63,1).
perm_android_permission_mount_unmount_filesystems(64,0).
perm_android_permission_mount_unmount_filesystems(65,1).
perm_android_permission_mount_unmount_filesystems(66,1).
perm_android_permission_mount_unmount_filesystems(67,0).
perm_android_permission_mount_unmount_filesystems(68,1).
perm_android_permission_mount_unmount_filesystems(69,1).
perm_android_permission_mount_unmount_filesystems(7,1).
perm_android_permission_mount_unmount_filesystems(8,1).
perm_android_permission_mount_unmount_filesystems(9,1).
perm_android_permission_process_outgoing_calls(0,0).
perm_android_permission_process_outgoing_calls(1,0).
perm_android_permission_process_outgoing_calls(10,1).
perm_android_permission_process_outgoing_calls(11,0).
perm_android_permission_process_outgoing_calls(12,0).
perm_android_permission_process_outgoing_calls(13,1).
perm_android_permission_process_outgoing_calls(14,0).
perm_android_permission_process_outgoing_calls(15,0).
perm_android_permission_process_outgoing_calls(16,1).
perm_android_permission_process_outgoing_calls(17,0).
perm_android_permission_process_outgoing_calls(18,1).
perm_android_permission_process_outgoing_calls(19,0).
perm_android_permission_process_outgoing_calls(2,0).
perm_android_permission_process_outgoing_calls(20,1).
perm_android_permission_process_outgoing_calls(21,0).
perm_android_permission_process_outgoing_calls(22,0).
perm_android_permission_process_outgoing_calls(23,0).
perm_android_permission_process_outgoing_calls(24,0).
perm_android_permission_process_outgoing_calls(25,1).
perm_android_permission_process_outgoing_calls(26,0).
perm_android_permission_process_outgoing_calls(27,0).
perm_android_permission_process_outgoing_calls(28,0).
perm_android_permission_process_outgoing_calls(29,1).
perm_android_permission_process_outgoing_calls(3,0).
perm_android_permission_process_outgoing_calls(30,1).
perm_android_permission_process_outgoing_calls(31,0).
perm_android_permission_process_outgoing_calls(32,1).
perm_android_permission_process_outgoing_calls(33,0).
perm_android_permission_process_outgoing_calls(34,0).
perm_android_permission_process_outgoing_calls(35,0).
perm_android_permission_process_outgoing_calls(36,1).
perm_android_permission_process_outgoing_calls(37,1).
perm_android_permission_process_outgoing_calls(38,0).
perm_android_permission_process_outgoing_calls(39,1).
perm_android_permission_process_outgoing_calls(4,1).
perm_android_permission_process_outgoing_calls(40,0).
perm_android_permission_process_outgoing_calls(41,0).
perm_android_permission_process_outgoing_calls(42,1).
perm_android_permission_process_outgoing_calls(43,0).
perm_android_permission_process_outgoing_calls(44,0).
perm_android_permission_process_outgoing_calls(45,0).
perm_android_permission_process_outgoing_calls(46,0).
perm_android_permission_process_outgoing_calls(47,0).
perm_android_permission_process_outgoing_calls(48,1).
perm_android_permission_process_outgoing_calls(49,0).
perm_android_permission_process_outgoing_calls(5,0).
perm_android_permission_process_outgoing_calls(50,0).
perm_android_permission_process_outgoing_calls(51,1).
perm_android_permission_process_outgoing_calls(52,0).
perm_android_permission_process_outgoing_calls(53,0).
perm_android_permission_process_outgoing_calls(54,0).
perm_android_permission_process_outgoing_calls(55,0).
perm_android_permission_process_outgoing_calls(56,0).
perm_android_permission_process_outgoing_calls(57,0).
perm_android_permission_process_outgoing_calls(58,0).
perm_android_permission_process_outgoing_calls(59,1).
perm_android_permission_process_outgoing_calls(6,0).
perm_android_permission_process_outgoing_calls(60,0).
perm_android_permission_process_outgoing_calls(61,1).
perm_android_permission_process_outgoing_calls(62,1).
perm_android_permission_process_outgoing_calls(63,1).
perm_android_permission_process_outgoing_calls(64,0).
perm_android_permission_process_outgoing_calls(65,0).
perm_android_permission_process_outgoing_calls(66,0).
perm_android_permission_process_outgoing_calls(67,0).
perm_android_permission_process_outgoing_calls(68,0).
perm_android_permission_process_outgoing_calls(69,0).
perm_android_permission_process_outgoing_calls(7,1).
perm_android_permission_process_outgoing_calls(8,1).
perm_android_permission_process_outgoing_calls(9,1).
perm_android_permission_read_call_log(0,0).
perm_android_permission_read_call_log(1,0).
perm_android_permission_read_call_log(10,1).
perm_android_permission_read_call_log(11,0).
perm_android_permission_read_call_log(12,0).
perm_android_permission_read_call_log(13,0).
perm_android_permission_read_call_log(14,0).
perm_android_permission_read_call_log(15,0).
perm_android_permission_read_call_log(16,1).
perm_android_permission_read_call_log(17,0).
perm_android_permission_read_call_log(18,1).
perm_android_permission_read_call_log(19,0).
perm_android_permission_read_call_log(2,0).
perm_android_permission_read_call_log(20,1).
perm_android_permission_read_call_log(21,0).
perm_android_permission_read_call_log(22,0).
perm_android_permission_read_call_log(23,0).
perm_android_permission_read_call_log(24,0).
perm_android_permission_read_call_log(25,0).
perm_android_permission_read_call_log(26,0).
perm_android_permission_read_call_log(27,0).
perm_android_permission_read_call_log(28,0).
perm_android_permission_read_call_log(29,0).
perm_android_permission_read_call_log(3,0).
perm_android_permission_read_call_log(30,1).
perm_android_permission_read_call_log(31,0).
perm_android_permission_read_call_log(32,1).
perm_android_permission_read_call_log(33,0).
perm_android_permission_read_call_log(34,0).
perm_android_permission_read_call_log(35,0).
perm_android_permission_read_call_log(36,0).
perm_android_permission_read_call_log(37,1).
perm_android_permission_read_call_log(38,0).
perm_android_permission_read_call_log(39,1).
perm_android_permission_read_call_log(4,1).
perm_android_permission_read_call_log(40,0).
perm_android_permission_read_call_log(41,0).
perm_android_permission_read_call_log(42,1).
perm_android_permission_read_call_log(43,0).
perm_android_permission_read_call_log(44,0).
perm_android_permission_read_call_log(45,0).
perm_android_permission_read_call_log(46,0).
perm_android_permission_read_call_log(47,0).
perm_android_permission_read_call_log(48,1).
perm_android_permission_read_call_log(49,0).
perm_android_permission_read_call_log(5,0).
perm_android_permission_read_call_log(50,0).
perm_android_permission_read_call_log(51,0).
perm_android_permission_read_call_log(52,0).
perm_android_permission_read_call_log(53,0).
perm_android_permission_read_call_log(54,0).
perm_android_permission_read_call_log(55,0).
perm_android_permission_read_call_log(56,0).
perm_android_permission_read_call_log(57,0).
perm_android_permission_read_call_log(58,1).
perm_android_permission_read_call_log(59,0).
perm_android_permission_read_call_log(6,0).
perm_android_permission_read_call_log(60,0).
perm_android_permission_read_call_log(61,1).
perm_android_permission_read_call_log(62,1).
perm_android_permission_read_call_log(63,1).
perm_android_permission_read_call_log(64,0).
perm_android_permission_read_call_log(65,0).
perm_android_permission_read_call_log(66,0).
perm_android_permission_read_call_log(67,0).
perm_android_permission_read_call_log(68,0).
perm_android_permission_read_call_log(69,0).
perm_android_permission_read_call_log(7,1).
perm_android_permission_read_call_log(8,1).
perm_android_permission_read_call_log(9,1).
perm_android_permission_read_logs(0,1).
perm_android_permission_read_logs(1,0).
perm_android_permission_read_logs(10,1).
perm_android_permission_read_logs(11,1).
perm_android_permission_read_logs(12,0).
perm_android_permission_read_logs(13,1).
perm_android_permission_read_logs(14,1).
perm_android_permission_read_logs(15,0).
perm_android_permission_read_logs(16,1).
perm_android_permission_read_logs(17,0).
perm_android_permission_read_logs(18,1).
perm_android_permission_read_logs(19,1).
perm_android_permission_read_logs(2,1).
perm_android_permission_read_logs(20,1).
perm_android_permission_read_logs(21,1).
perm_android_permission_read_logs(22,1).
perm_android_permission_read_logs(23,1).
perm_android_permission_read_logs(24,1).
perm_android_permission_read_logs(25,1).
perm_android_permission_read_logs(26,0).
perm_android_permission_read_logs(27,1).
perm_android_permission_read_logs(28,1).
perm_android_permission_read_logs(29,1).
perm_android_permission_read_logs(3,0).
perm_android_permission_read_logs(30,1).
perm_android_permission_read_logs(31,0).
perm_android_permission_read_logs(32,1).
perm_android_permission_read_logs(33,1).
perm_android_permission_read_logs(34,1).
perm_android_permission_read_logs(35,1).
perm_android_permission_read_logs(36,1).
perm_android_permission_read_logs(37,1).
perm_android_permission_read_logs(38,1).
perm_android_permission_read_logs(39,1).
perm_android_permission_read_logs(4,1).
perm_android_permission_read_logs(40,1).
perm_android_permission_read_logs(41,1).
perm_android_permission_read_logs(42,1).
perm_android_permission_read_logs(43,0).
perm_android_permission_read_logs(44,1).
perm_android_permission_read_logs(45,1).
perm_android_permission_read_logs(46,0).
perm_android_permission_read_logs(47,1).
perm_android_permission_read_logs(48,1).
perm_android_permission_read_logs(49,1).
perm_android_permission_read_logs(5,1).
perm_android_permission_read_logs(50,1).
perm_android_permission_read_logs(51,1).
perm_android_permission_read_logs(52,1).
perm_android_permission_read_logs(53,0).
perm_android_permission_read_logs(54,0).
perm_android_permission_read_logs(55,0).
perm_android_permission_read_logs(56,1).
perm_android_permission_read_logs(57,0).
perm_android_permission_read_logs(58,1).
perm_android_permission_read_logs(59,1).
perm_android_permission_read_logs(6,0).
perm_android_permission_read_logs(60,0).
perm_android_permission_read_logs(61,1).
perm_android_permission_read_logs(62,1).
perm_android_permission_read_logs(63,1).
perm_android_permission_read_logs(64,1).
perm_android_permission_read_logs(65,1).
perm_android_permission_read_logs(66,1).
perm_android_permission_read_logs(67,0).
perm_android_permission_read_logs(68,1).
perm_android_permission_read_logs(69,1).
perm_android_permission_read_logs(7,1).
perm_android_permission_read_logs(8,1).
perm_android_permission_read_logs(9,0).
perm_android_permission_reorder_tasks(0,0).
perm_android_permission_reorder_tasks(1,0).
perm_android_permission_reorder_tasks(10,1).
perm_android_permission_reorder_tasks(11,1).
perm_android_permission_reorder_tasks(12,0).
perm_android_permission_reorder_tasks(13,0).
perm_android_permission_reorder_tasks(14,0).
perm_android_permission_reorder_tasks(15,0).
perm_android_permission_reorder_tasks(16,1).
perm_android_permission_reorder_tasks(17,0).
perm_android_permission_reorder_tasks(18,1).
perm_android_permission_reorder_tasks(19,1).
perm_android_permission_reorder_tasks(2,0).
perm_android_permission_reorder_tasks(20,1).
perm_android_permission_reorder_tasks(21,0).
perm_android_permission_reorder_tasks(22,0).
perm_android_permission_reorder_tasks(23,0).
perm_android_permission_reorder_tasks(24,0).
perm_android_permission_reorder_tasks(25,0).
perm_android_permission_reorder_tasks(26,0).
perm_android_permission_reorder_tasks(27,0).
perm_android_permission_reorder_tasks(28,0).
perm_android_permission_reorder_tasks(29,0).
perm_android_permission_reorder_tasks(3,0).
perm_android_permission_reorder_tasks(30,1).
perm_android_permission_reorder_tasks(31,0).
perm_android_permission_reorder_tasks(32,1).
perm_android_permission_reorder_tasks(33,1).
perm_android_permission_reorder_tasks(34,1).
perm_android_permission_reorder_tasks(35,1).
perm_android_permission_reorder_tasks(36,1).
perm_android_permission_reorder_tasks(37,0).
perm_android_permission_reorder_tasks(38,0).
perm_android_permission_reorder_tasks(39,1).
perm_android_permission_reorder_tasks(4,1).
perm_android_permission_reorder_tasks(40,0).
perm_android_permission_reorder_tasks(41,0).
perm_android_permission_reorder_tasks(42,1).
perm_android_permission_reorder_tasks(43,0).
perm_android_permission_reorder_tasks(44,1).
perm_android_permission_reorder_tasks(45,0).
perm_android_permission_reorder_tasks(46,0).
perm_android_permission_reorder_tasks(47,0).
perm_android_permission_reorder_tasks(48,0).
perm_android_permission_reorder_tasks(49,1).
perm_android_permission_reorder_tasks(5,0).
perm_android_permission_reorder_tasks(50,1).
perm_android_permission_reorder_tasks(51,0).
perm_android_permission_reorder_tasks(52,1).
perm_android_permission_reorder_tasks(53,0).
perm_android_permission_reorder_tasks(54,0).
perm_android_permission_reorder_tasks(55,0).
perm_android_permission_reorder_tasks(56,0).
perm_android_permission_reorder_tasks(57,0).
perm_android_permission_reorder_tasks(58,1).
perm_android_permission_reorder_tasks(59,1).
perm_android_permission_reorder_tasks(6,0).
perm_android_permission_reorder_tasks(60,0).
perm_android_permission_reorder_tasks(61,1).
perm_android_permission_reorder_tasks(62,1).
perm_android_permission_reorder_tasks(63,1).
perm_android_permission_reorder_tasks(64,1).
perm_android_permission_reorder_tasks(65,0).
perm_android_permission_reorder_tasks(66,0).
perm_android_permission_reorder_tasks(67,0).
perm_android_permission_reorder_tasks(68,0).
perm_android_permission_reorder_tasks(69,0).
perm_android_permission_reorder_tasks(7,1).
perm_android_permission_reorder_tasks(8,1).
perm_android_permission_reorder_tasks(9,0).
perm_android_permission_set_wallpaper(0,0).
perm_android_permission_set_wallpaper(1,1).
perm_android_permission_set_wallpaper(10,1).
perm_android_permission_set_wallpaper(11,0).
perm_android_permission_set_wallpaper(12,1).
perm_android_permission_set_wallpaper(13,0).
perm_android_permission_set_wallpaper(14,1).
perm_android_permission_set_wallpaper(15,0).
perm_android_permission_set_wallpaper(16,1).
perm_android_permission_set_wallpaper(17,0).
perm_android_permission_set_wallpaper(18,1).
perm_android_permission_set_wallpaper(19,0).
perm_android_permission_set_wallpaper(2,0).
perm_android_permission_set_wallpaper(20,1).
perm_android_permission_set_wallpaper(21,0).
perm_android_permission_set_wallpaper(22,1).
perm_android_permission_set_wallpaper(23,0).
perm_android_permission_set_wallpaper(24,0).
perm_android_permission_set_wallpaper(25,0).
perm_android_permission_set_wallpaper(26,0).
perm_android_permission_set_wallpaper(27,0).
perm_android_permission_set_wallpaper(28,1).
perm_android_permission_set_wallpaper(29,0).
perm_android_permission_set_wallpaper(3,0).
perm_android_permission_set_wallpaper(30,1).
perm_android_permission_set_wallpaper(31,0).
perm_android_permission_set_wallpaper(32,0).
perm_android_permission_set_wallpaper(33,0).
perm_android_permission_set_wallpaper(34,0).
perm_android_permission_set_wallpaper(35,0).
perm_android_permission_set_wallpaper(36,0).
perm_android_permission_set_wallpaper(37,1).
perm_android_permission_set_wallpaper(38,0).
perm_android_permission_set_wallpaper(39,1).
perm_android_permission_set_wallpaper(4,1).
perm_android_permission_set_wallpaper(40,1).
perm_android_permission_set_wallpaper(41,0).
perm_android_permission_set_wallpaper(42,1).
perm_android_permission_set_wallpaper(43,0).
perm_android_permission_set_wallpaper(44,0).
perm_android_permission_set_wallpaper(45,1).
perm_android_permission_set_wallpaper(46,0).
perm_android_permission_set_wallpaper(47,0).
perm_android_permission_set_wallpaper(48,1).
perm_android_permission_set_wallpaper(49,0).
perm_android_permission_set_wallpaper(5,0).
perm_android_permission_set_wallpaper(50,0).
perm_android_permission_set_wallpaper(51,0).
perm_android_permission_set_wallpaper(52,0).
perm_android_permission_set_wallpaper(53,0).
perm_android_permission_set_wallpaper(54,0).
perm_android_permission_set_wallpaper(55,0).
perm_android_permission_set_wallpaper(56,0).
perm_android_permission_set_wallpaper(57,0).
perm_android_permission_set_wallpaper(58,0).
perm_android_permission_set_wallpaper(59,1).
perm_android_permission_set_wallpaper(6,0).
perm_android_permission_set_wallpaper(60,0).
perm_android_permission_set_wallpaper(61,1).
perm_android_permission_set_wallpaper(62,1).
perm_android_permission_set_wallpaper(63,1).
perm_android_permission_set_wallpaper(64,0).
perm_android_permission_set_wallpaper(65,0).
perm_android_permission_set_wallpaper(66,0).
perm_android_permission_set_wallpaper(67,0).
perm_android_permission_set_wallpaper(68,0).
perm_android_permission_set_wallpaper(69,0).
perm_android_permission_set_wallpaper(7,1).
perm_android_permission_set_wallpaper(8,1).
perm_android_permission_set_wallpaper(9,0).
perm_android_permission_write_call_log(0,0).
perm_android_permission_write_call_log(1,0).
perm_android_permission_write_call_log(10,1).
perm_android_permission_write_call_log(11,0).
perm_android_permission_write_call_log(12,0).
perm_android_permission_write_call_log(13,0).
perm_android_permission_write_call_log(14,0).
perm_android_permission_write_call_log(15,0).
perm_android_permission_write_call_log(16,1).
perm_android_permission_write_call_log(17,0).
perm_android_permission_write_call_log(18,1).
perm_android_permission_write_call_log(19,0).
perm_android_permission_write_call_log(2,0).
perm_android_permission_write_call_log(20,1).
perm_android_permission_write_call_log(21,0).
perm_android_permission_write_call_log(22,0).
perm_android_permission_write_call_log(23,0).
perm_android_permission_write_call_log(24,0).
perm_android_permission_write_call_log(25,0).
perm_android_permission_write_call_log(26,0).
perm_android_permission_write_call_log(27,0).
perm_android_permission_write_call_log(28,0).
perm_android_permission_write_call_log(29,0).
perm_android_permission_write_call_log(3,0).
perm_android_permission_write_call_log(30,1).
perm_android_permission_write_call_log(31,0).
perm_android_permission_write_call_log(32,1).
perm_android_permission_write_call_log(33,0).
perm_android_permission_write_call_log(34,0).
perm_android_permission_write_call_log(35,0).
perm_android_permission_write_call_log(36,0).
perm_android_permission_write_call_log(37,0).
perm_android_permission_write_call_log(38,0).
perm_android_permission_write_call_log(39,1).
perm_android_permission_write_call_log(4,1).
perm_android_permission_write_call_log(40,0).
perm_android_permission_write_call_log(41,0).
perm_android_permission_write_call_log(42,1).
perm_android_permission_write_call_log(43,0).
perm_android_permission_write_call_log(44,0).
perm_android_permission_write_call_log(45,0).
perm_android_permission_write_call_log(46,0).
perm_android_permission_write_call_log(47,0).
perm_android_permission_write_call_log(48,0).
perm_android_permission_write_call_log(49,0).
perm_android_permission_write_call_log(5,0).
perm_android_permission_write_call_log(50,0).
perm_android_permission_write_call_log(51,0).
perm_android_permission_write_call_log(52,0).
perm_android_permission_write_call_log(53,0).
perm_android_permission_write_call_log(54,0).
perm_android_permission_write_call_log(55,0).
perm_android_permission_write_call_log(56,0).
perm_android_permission_write_call_log(57,0).
perm_android_permission_write_call_log(58,0).
perm_android_permission_write_call_log(59,0).
perm_android_permission_write_call_log(6,0).
perm_android_permission_write_call_log(60,0).
perm_android_permission_write_call_log(61,1).
perm_android_permission_write_call_log(62,1).
perm_android_permission_write_call_log(63,1).
perm_android_permission_write_call_log(64,0).
perm_android_permission_write_call_log(65,0).
perm_android_permission_write_call_log(66,0).
perm_android_permission_write_call_log(67,0).
perm_android_permission_write_call_log(68,0).
perm_android_permission_write_call_log(69,0).
perm_android_permission_write_call_log(7,1).
perm_android_permission_write_call_log(8,1).
perm_android_permission_write_call_log(9,0).
perm_android_permission_write_media_storage(0,0).
perm_android_permission_write_media_storage(1,0).
perm_android_permission_write_media_storage(10,1).
perm_android_permission_write_media_storage(11,0).
perm_android_permission_write_media_storage(12,0).
perm_android_permission_write_media_storage(13,0).
perm_android_permission_write_media_storage(14,0).
perm_android_permission_write_media_storage(15,0).
perm_android_permission_write_media_storage(16,1).
perm_android_permission_write_media_storage(17,0).
perm_android_permission_write_media_storage(18,1).
perm_android_permission_write_media_storage(19,0).
perm_android_permission_write_media_storage(2,0).
perm_android_permission_write_media_storage(20,1).
perm_android_permission_write_media_storage(21,0).
perm_android_permission_write_media_storage(22,0).
perm_android_permission_write_media_storage(23,0).
perm_android_permission_write_media_storage(24,0).
perm_android_permission_write_media_storage(25,0).
perm_android_permission_write_media_storage(26,0).
perm_android_permission_write_media_storage(27,0).
perm_android_permission_write_media_storage(28,0).
perm_android_permission_write_media_storage(29,0).
perm_android_permission_write_media_storage(3,0).
perm_android_permission_write_media_storage(30,1).
perm_android_permission_write_media_storage(31,0).
perm_android_permission_write_media_storage(32,0).
perm_android_permission_write_media_storage(33,0).
perm_android_permission_write_media_storage(34,0).
perm_android_permission_write_media_storage(35,0).
perm_android_permission_write_media_storage(36,0).
perm_android_permission_write_media_storage(37,0).
perm_android_permission_write_media_storage(38,0).
perm_android_permission_write_media_storage(39,1).
perm_android_permission_write_media_storage(4,1).
perm_android_permission_write_media_storage(40,0).
perm_android_permission_write_media_storage(41,0).
perm_android_permission_write_media_storage(42,1).
perm_android_permission_write_media_storage(43,0).
perm_android_permission_write_media_storage(44,0).
perm_android_permission_write_media_storage(45,0).
perm_android_permission_write_media_storage(46,0).
perm_android_permission_write_media_storage(47,0).
perm_android_permission_write_media_storage(48,0).
perm_android_permission_write_media_storage(49,0).
perm_android_permission_write_media_storage(5,0).
perm_android_permission_write_media_storage(50,0).
perm_android_permission_write_media_storage(51,0).
perm_android_permission_write_media_storage(52,0).
perm_android_permission_write_media_storage(53,0).
perm_android_permission_write_media_storage(54,0).
perm_android_permission_write_media_storage(55,0).
perm_android_permission_write_media_storage(56,0).
perm_android_permission_write_media_storage(57,0).
perm_android_permission_write_media_storage(58,0).
perm_android_permission_write_media_storage(59,1).
perm_android_permission_write_media_storage(6,0).
perm_android_permission_write_media_storage(60,0).
perm_android_permission_write_media_storage(61,0).
perm_android_permission_write_media_storage(62,1).
perm_android_permission_write_media_storage(63,1).
perm_android_permission_write_media_storage(64,0).
perm_android_permission_write_media_storage(65,0).
perm_android_permission_write_media_storage(66,0).
perm_android_permission_write_media_storage(67,0).
perm_android_permission_write_media_storage(68,0).
perm_android_permission_write_media_storage(69,0).
perm_android_permission_write_media_storage(7,1).
perm_android_permission_write_media_storage(8,1).
perm_android_permission_write_media_storage(9,0).
perm_android_permission_write_sms(0,0).
perm_android_permission_write_sms(1,0).
perm_android_permission_write_sms(10,1).
perm_android_permission_write_sms(11,0).
perm_android_permission_write_sms(12,0).
perm_android_permission_write_sms(13,0).
perm_android_permission_write_sms(14,0).
perm_android_permission_write_sms(15,0).
perm_android_permission_write_sms(16,1).
perm_android_permission_write_sms(17,0).
perm_android_permission_write_sms(18,1).
perm_android_permission_write_sms(19,0).
perm_android_permission_write_sms(2,1).
perm_android_permission_write_sms(20,1).
perm_android_permission_write_sms(21,0).
perm_android_permission_write_sms(22,0).
perm_android_permission_write_sms(23,0).
perm_android_permission_write_sms(24,0).
perm_android_permission_write_sms(25,1).
perm_android_permission_write_sms(26,0).
perm_android_permission_write_sms(27,0).
perm_android_permission_write_sms(28,0).
perm_android_permission_write_sms(29,0).
perm_android_permission_write_sms(3,0).
perm_android_permission_write_sms(30,1).
perm_android_permission_write_sms(31,0).
perm_android_permission_write_sms(32,1).
perm_android_permission_write_sms(33,0).
perm_android_permission_write_sms(34,0).
perm_android_permission_write_sms(35,0).
perm_android_permission_write_sms(36,1).
perm_android_permission_write_sms(37,0).
perm_android_permission_write_sms(38,0).
perm_android_permission_write_sms(39,1).
perm_android_permission_write_sms(4,1).
perm_android_permission_write_sms(40,0).
perm_android_permission_write_sms(41,0).
perm_android_permission_write_sms(42,1).
perm_android_permission_write_sms(43,0).
perm_android_permission_write_sms(44,0).
perm_android_permission_write_sms(45,0).
perm_android_permission_write_sms(46,0).
perm_android_permission_write_sms(47,0).
perm_android_permission_write_sms(48,0).
perm_android_permission_write_sms(49,0).
perm_android_permission_write_sms(5,1).
perm_android_permission_write_sms(50,0).
perm_android_permission_write_sms(51,0).
perm_android_permission_write_sms(52,0).
perm_android_permission_write_sms(53,0).
perm_android_permission_write_sms(54,0).
perm_android_permission_write_sms(55,0).
perm_android_permission_write_sms(56,0).
perm_android_permission_write_sms(57,0).
perm_android_permission_write_sms(58,1).
perm_android_permission_write_sms(59,0).
perm_android_permission_write_sms(6,0).
perm_android_permission_write_sms(60,0).
perm_android_permission_write_sms(61,1).
perm_android_permission_write_sms(62,1).
perm_android_permission_write_sms(63,0).
perm_android_permission_write_sms(64,0).
perm_android_permission_write_sms(65,0).
perm_android_permission_write_sms(66,0).
perm_android_permission_write_sms(67,0).
perm_android_permission_write_sms(68,0).
perm_android_permission_write_sms(69,0).
perm_android_permission_write_sms(7,1).
perm_android_permission_write_sms(8,1).
perm_android_permission_write_sms(9,0).
perm_cn_nubia_launcher_permission_read_settings(0,0).
perm_cn_nubia_launcher_permission_read_settings(1,0).
perm_cn_nubia_launcher_permission_read_settings(10,1).
perm_cn_nubia_launcher_permission_read_settings(11,0).
perm_cn_nubia_launcher_permission_read_settings(12,0).
perm_cn_nubia_launcher_permission_read_settings(13,0).
perm_cn_nubia_launcher_permission_read_settings(14,0).
perm_cn_nubia_launcher_permission_read_settings(15,0).
perm_cn_nubia_launcher_permission_read_settings(16,1).
perm_cn_nubia_launcher_permission_read_settings(17,0).
perm_cn_nubia_launcher_permission_read_settings(18,1).
perm_cn_nubia_launcher_permission_read_settings(19,0).
perm_cn_nubia_launcher_permission_read_settings(2,0).
perm_cn_nubia_launcher_permission_read_settings(20,1).
perm_cn_nubia_launcher_permission_read_settings(21,0).
perm_cn_nubia_launcher_permission_read_settings(22,0).
perm_cn_nubia_launcher_permission_read_settings(23,0).
perm_cn_nubia_launcher_permission_read_settings(24,0).
perm_cn_nubia_launcher_permission_read_settings(25,0).
perm_cn_nubia_launcher_permission_read_settings(26,0).
perm_cn_nubia_launcher_permission_read_settings(27,0).
perm_cn_nubia_launcher_permission_read_settings(28,0).
perm_cn_nubia_launcher_permission_read_settings(29,0).
perm_cn_nubia_launcher_permission_read_settings(3,0).
perm_cn_nubia_launcher_permission_read_settings(30,1).
perm_cn_nubia_launcher_permission_read_settings(31,0).
perm_cn_nubia_launcher_permission_read_settings(32,0).
perm_cn_nubia_launcher_permission_read_settings(33,0).
perm_cn_nubia_launcher_permission_read_settings(34,0).
perm_cn_nubia_launcher_permission_read_settings(35,0).
perm_cn_nubia_launcher_permission_read_settings(36,0).
perm_cn_nubia_launcher_permission_read_settings(37,0).
perm_cn_nubia_launcher_permission_read_settings(38,0).
perm_cn_nubia_launcher_permission_read_settings(39,1).
perm_cn_nubia_launcher_permission_read_settings(4,1).
perm_cn_nubia_launcher_permission_read_settings(40,0).
perm_cn_nubia_launcher_permission_read_settings(41,0).
perm_cn_nubia_launcher_permission_read_settings(42,1).
perm_cn_nubia_launcher_permission_read_settings(43,0).
perm_cn_nubia_launcher_permission_read_settings(44,0).
perm_cn_nubia_launcher_permission_read_settings(45,0).
perm_cn_nubia_launcher_permission_read_settings(46,0).
perm_cn_nubia_launcher_permission_read_settings(47,0).
perm_cn_nubia_launcher_permission_read_settings(48,0).
perm_cn_nubia_launcher_permission_read_settings(49,0).
perm_cn_nubia_launcher_permission_read_settings(5,0).
perm_cn_nubia_launcher_permission_read_settings(50,0).
perm_cn_nubia_launcher_permission_read_settings(51,0).
perm_cn_nubia_launcher_permission_read_settings(52,0).
perm_cn_nubia_launcher_permission_read_settings(53,0).
perm_cn_nubia_launcher_permission_read_settings(54,0).
perm_cn_nubia_launcher_permission_read_settings(55,0).
perm_cn_nubia_launcher_permission_read_settings(56,0).
perm_cn_nubia_launcher_permission_read_settings(57,0).
perm_cn_nubia_launcher_permission_read_settings(58,0).
perm_cn_nubia_launcher_permission_read_settings(59,1).
perm_cn_nubia_launcher_permission_read_settings(6,0).
perm_cn_nubia_launcher_permission_read_settings(60,0).
perm_cn_nubia_launcher_permission_read_settings(61,0).
perm_cn_nubia_launcher_permission_read_settings(62,1).
perm_cn_nubia_launcher_permission_read_settings(63,1).
perm_cn_nubia_launcher_permission_read_settings(64,0).
perm_cn_nubia_launcher_permission_read_settings(65,0).
perm_cn_nubia_launcher_permission_read_settings(66,0).
perm_cn_nubia_launcher_permission_read_settings(67,0).
perm_cn_nubia_launcher_permission_read_settings(68,0).
perm_cn_nubia_launcher_permission_read_settings(69,0).
perm_cn_nubia_launcher_permission_read_settings(7,1).
perm_cn_nubia_launcher_permission_read_settings(8,1).
perm_cn_nubia_launcher_permission_read_settings(9,0).
perm_com_android_launcher2_permission_read_settings(0,0).
perm_com_android_launcher2_permission_read_settings(1,0).
perm_com_android_launcher2_permission_read_settings(10,1).
perm_com_android_launcher2_permission_read_settings(11,0).
perm_com_android_launcher2_permission_read_settings(12,1).
perm_com_android_launcher2_permission_read_settings(13,0).
perm_com_android_launcher2_permission_read_settings(14,0).
perm_com_android_launcher2_permission_read_settings(15,0).
perm_com_android_launcher2_permission_read_settings(16,1).
perm_com_android_launcher2_permission_read_settings(17,0).
perm_com_android_launcher2_permission_read_settings(18,1).
perm_com_android_launcher2_permission_read_settings(19,0).
perm_com_android_launcher2_permission_read_settings(2,0).
perm_com_android_launcher2_permission_read_settings(20,1).
perm_com_android_launcher2_permission_read_settings(21,0).
perm_com_android_launcher2_permission_read_settings(22,0).
perm_com_android_launcher2_permission_read_settings(23,0).
perm_com_android_launcher2_permission_read_settings(24,0).
perm_com_android_launcher2_permission_read_settings(25,1).
perm_com_android_launcher2_permission_read_settings(26,0).
perm_com_android_launcher2_permission_read_settings(27,0).
perm_com_android_launcher2_permission_read_settings(28,0).
perm_com_android_launcher2_permission_read_settings(29,0).
perm_com_android_launcher2_permission_read_settings(3,0).
perm_com_android_launcher2_permission_read_settings(30,1).
perm_com_android_launcher2_permission_read_settings(31,0).
perm_com_android_launcher2_permission_read_settings(32,0).
perm_com_android_launcher2_permission_read_settings(33,0).
perm_com_android_launcher2_permission_read_settings(34,0).
perm_com_android_launcher2_permission_read_settings(35,0).
perm_com_android_launcher2_permission_read_settings(36,0).
perm_com_android_launcher2_permission_read_settings(37,1).
perm_com_android_launcher2_permission_read_settings(38,0).
perm_com_android_launcher2_permission_read_settings(39,1).
perm_com_android_launcher2_permission_read_settings(4,1).
perm_com_android_launcher2_permission_read_settings(40,1).
perm_com_android_launcher2_permission_read_settings(41,0).
perm_com_android_launcher2_permission_read_settings(42,1).
perm_com_android_launcher2_permission_read_settings(43,0).
perm_com_android_launcher2_permission_read_settings(44,0).
perm_com_android_launcher2_permission_read_settings(45,0).
perm_com_android_launcher2_permission_read_settings(46,1).
perm_com_android_launcher2_permission_read_settings(47,0).
perm_com_android_launcher2_permission_read_settings(48,1).
perm_com_android_launcher2_permission_read_settings(49,0).
perm_com_android_launcher2_permission_read_settings(5,1).
perm_com_android_launcher2_permission_read_settings(50,0).
perm_com_android_launcher2_permission_read_settings(51,0).
perm_com_android_launcher2_permission_read_settings(52,0).
perm_com_android_launcher2_permission_read_settings(53,0).
perm_com_android_launcher2_permission_read_settings(54,0).
perm_com_android_launcher2_permission_read_settings(55,0).
perm_com_android_launcher2_permission_read_settings(56,0).
perm_com_android_launcher2_permission_read_settings(57,0).
perm_com_android_launcher2_permission_read_settings(58,0).
perm_com_android_launcher2_permission_read_settings(59,1).
perm_com_android_launcher2_permission_read_settings(6,0).
perm_com_android_launcher2_permission_read_settings(60,0).
perm_com_android_launcher2_permission_read_settings(61,0).
perm_com_android_launcher2_permission_read_settings(62,1).
perm_com_android_launcher2_permission_read_settings(63,1).
perm_com_android_launcher2_permission_read_settings(64,0).
perm_com_android_launcher2_permission_read_settings(65,0).
perm_com_android_launcher2_permission_read_settings(66,0).
perm_com_android_launcher2_permission_read_settings(67,0).
perm_com_android_launcher2_permission_read_settings(68,0).
perm_com_android_launcher2_permission_read_settings(69,0).
perm_com_android_launcher2_permission_read_settings(7,1).
perm_com_android_launcher2_permission_read_settings(8,1).
perm_com_android_launcher2_permission_read_settings(9,0).
perm_com_android_launcher_permission_install_shortcut(0,0).
perm_com_android_launcher_permission_install_shortcut(1,0).
perm_com_android_launcher_permission_install_shortcut(10,1).
perm_com_android_launcher_permission_install_shortcut(11,1).
perm_com_android_launcher_permission_install_shortcut(12,1).
perm_com_android_launcher_permission_install_shortcut(13,1).
perm_com_android_launcher_permission_install_shortcut(14,1).
perm_com_android_launcher_permission_install_shortcut(15,0).
perm_com_android_launcher_permission_install_shortcut(16,1).
perm_com_android_launcher_permission_install_shortcut(17,1).
perm_com_android_launcher_permission_install_shortcut(18,1).
perm_com_android_launcher_permission_install_shortcut(19,1).
perm_com_android_launcher_permission_install_shortcut(2,0).
perm_com_android_launcher_permission_install_shortcut(20,1).
perm_com_android_launcher_permission_install_shortcut(21,0).
perm_com_android_launcher_permission_install_shortcut(22,1).
perm_com_android_launcher_permission_install_shortcut(23,0).
perm_com_android_launcher_permission_install_shortcut(24,1).
perm_com_android_launcher_permission_install_shortcut(25,1).
perm_com_android_launcher_permission_install_shortcut(26,1).
perm_com_android_launcher_permission_install_shortcut(27,1).
perm_com_android_launcher_permission_install_shortcut(28,1).
perm_com_android_launcher_permission_install_shortcut(29,1).
perm_com_android_launcher_permission_install_shortcut(3,0).
perm_com_android_launcher_permission_install_shortcut(30,1).
perm_com_android_launcher_permission_install_shortcut(31,1).
perm_com_android_launcher_permission_install_shortcut(32,1).
perm_com_android_launcher_permission_install_shortcut(33,1).
perm_com_android_launcher_permission_install_shortcut(34,1).
perm_com_android_launcher_permission_install_shortcut(35,1).
perm_com_android_launcher_permission_install_shortcut(36,1).
perm_com_android_launcher_permission_install_shortcut(37,1).
perm_com_android_launcher_permission_install_shortcut(38,0).
perm_com_android_launcher_permission_install_shortcut(39,1).
perm_com_android_launcher_permission_install_shortcut(4,1).
perm_com_android_launcher_permission_install_shortcut(40,1).
perm_com_android_launcher_permission_install_shortcut(41,1).
perm_com_android_launcher_permission_install_shortcut(42,1).
perm_com_android_launcher_permission_install_shortcut(43,0).
perm_com_android_launcher_permission_install_shortcut(44,1).
perm_com_android_launcher_permission_install_shortcut(45,0).
perm_com_android_launcher_permission_install_shortcut(46,1).
perm_com_android_launcher_permission_install_shortcut(47,1).
perm_com_android_launcher_permission_install_shortcut(48,1).
perm_com_android_launcher_permission_install_shortcut(49,1).
perm_com_android_launcher_permission_install_shortcut(5,1).
perm_com_android_launcher_permission_install_shortcut(50,0).
perm_com_android_launcher_permission_install_shortcut(51,1).
perm_com_android_launcher_permission_install_shortcut(52,1).
perm_com_android_launcher_permission_install_shortcut(53,0).
perm_com_android_launcher_permission_install_shortcut(54,0).
perm_com_android_launcher_permission_install_shortcut(55,1).
perm_com_android_launcher_permission_install_shortcut(56,0).
perm_com_android_launcher_permission_install_shortcut(57,1).
perm_com_android_launcher_permission_install_shortcut(58,1).
perm_com_android_launcher_permission_install_shortcut(59,1).
perm_com_android_launcher_permission_install_shortcut(6,1).
perm_com_android_launcher_permission_install_shortcut(60,0).
perm_com_android_launcher_permission_install_shortcut(61,1).
perm_com_android_launcher_permission_install_shortcut(62,1).
perm_com_android_launcher_permission_install_shortcut(63,1).
perm_com_android_launcher_permission_install_shortcut(64,1).
perm_com_android_launcher_permission_install_shortcut(65,0).
perm_com_android_launcher_permission_install_shortcut(66,1).
perm_com_android_launcher_permission_install_shortcut(67,1).
perm_com_android_launcher_permission_install_shortcut(68,0).
perm_com_android_launcher_permission_install_shortcut(69,1).
perm_com_android_launcher_permission_install_shortcut(7,1).
perm_com_android_launcher_permission_install_shortcut(8,1).
perm_com_android_launcher_permission_install_shortcut(9,0).
perm_com_android_launcher_permission_read_settings(0,0).
perm_com_android_launcher_permission_read_settings(1,0).
perm_com_android_launcher_permission_read_settings(10,1).
perm_com_android_launcher_permission_read_settings(11,1).
perm_com_android_launcher_permission_read_settings(12,1).
perm_com_android_launcher_permission_read_settings(13,0).
perm_com_android_launcher_permission_read_settings(14,1).
perm_com_android_launcher_permission_read_settings(15,0).
perm_com_android_launcher_permission_read_settings(16,1).
perm_com_android_launcher_permission_read_settings(17,1).
perm_com_android_launcher_permission_read_settings(18,1).
perm_com_android_launcher_permission_read_settings(19,1).
perm_com_android_launcher_permission_read_settings(2,1).
perm_com_android_launcher_permission_read_settings(20,1).
perm_com_android_launcher_permission_read_settings(21,0).
perm_com_android_launcher_permission_read_settings(22,0).
perm_com_android_launcher_permission_read_settings(23,0).
perm_com_android_launcher_permission_read_settings(24,0).
perm_com_android_launcher_permission_read_settings(25,1).
perm_com_android_launcher_permission_read_settings(26,1).
perm_com_android_launcher_permission_read_settings(27,0).
perm_com_android_launcher_permission_read_settings(28,0).
perm_com_android_launcher_permission_read_settings(29,1).
perm_com_android_launcher_permission_read_settings(3,0).
perm_com_android_launcher_permission_read_settings(30,1).
perm_com_android_launcher_permission_read_settings(31,0).
perm_com_android_launcher_permission_read_settings(32,0).
perm_com_android_launcher_permission_read_settings(33,0).
perm_com_android_launcher_permission_read_settings(34,1).
perm_com_android_launcher_permission_read_settings(35,1).
perm_com_android_launcher_permission_read_settings(36,1).
perm_com_android_launcher_permission_read_settings(37,1).
perm_com_android_launcher_permission_read_settings(38,0).
perm_com_android_launcher_permission_read_settings(39,1).
perm_com_android_launcher_permission_read_settings(4,1).
perm_com_android_launcher_permission_read_settings(40,1).
perm_com_android_launcher_permission_read_settings(41,1).
perm_com_android_launcher_permission_read_settings(42,1).
perm_com_android_launcher_permission_read_settings(43,1).
perm_com_android_launcher_permission_read_settings(44,1).
perm_com_android_launcher_permission_read_settings(45,0).
perm_com_android_launcher_permission_read_settings(46,1).
perm_com_android_launcher_permission_read_settings(47,0).
perm_com_android_launcher_permission_read_settings(48,1).
perm_com_android_launcher_permission_read_settings(49,1).
perm_com_android_launcher_permission_read_settings(5,1).
perm_com_android_launcher_permission_read_settings(50,0).
perm_com_android_launcher_permission_read_settings(51,0).
perm_com_android_launcher_permission_read_settings(52,0).
perm_com_android_launcher_permission_read_settings(53,0).
perm_com_android_launcher_permission_read_settings(54,0).
perm_com_android_launcher_permission_read_settings(55,1).
perm_com_android_launcher_permission_read_settings(56,0).
perm_com_android_launcher_permission_read_settings(57,1).
perm_com_android_launcher_permission_read_settings(58,1).
perm_com_android_launcher_permission_read_settings(59,1).
perm_com_android_launcher_permission_read_settings(6,1).
perm_com_android_launcher_permission_read_settings(60,0).
perm_com_android_launcher_permission_read_settings(61,1).
perm_com_android_launcher_permission_read_settings(62,1).
perm_com_android_launcher_permission_read_settings(63,1).
perm_com_android_launcher_permission_read_settings(64,1).
perm_com_android_launcher_permission_read_settings(65,0).
perm_com_android_launcher_permission_read_settings(66,0).
perm_com_android_launcher_permission_read_settings(67,1).
perm_com_android_launcher_permission_read_settings(68,0).
perm_com_android_launcher_permission_read_settings(69,0).
perm_com_android_launcher_permission_read_settings(7,1).
perm_com_android_launcher_permission_read_settings(8,1).
perm_com_android_launcher_permission_read_settings(9,0).
perm_com_android_launcher_permission_write_settings(0,0).
perm_com_android_launcher_permission_write_settings(1,0).
perm_com_android_launcher_permission_write_settings(10,1).
perm_com_android_launcher_permission_write_settings(11,0).
perm_com_android_launcher_permission_write_settings(12,0).
perm_com_android_launcher_permission_write_settings(13,0).
perm_com_android_launcher_permission_write_settings(14,1).
perm_com_android_launcher_permission_write_settings(15,0).
perm_com_android_launcher_permission_write_settings(16,1).
perm_com_android_launcher_permission_write_settings(17,1).
perm_com_android_launcher_permission_write_settings(18,1).
perm_com_android_launcher_permission_write_settings(19,0).
perm_com_android_launcher_permission_write_settings(2,0).
perm_com_android_launcher_permission_write_settings(20,1).
perm_com_android_launcher_permission_write_settings(21,0).
perm_com_android_launcher_permission_write_settings(22,0).
perm_com_android_launcher_permission_write_settings(23,0).
perm_com_android_launcher_permission_write_settings(24,0).
perm_com_android_launcher_permission_write_settings(25,1).
perm_com_android_launcher_permission_write_settings(26,1).
perm_com_android_launcher_permission_write_settings(27,0).
perm_com_android_launcher_permission_write_settings(28,0).
perm_com_android_launcher_permission_write_settings(29,0).
perm_com_android_launcher_permission_write_settings(3,0).
perm_com_android_launcher_permission_write_settings(30,1).
perm_com_android_launcher_permission_write_settings(31,0).
perm_com_android_launcher_permission_write_settings(32,0).
perm_com_android_launcher_permission_write_settings(33,0).
perm_com_android_launcher_permission_write_settings(34,0).
perm_com_android_launcher_permission_write_settings(35,0).
perm_com_android_launcher_permission_write_settings(36,0).
perm_com_android_launcher_permission_write_settings(37,0).
perm_com_android_launcher_permission_write_settings(38,0).
perm_com_android_launcher_permission_write_settings(39,1).
perm_com_android_launcher_permission_write_settings(4,1).
perm_com_android_launcher_permission_write_settings(40,0).
perm_com_android_launcher_permission_write_settings(41,1).
perm_com_android_launcher_permission_write_settings(42,1).
perm_com_android_launcher_permission_write_settings(43,0).
perm_com_android_launcher_permission_write_settings(44,0).
perm_com_android_launcher_permission_write_settings(45,0).
perm_com_android_launcher_permission_write_settings(46,0).
perm_com_android_launcher_permission_write_settings(47,0).
perm_com_android_launcher_permission_write_settings(48,0).
perm_com_android_launcher_permission_write_settings(49,0).
perm_com_android_launcher_permission_write_settings(5,1).
perm_com_android_launcher_permission_write_settings(50,0).
perm_com_android_launcher_permission_write_settings(51,0).
perm_com_android_launcher_permission_write_settings(52,0).
perm_com_android_launcher_permission_write_settings(53,0).
perm_com_android_launcher_permission_write_settings(54,0).
perm_com_android_launcher_permission_write_settings(55,1).
perm_com_android_launcher_permission_write_settings(56,0).
perm_com_android_launcher_permission_write_settings(57,1).
perm_com_android_launcher_permission_write_settings(58,0).
perm_com_android_launcher_permission_write_settings(59,1).
perm_com_android_launcher_permission_write_settings(6,1).
perm_com_android_launcher_permission_write_settings(60,0).
perm_com_android_launcher_permission_write_settings(61,1).
perm_com_android_launcher_permission_write_settings(62,1).
perm_com_android_launcher_permission_write_settings(63,1).
perm_com_android_launcher_permission_write_settings(64,0).
perm_com_android_launcher_permission_write_settings(65,0).
perm_com_android_launcher_permission_write_settings(66,0).
perm_com_android_launcher_permission_write_settings(67,0).
perm_com_android_launcher_permission_write_settings(68,0).
perm_com_android_launcher_permission_write_settings(69,0).
perm_com_android_launcher_permission_write_settings(7,1).
perm_com_android_launcher_permission_write_settings(8,1).
perm_com_android_launcher_permission_write_settings(9,0).
non_functional(Atom1):-
	Atom1=..[label,A,B],
	Atom2=..[label,A,C],
	call(Atom2),
	B \= C.
