constant(int_32,int).
constant(int_1,int).
constant(int_0,int).
constant(int_7,int).
constant(int_15,int).
constant(int_3,int).
constant(int_114,int).
constant(int_36,int).
constant(int_4,int).
constant(int_10,int).
constant(int_14,int).
constant(int_8,int).
constant(int_98,int).
constant(int_49,int).
constant(int_25,int).
constant(int_12,int).
constant(int_110,int).
constant(int_29,int).
constant(int_84,int).
constant(int_45,int).
constant(int_11,int).
constant(int_22,int).
constant(int_108,int).
constant(int_56,int).
constant(int_13,int).
constant(int_26,int).
constant(int_88,int).
constant(int_23,int).
constant(int_85,int).
constant(int_81,int).
constant(int_39,int).
constant(int_2,int).
constant(int_18,int).
constant(int_48,int).
constant(int_63,int).
constant(int_46,int).
constant(int_6,int).
constant(int_16,int).
constant(int_117,int).
constant(int_33,int).
constant(int_136,int).
constant(int_97,int).
constant(int_17,int).
constant(int_9,int).
constant(int_93,int).
constant(int_5,int).
constant(int_100,int).
constant(int_126,int).
constant(int_44,int).
constant(int_40,int).
constant(int_20,int).
constant(int_124,int).
constant(int_24,int).
constant(int_21,int).
constant(int_95,int).
constant(int_47,int).
constant(int_91,int).
constant(int_30,int).
constant(int_106,int).
constant(int_83,int).
constant(int_34,int).
constant(int_122,int).
constant(int_52,int).
constant(int_118,int).
constant(int_89,int).
constant(int_111,int).
constant(int_60,int).
constant(int_121,int).
constant(int_112,int).
constant(int_51,int).
constant(int_103,int).
constant(int_116,int).
constant(int_82,int).
constant(int_102,int).
constant(int_107,int).
constant(int_127,int).
constant(int_132,int).
constant(int_120,int).
constant(int_41,int).
constant(int_99,int).
constant(int_35,int).
constant(int_92,int).
constant(int_19,int).
constant(int_87,int).
constant(int_28,int).
constant(int_42,int).
constant(int_31,int).
constant(int_96,int).
constant(int_38,int).
constant(int_123,int).
constant(int_61,int).
constant(int_115,int).
constant(int_113,int).
constant(int_50,int).
constant(int_139,int).
constant(int_109,int).
constant(int_27,int).
constant(int_148,int).
constant(int_75,int).
constant(int_104,int).
constant(int_86,int).
constant(int_133,int).
constant(int_68,int).
constant(int_129,int).
head_pred(label,2).
body_pred(n_api_calls,2).
body_pred(suspicious_getcelllocation,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(intent_android_net_conn_connectivity_change,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(perm_android_permission_change_network_state,2).
body_pred(intent_android_intent_action_user_present,2).
body_pred(intent_com_google_android_c2dm_intent_receive,2).
body_pred(intent_com_google_firebase_instance_id_event,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(n_providers,2).
body_pred(perm_android_permission_change_wifi_state,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(perm_android_permission_write_sms,2).
body_pred(intent_com_google_firebase_messaging_event,2).
body_pred(perm_android_permission_access_wifi_state,2).
body_pred(perm_android_permission_bluetooth,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(n_permissions,2).
body_pred(perm_com_google_android_c2dm_permission_receive,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(perm_android_permission_access_coarse_location,2).
body_pred(perm_android_permission_restart_packages,2).
body_pred(intent_android_bluetooth_adapter_action_state_changed,2).
body_pred(perm_android_permission_write_settings,2).
body_pred(perm_android_permission_receive_sms,2).
body_pred(intent_android_intent_action_action_power_connected,2).
body_pred(n_used_permissions,2).
body_pred(n_services,2).
body_pred(n_urls,2).
type(label,(ex,int)).
type(n_api_calls,(ex,int)).
type(suspicious_getcelllocation,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(intent_android_net_conn_connectivity_change,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(perm_android_permission_change_network_state,(ex,int)).
type(intent_android_intent_action_user_present,(ex,int)).
type(intent_com_google_android_c2dm_intent_receive,(ex,int)).
type(intent_com_google_firebase_instance_id_event,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(n_providers,(ex,int)).
type(perm_android_permission_change_wifi_state,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(perm_android_permission_write_sms,(ex,int)).
type(intent_com_google_firebase_messaging_event,(ex,int)).
type(perm_android_permission_access_wifi_state,(ex,int)).
type(perm_android_permission_bluetooth,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(n_permissions,(ex,int)).
type(perm_com_google_android_c2dm_permission_receive,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(perm_android_permission_access_coarse_location,(ex,int)).
type(perm_android_permission_restart_packages,(ex,int)).
type(intent_android_bluetooth_adapter_action_state_changed,(ex,int)).
type(perm_android_permission_write_settings,(ex,int)).
type(perm_android_permission_receive_sms,(ex,int)).
type(intent_android_intent_action_action_power_connected,(ex,int)).
type(n_used_permissions,(ex,int)).
type(n_services,(ex,int)).
type(n_urls,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
