constant(int_0,int).
constant(int_2,int).
constant(int_5,int).
constant(int_15,int).
constant(int_13,int).
constant(int_1,int).
constant(int_6,int).
constant(int_7,int).
constant(int_14,int).
constant(int_11,int).
constant(int_17,int).
constant(int_9,int).
constant(int_4,int).
constant(int_16,int).
constant(int_3,int).
constant(int_8,int).
constant(int_18,int).
constant(int_10,int).
constant(int_19,int).
constant(int_12,int).
constant(int_20,int).
constant(int_22,int).
constant(int_21,int).
head_pred(label,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(suspicious_ljava_lang_runtime___exec,2).
body_pred(n_providers,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(perm_com_google_android_c2dm_permission_receive,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(intent_com_google_android_c2dm_intent_receive,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(suspicious_sendtextmessage,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(intent_android_intent_action_package_added,2).
body_pred(intent_com_google_firebase_instance_id_event,2).
body_pred(intent_android_intent_action_user_present,2).
body_pred(n_activities,2).
body_pred(suspicious_getcelllocation,2).
body_pred(n_used_permissions,2).
body_pred(n_receivers,2).
body_pred(intent_com_google_firebase_messaging_event,2).
body_pred(intent_android_intent_action_package_removed,2).
body_pred(intent_com_google_android_c2dm_intent_registration,2).
body_pred(n_api_calls,2).
body_pred(n_urls,2).
body_pred(n_permissions,2).
body_pred(perm_android_permission_change_configuration,2).
body_pred(suspicious_base64,2).
body_pred(intent_com_android_vending_install_referrer,2).
body_pred(intent_safiap_framework_action_to_install_iap,2).
type(label,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(suspicious_ljava_lang_runtime___exec,(ex,int)).
type(n_providers,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(perm_com_google_android_c2dm_permission_receive,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(intent_com_google_android_c2dm_intent_receive,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(suspicious_sendtextmessage,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(intent_android_intent_action_package_added,(ex,int)).
type(intent_com_google_firebase_instance_id_event,(ex,int)).
type(intent_android_intent_action_user_present,(ex,int)).
type(n_activities,(ex,int)).
type(suspicious_getcelllocation,(ex,int)).
type(n_used_permissions,(ex,int)).
type(n_receivers,(ex,int)).
type(intent_com_google_firebase_messaging_event,(ex,int)).
type(intent_android_intent_action_package_removed,(ex,int)).
type(intent_com_google_android_c2dm_intent_registration,(ex,int)).
type(n_api_calls,(ex,int)).
type(n_urls,(ex,int)).
type(n_permissions,(ex,int)).
type(perm_android_permission_change_configuration,(ex,int)).
type(suspicious_base64,(ex,int)).
type(intent_com_android_vending_install_referrer,(ex,int)).
type(intent_safiap_framework_action_to_install_iap,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
