constant(int_6,int).
constant(int_1,int).
constant(int_20,int).
constant(int_8,int).
constant(int_2,int).
constant(int_0,int).
constant(int_5,int).
constant(int_25,int).
constant(int_7,int).
constant(int_3,int).
constant(int_4,int).
constant(int_9,int).
constant(int_13,int).
constant(int_22,int).
constant(int_18,int).
constant(int_11,int).
constant(int_10,int).
constant(int_28,int).
constant(int_26,int).
constant(int_21,int).
constant(int_14,int).
constant(int_16,int).
constant(int_17,int).
constant(int_23,int).
constant(int_19,int).
constant(int_15,int).
constant(int_24,int).
constant(int_12,int).
constant(int_29,int).
head_pred(label,2).
body_pred(n_api_calls,2).
body_pred(suspicious_getexternalstoragedirectory,2).
body_pred(n_urls,2).
body_pred(n_activities,2).
body_pred(suspicious_getdeviceid,2).
body_pred(n_permissions,2).
body_pred(n_providers,2).
body_pred(suspicious_ljava_lang_system___load,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(perm_android_permission_set_wallpaper,2).
body_pred(n_used_permissions,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(n_services,2).
body_pred(n_receivers,2).
body_pred(suspicious_ljava_lang_system___loadlibrary,2).
body_pred(intent_com_google_firebase_instance_id_event,2).
body_pred(intent_com_google_android_c2dm_intent_receive,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(perm_com_google_android_c2dm_permission_receive,2).
body_pred(perm_android_permission_write_external_storage,2).
body_pred(perm_android_permission_vibrate,2).
body_pred(intent_com_android_vending_install_referrer,2).
body_pred(perm_com_android_vending_billing,2).
body_pred(intent_com_google_android_c2dm_intent_registration,2).
body_pred(perm_android_permission_read_external_storage,2).
body_pred(intent_android_intent_action_user_present,2).
body_pred(intent_safiap_framework_action_to_install,2).
body_pred(intent_android_intent_action_phone_state,2).
body_pred(intent_android_net_wifi_pick_wifi_work,2).
body_pred(intent_android_content_syncadapter,2).
type(label,(ex,int)).
type(n_api_calls,(ex,int)).
type(suspicious_getexternalstoragedirectory,(ex,int)).
type(n_urls,(ex,int)).
type(n_activities,(ex,int)).
type(suspicious_getdeviceid,(ex,int)).
type(n_permissions,(ex,int)).
type(n_providers,(ex,int)).
type(suspicious_ljava_lang_system___load,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(perm_android_permission_set_wallpaper,(ex,int)).
type(n_used_permissions,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(n_services,(ex,int)).
type(n_receivers,(ex,int)).
type(suspicious_ljava_lang_system___loadlibrary,(ex,int)).
type(intent_com_google_firebase_instance_id_event,(ex,int)).
type(intent_com_google_android_c2dm_intent_receive,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(perm_com_google_android_c2dm_permission_receive,(ex,int)).
type(perm_android_permission_write_external_storage,(ex,int)).
type(perm_android_permission_vibrate,(ex,int)).
type(intent_com_android_vending_install_referrer,(ex,int)).
type(perm_com_android_vending_billing,(ex,int)).
type(intent_com_google_android_c2dm_intent_registration,(ex,int)).
type(perm_android_permission_read_external_storage,(ex,int)).
type(intent_android_intent_action_user_present,(ex,int)).
type(intent_safiap_framework_action_to_install,(ex,int)).
type(intent_android_intent_action_phone_state,(ex,int)).
type(intent_android_net_wifi_pick_wifi_work,(ex,int)).
type(intent_android_content_syncadapter,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
