constant(int_3,int).
constant(int_0,int).
constant(int_1,int).
constant(int_2,int).
constant(int_5,int).
constant(int_4,int).
constant(int_10,int).
constant(int_7,int).
constant(int_9,int).
constant(int_11,int).
constant(int_12,int).
constant(int_6,int).
constant(int_8,int).
constant(int_15,int).
constant(int_14,int).
constant(int_13,int).
head_pred(label,2).
body_pred(n_permissions,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(n_services,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(suspicious_ljava_lang_runtime___exec,2).
body_pred(intent_android_intent_action_package_added,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(perm_com_android_launcher_permission_uninstall_shortcut,2).
body_pred(n_urls,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(suspicious_ldalvik_system_dexclassloader_,2).
body_pred(perm_android_permission_receive_boot_completed,2).
body_pred(perm_android_permission_write_external_storage,2).
body_pred(perm_com_android_launcher_permission_read_settings,2).
body_pred(suspicious_getsystemservice,2).
body_pred(perm_android_permission_receive_user_present,2).
body_pred(n_used_permissions,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(intent_com_android_vending_install_referrer,2).
body_pred(intent_android_intent_action_boot_completed,2).
body_pred(suspicious_base64,2).
body_pred(suspicious_getpackageinfo,2).
body_pred(n_api_calls,2).
body_pred(n_receivers,2).
body_pred(perm_android_permission_read_logs,2).
body_pred(perm_android_permission_access_network_state,2).
body_pred(intent_android_intent_action_action_power_connected,2).
body_pred(perm_com_android_vending_billing,2).
type(label,(ex,int)).
type(n_permissions,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(n_services,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(suspicious_ljava_lang_runtime___exec,(ex,int)).
type(intent_android_intent_action_package_added,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(perm_com_android_launcher_permission_uninstall_shortcut,(ex,int)).
type(n_urls,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(suspicious_ldalvik_system_dexclassloader_,(ex,int)).
type(perm_android_permission_receive_boot_completed,(ex,int)).
type(perm_android_permission_write_external_storage,(ex,int)).
type(perm_com_android_launcher_permission_read_settings,(ex,int)).
type(suspicious_getsystemservice,(ex,int)).
type(perm_android_permission_receive_user_present,(ex,int)).
type(n_used_permissions,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(intent_com_android_vending_install_referrer,(ex,int)).
type(intent_android_intent_action_boot_completed,(ex,int)).
type(suspicious_base64,(ex,int)).
type(suspicious_getpackageinfo,(ex,int)).
type(n_api_calls,(ex,int)).
type(n_receivers,(ex,int)).
type(perm_android_permission_read_logs,(ex,int)).
type(perm_android_permission_access_network_state,(ex,int)).
type(intent_android_intent_action_action_power_connected,(ex,int)).
type(perm_com_android_vending_billing,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
