constant(int_0,int).
constant(int_1,int).
constant(int_28,int).
constant(int_3,int).
constant(int_35,int).
constant(int_4,int).
constant(int_39,int).
constant(int_2,int).
constant(int_29,int).
constant(int_36,int).
constant(int_38,int).
constant(int_14,int).
constant(int_30,int).
constant(int_34,int).
constant(int_33,int).
constant(int_43,int).
constant(int_5,int).
constant(int_37,int).
constant(int_8,int).
constant(int_31,int).
constant(int_41,int).
constant(int_6,int).
constant(int_32,int).
constant(int_42,int).
constant(int_25,int).
constant(int_26,int).
constant(int_9,int).
head_pred(label,2).
body_pred(perm_android_permission_access_coarse_location,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(perm_android_permission_access_wifi_state,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(perm_android_permission_access_fine_location,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(n_urls,2).
body_pred(intent_com_google_firebase_instance_id_event,2).
body_pred(perm_android_permission_write_external_storage,2).
body_pred(intent_android_net_wifi_supplicant_connection_change,2).
body_pred(intent_android_intent_action_create_shortcut,2).
body_pred(intent_android_intent_action_delete,2).
body_pred(perm_com_android_launcher3_permission_read_settings,2).
body_pred(perm_com_android_launcher_permission_uninstall_shortcut,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(intent_android_net_wifi_state_change,2).
body_pred(perm_com_android_browser_permission_read_history_bookmarks,2).
body_pred(perm_com_android_launcher_permission_read_settings,2).
body_pred(intent_android_app_action_device_admin_enabled,2).
body_pred(intent_android_intent_action_external_applications_available,2).
body_pred(perm_com_android_alarm_permission_set_alarm,2).
body_pred(intent_android_intent_action_package_fully_removed,2).
body_pred(intent_android_intent_action_user_present,2).
body_pred(intent_android_intent_action_phone_state,2).
body_pred(n_services,2).
body_pred(n_providers,2).
body_pred(intent_com_android_vending_install_referrer,2).
type(label,(ex,int)).
type(perm_android_permission_access_coarse_location,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(perm_android_permission_access_wifi_state,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(perm_android_permission_access_fine_location,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(n_urls,(ex,int)).
type(intent_com_google_firebase_instance_id_event,(ex,int)).
type(perm_android_permission_write_external_storage,(ex,int)).
type(intent_android_net_wifi_supplicant_connection_change,(ex,int)).
type(intent_android_intent_action_create_shortcut,(ex,int)).
type(intent_android_intent_action_delete,(ex,int)).
type(perm_com_android_launcher3_permission_read_settings,(ex,int)).
type(perm_com_android_launcher_permission_uninstall_shortcut,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(intent_android_net_wifi_state_change,(ex,int)).
type(perm_com_android_browser_permission_read_history_bookmarks,(ex,int)).
type(perm_com_android_launcher_permission_read_settings,(ex,int)).
type(intent_android_app_action_device_admin_enabled,(ex,int)).
type(intent_android_intent_action_external_applications_available,(ex,int)).
type(perm_com_android_alarm_permission_set_alarm,(ex,int)).
type(intent_android_intent_action_package_fully_removed,(ex,int)).
type(intent_android_intent_action_user_present,(ex,int)).
type(intent_android_intent_action_phone_state,(ex,int)).
type(n_services,(ex,int)).
type(n_providers,(ex,int)).
type(intent_com_android_vending_install_referrer,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
