constant(int_0,int).
constant(int_1,int).
constant(int_9,int).
constant(int_18,int).
constant(int_12,int).
constant(int_13,int).
constant(int_16,int).
constant(int_3,int).
constant(int_6,int).
constant(int_14,int).
constant(int_7,int).
constant(int_30,int).
constant(int_31,int).
constant(int_10,int).
constant(int_19,int).
constant(int_17,int).
constant(int_2,int).
constant(int_21,int).
constant(int_4,int).
constant(int_24,int).
constant(int_8,int).
constant(int_11,int).
constant(int_34,int).
constant(int_25,int).
constant(int_15,int).
constant(int_23,int).
constant(int_5,int).
constant(int_26,int).
constant(int_28,int).
constant(int_22,int).
constant(int_27,int).
constant(int_32,int).
constant(int_40,int).
constant(int_20,int).
constant(int_43,int).
constant(int_29,int).
constant(int_36,int).
constant(int_37,int).
constant(int_33,int).
head_pred(label,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(perm_android_permission_read_logs,2).
body_pred(perm_android_permission_access_wifi_state,2).
body_pred(intent_android_intent_action_package_added,2).
body_pred(n_permissions,2).
body_pred(suspicious_ljava_lang_runtime___exec,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(n_urls,2).
body_pred(perm_android_permission_write_external_storage,2).
body_pred(suspicious_getcelllocation,2).
body_pred(intent_android_intent_action_package_removed,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(n_providers,2).
body_pred(suspicious_ljava_lang_system___load,2).
body_pred(perm_android_permission_install_packages,2).
body_pred(suspicious_ljava_lang_system___loadlibrary,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(suspicious_adb_enabled,2).
body_pred(intent_android_net_conn_connectivity_change,2).
body_pred(perm_android_permission_kill_background_processes,2).
body_pred(suspicious_sendtextmessage,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(n_activities,2).
body_pred(perm_android_permission_restart_packages,2).
body_pred(perm_com_google_android_c2dm_permission_receive,2).
body_pred(intent_com_google_android_c2dm_intent_receive,2).
body_pred(intent_co_ronash_pushe_check_tasks,2).
type(label,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(perm_android_permission_read_logs,(ex,int)).
type(perm_android_permission_access_wifi_state,(ex,int)).
type(intent_android_intent_action_package_added,(ex,int)).
type(n_permissions,(ex,int)).
type(suspicious_ljava_lang_runtime___exec,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(n_urls,(ex,int)).
type(perm_android_permission_write_external_storage,(ex,int)).
type(suspicious_getcelllocation,(ex,int)).
type(intent_android_intent_action_package_removed,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(n_providers,(ex,int)).
type(suspicious_ljava_lang_system___load,(ex,int)).
type(perm_android_permission_install_packages,(ex,int)).
type(suspicious_ljava_lang_system___loadlibrary,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(suspicious_adb_enabled,(ex,int)).
type(intent_android_net_conn_connectivity_change,(ex,int)).
type(perm_android_permission_kill_background_processes,(ex,int)).
type(suspicious_sendtextmessage,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(n_activities,(ex,int)).
type(perm_android_permission_restart_packages,(ex,int)).
type(perm_com_google_android_c2dm_permission_receive,(ex,int)).
type(intent_com_google_android_c2dm_intent_receive,(ex,int)).
type(intent_co_ronash_pushe_check_tasks,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
