constant(int_15,int).
constant(int_13,int).
constant(int_0,int).
constant(int_4,int).
constant(int_1,int).
constant(int_6,int).
constant(int_5,int).
constant(int_9,int).
constant(int_16,int).
constant(int_2,int).
constant(int_12,int).
constant(int_8,int).
constant(int_7,int).
constant(int_17,int).
constant(int_10,int).
constant(int_14,int).
constant(int_3,int).
constant(int_11,int).
constant(int_19,int).
constant(int_18,int).
head_pred(label,2).
body_pred(n_urls,2).
body_pred(n_api_calls,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(n_activities,2).
body_pred(suspicious_getdeviceid,2).
body_pred(suspicious_getexternalstoragedirectory,2).
body_pred(n_used_permissions,2).
body_pred(perm_android_permission_access_network_state,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(suspicious_ldalvik_system_dexclassloader_,2).
body_pred(n_providers,2).
body_pred(suspicious_sendtextmessage,2).
body_pred(intent_android_intent_action_package_added,2).
body_pred(suspicious_ljava_lang_system___load,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(suspicious_ljava_lang_system___loadlibrary,2).
body_pred(suspicious_getpackageinfo,2).
body_pred(n_services,2).
body_pred(perm_com_android_vending_billing,2).
body_pred(intent_com_google_android_c2dm_intent_receive,2).
body_pred(intent_android_intent_action_view,2).
body_pred(n_receivers,2).
body_pred(perm_com_google_android_c2dm_permission_receive,2).
body_pred(perm_android_permission_set_wallpaper,2).
body_pred(n_permissions,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(perm_android_permission_flashlight,2).
body_pred(intent_com_google_android_gms_measurement_upload,2).
body_pred(intent_show_lock_set_email,2).
body_pred(perm_android_permission_read_cell_broadcasts,2).
type(label,(ex,int)).
type(n_urls,(ex,int)).
type(n_api_calls,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(n_activities,(ex,int)).
type(suspicious_getdeviceid,(ex,int)).
type(suspicious_getexternalstoragedirectory,(ex,int)).
type(n_used_permissions,(ex,int)).
type(perm_android_permission_access_network_state,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(suspicious_ldalvik_system_dexclassloader_,(ex,int)).
type(n_providers,(ex,int)).
type(suspicious_sendtextmessage,(ex,int)).
type(intent_android_intent_action_package_added,(ex,int)).
type(suspicious_ljava_lang_system___load,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(suspicious_ljava_lang_system___loadlibrary,(ex,int)).
type(suspicious_getpackageinfo,(ex,int)).
type(n_services,(ex,int)).
type(perm_com_android_vending_billing,(ex,int)).
type(intent_com_google_android_c2dm_intent_receive,(ex,int)).
type(intent_android_intent_action_view,(ex,int)).
type(n_receivers,(ex,int)).
type(perm_com_google_android_c2dm_permission_receive,(ex,int)).
type(perm_android_permission_set_wallpaper,(ex,int)).
type(n_permissions,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(perm_android_permission_flashlight,(ex,int)).
type(intent_com_google_android_gms_measurement_upload,(ex,int)).
type(intent_show_lock_set_email,(ex,int)).
type(perm_android_permission_read_cell_broadcasts,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
