constant(int_0,int).
constant(int_1,int).
constant(int_5,int).
constant(int_9,int).
constant(int_6,int).
constant(int_3,int).
constant(int_4,int).
constant(int_2,int).
constant(int_8,int).
constant(int_12,int).
constant(int_7,int).
constant(int_11,int).
constant(int_14,int).
constant(int_10,int).
constant(int_13,int).
head_pred(label,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(perm_android_permission_change_network_state,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(perm_com_android_browser_permission_read_history_bookmarks,2).
body_pred(perm_android_permission_write_settings,2).
body_pred(perm_android_permission_change_wifi_state,2).
body_pred(intent_com_google_android_c2dm_intent_receive,2).
body_pred(intent_android_net_conn_connectivity_change,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(perm_com_android_launcher_permission_uninstall_shortcut,2).
body_pred(intent_android_intent_action_package_added,2).
body_pred(intent_android_intent_action_package_removed,2).
body_pred(perm_android_permission_receive_sms,2).
body_pred(perm_com_google_android_c2dm_permission_receive,2).
body_pred(n_receivers,2).
body_pred(n_services,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(n_providers,2).
body_pred(suspicious_getcelllocation,2).
body_pred(perm_android_permission_install_packages,2).
body_pred(perm_android_permission_read_logs,2).
body_pred(intent_com_android_vending_install_referrer,2).
body_pred(perm_android_permission_read_sms,2).
body_pred(perm_android_permission_access_wifi_state,2).
body_pred(perm_android_permission_access_coarse_location,2).
body_pred(suspicious_sendtextmessage,2).
type(label,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(perm_android_permission_change_network_state,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(perm_com_android_browser_permission_read_history_bookmarks,(ex,int)).
type(perm_android_permission_write_settings,(ex,int)).
type(perm_android_permission_change_wifi_state,(ex,int)).
type(intent_com_google_android_c2dm_intent_receive,(ex,int)).
type(intent_android_net_conn_connectivity_change,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(perm_com_android_launcher_permission_uninstall_shortcut,(ex,int)).
type(intent_android_intent_action_package_added,(ex,int)).
type(intent_android_intent_action_package_removed,(ex,int)).
type(perm_android_permission_receive_sms,(ex,int)).
type(perm_com_google_android_c2dm_permission_receive,(ex,int)).
type(n_receivers,(ex,int)).
type(n_services,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(n_providers,(ex,int)).
type(suspicious_getcelllocation,(ex,int)).
type(perm_android_permission_install_packages,(ex,int)).
type(perm_android_permission_read_logs,(ex,int)).
type(intent_com_android_vending_install_referrer,(ex,int)).
type(perm_android_permission_read_sms,(ex,int)).
type(perm_android_permission_access_wifi_state,(ex,int)).
type(perm_android_permission_access_coarse_location,(ex,int)).
type(suspicious_sendtextmessage,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
