constant(int_21,int).
constant(int_0,int).
constant(int_1,int).
constant(int_6,int).
constant(int_14,int).
constant(int_7,int).
constant(int_4,int).
constant(int_24,int).
constant(int_15,int).
constant(int_11,int).
constant(int_22,int).
constant(int_17,int).
constant(int_12,int).
constant(int_5,int).
constant(int_35,int).
constant(int_16,int).
constant(int_2,int).
constant(int_29,int).
constant(int_10,int).
constant(int_25,int).
constant(int_9,int).
constant(int_40,int).
constant(int_3,int).
constant(int_23,int).
constant(int_44,int).
constant(int_45,int).
constant(int_20,int).
constant(int_8,int).
constant(int_48,int).
constant(int_19,int).
constant(int_33,int).
constant(int_41,int).
constant(int_42,int).
constant(int_36,int).
constant(int_32,int).
constant(int_31,int).
constant(int_13,int).
constant(int_18,int).
constant(int_37,int).
constant(int_27,int).
constant(int_28,int).
constant(int_54,int).
constant(int_55,int).
constant(int_34,int).
constant(int_53,int).
constant(int_26,int).
constant(int_30,int).
constant(int_52,int).
constant(int_39,int).
head_pred(label,2).
body_pred(n_api_calls,2).
body_pred(suspicious_getcelllocation,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(intent_android_intent_action_user_present,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(intent_com_google_android_c2dm_intent_receive,2).
body_pred(perm_com_google_android_c2dm_permission_receive,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(intent_com_google_firebase_instance_id_event,2).
body_pred(n_providers,2).
body_pred(perm_android_permission_access_wifi_state,2).
body_pred(intent_com_google_firebase_messaging_event,2).
body_pred(perm_android_permission_access_fine_location,2).
body_pred(perm_android_permission_write_settings,2).
body_pred(perm_android_permission_receive_sms,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(perm_com_google_android_finsky_permission_bind_get_install_referrer_service,2).
body_pred(perm_android_permission_access_coarse_location,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(intent_com_android_vending_install_referrer,2).
body_pred(intent_android_net_conn_connectivity_change,2).
body_pred(perm_android_permission_change_wifi_state,2).
body_pred(n_permissions,2).
body_pred(n_services,2).
body_pred(suspicious_sendtextmessage,2).
body_pred(n_receivers,2).
body_pred(perm_android_permission_change_network_state,2).
type(label,(ex,int)).
type(n_api_calls,(ex,int)).
type(suspicious_getcelllocation,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(intent_android_intent_action_user_present,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(intent_com_google_android_c2dm_intent_receive,(ex,int)).
type(perm_com_google_android_c2dm_permission_receive,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(intent_com_google_firebase_instance_id_event,(ex,int)).
type(n_providers,(ex,int)).
type(perm_android_permission_access_wifi_state,(ex,int)).
type(intent_com_google_firebase_messaging_event,(ex,int)).
type(perm_android_permission_access_fine_location,(ex,int)).
type(perm_android_permission_write_settings,(ex,int)).
type(perm_android_permission_receive_sms,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(perm_com_google_android_finsky_permission_bind_get_install_referrer_service,(ex,int)).
type(perm_android_permission_access_coarse_location,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(intent_com_android_vending_install_referrer,(ex,int)).
type(intent_android_net_conn_connectivity_change,(ex,int)).
type(perm_android_permission_change_wifi_state,(ex,int)).
type(n_permissions,(ex,int)).
type(n_services,(ex,int)).
type(suspicious_sendtextmessage,(ex,int)).
type(n_receivers,(ex,int)).
type(perm_android_permission_change_network_state,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
