constant(int_0,int).
constant(int_1,int).
constant(int_43,int).
constant(int_25,int).
constant(int_9,int).
constant(int_49,int).
constant(int_15,int).
constant(int_37,int).
constant(int_22,int).
constant(int_44,int).
constant(int_18,int).
constant(int_2,int).
constant(int_54,int).
constant(int_4,int).
constant(int_27,int).
constant(int_20,int).
constant(int_51,int).
constant(int_28,int).
constant(int_6,int).
constant(int_30,int).
constant(int_8,int).
constant(int_40,int).
constant(int_24,int).
constant(int_38,int).
constant(int_19,int).
constant(int_39,int).
constant(int_52,int).
constant(int_13,int).
constant(int_7,int).
constant(int_60,int).
constant(int_3,int).
constant(int_26,int).
constant(int_58,int).
constant(int_17,int).
constant(int_53,int).
constant(int_23,int).
constant(int_5,int).
constant(int_56,int).
constant(int_57,int).
constant(int_46,int).
constant(int_21,int).
constant(int_47,int).
constant(int_55,int).
constant(int_41,int).
constant(int_16,int).
constant(int_48,int).
constant(int_29,int).
constant(int_12,int).
constant(int_45,int).
constant(int_33,int).
constant(int_10,int).
constant(int_61,int).
constant(int_42,int).
constant(int_11,int).
constant(int_50,int).
constant(int_14,int).
constant(int_63,int).
constant(int_31,int).
head_pred(label,2).
body_pred(intent_android_intent_action_package_added,2).
body_pred(intent_android_net_conn_connectivity_change,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(suspicious_getsubscriberid,2).
body_pred(suspicious_sendtextmessage,2).
body_pred(perm_android_permission_get_tasks,2).
body_pred(intent_android_intent_action_action_power_connected,2).
body_pred(intent_android_intent_action_action_power_disconnected,2).
body_pred(perm_com_android_launcher_permission_install_shortcut,2).
body_pred(perm_android_permission_access_coarse_location,2).
body_pred(intent_com_google_firebase_instance_id_event,2).
body_pred(perm_android_permission_write_external_storage,2).
body_pred(perm_android_permission_access_wifi_state,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(intent_android_intent_action_download_complete,2).
body_pred(perm_android_permission_read_logs,2).
body_pred(perm_com_android_launcher_permission_uninstall_shortcut,2).
body_pred(perm_android_permission_nfc,2).
body_pred(n_providers,2).
body_pred(perm_android_permission_send_sms,2).
body_pred(perm_android_webkit_permission_plugin,2).
body_pred(perm_android_permission_get_package_size,2).
body_pred(intent_android_net_wifi_wifi_state_changed,2).
body_pred(intent_com_android_vending_install_referrer,2).
body_pred(n_services,2).
body_pred(perm_android_permission_restart_packages,2).
body_pred(perm_android_permission_kill_background_processes,2).
body_pred(n_urls,2).
body_pred(n_api_calls,2).
type(label,(ex,int)).
type(intent_android_intent_action_package_added,(ex,int)).
type(intent_android_net_conn_connectivity_change,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(suspicious_getsubscriberid,(ex,int)).
type(suspicious_sendtextmessage,(ex,int)).
type(perm_android_permission_get_tasks,(ex,int)).
type(intent_android_intent_action_action_power_connected,(ex,int)).
type(intent_android_intent_action_action_power_disconnected,(ex,int)).
type(perm_com_android_launcher_permission_install_shortcut,(ex,int)).
type(perm_android_permission_access_coarse_location,(ex,int)).
type(intent_com_google_firebase_instance_id_event,(ex,int)).
type(perm_android_permission_write_external_storage,(ex,int)).
type(perm_android_permission_access_wifi_state,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(intent_android_intent_action_download_complete,(ex,int)).
type(perm_android_permission_read_logs,(ex,int)).
type(perm_com_android_launcher_permission_uninstall_shortcut,(ex,int)).
type(perm_android_permission_nfc,(ex,int)).
type(n_providers,(ex,int)).
type(perm_android_permission_send_sms,(ex,int)).
type(perm_android_webkit_permission_plugin,(ex,int)).
type(perm_android_permission_get_package_size,(ex,int)).
type(intent_android_net_wifi_wifi_state_changed,(ex,int)).
type(intent_com_android_vending_install_referrer,(ex,int)).
type(n_services,(ex,int)).
type(perm_android_permission_restart_packages,(ex,int)).
type(perm_android_permission_kill_background_processes,(ex,int)).
type(n_urls,(ex,int)).
type(n_api_calls,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
