constant(int_123,int).
constant(int_0,int).
constant(int_1,int).
constant(int_3,int).
constant(int_33,int).
constant(int_14,int).
constant(int_16,int).
constant(int_13,int).
constant(int_2,int).
constant(int_139,int).
constant(int_5,int).
constant(int_41,int).
constant(int_15,int).
constant(int_9,int).
constant(int_120,int).
constant(int_4,int).
constant(int_18,int).
constant(int_34,int).
constant(int_27,int).
constant(int_12,int).
constant(int_176,int).
constant(int_23,int).
constant(int_20,int).
constant(int_11,int).
constant(int_6,int).
constant(int_8,int).
constant(int_94,int).
constant(int_25,int).
constant(int_95,int).
constant(int_28,int).
constant(int_17,int).
constant(int_7,int).
constant(int_154,int).
constant(int_43,int).
constant(int_10,int).
constant(int_32,int).
constant(int_105,int).
constant(int_19,int).
constant(int_24,int).
constant(int_142,int).
constant(int_49,int).
constant(int_137,int).
constant(int_46,int).
constant(int_147,int).
constant(int_38,int).
constant(int_170,int).
constant(int_37,int).
constant(int_22,int).
constant(int_21,int).
constant(int_136,int).
constant(int_108,int).
constant(int_45,int).
constant(int_26,int).
constant(int_104,int).
constant(int_47,int).
constant(int_125,int).
constant(int_54,int).
constant(int_115,int).
constant(int_118,int).
constant(int_31,int).
constant(int_117,int).
constant(int_173,int).
constant(int_42,int).
constant(int_144,int).
constant(int_121,int).
constant(int_40,int).
constant(int_124,int).
constant(int_35,int).
constant(int_114,int).
constant(int_102,int).
constant(int_109,int).
constant(int_30,int).
constant(int_29,int).
constant(int_162,int).
constant(int_36,int).
constant(int_44,int).
constant(int_132,int).
constant(int_107,int).
constant(int_167,int).
constant(int_116,int).
constant(int_179,int).
constant(int_96,int).
constant(int_150,int).
constant(int_152,int).
constant(int_100,int).
constant(int_112,int).
constant(int_110,int).
constant(int_166,int).
constant(int_39,int).
constant(int_122,int).
constant(int_97,int).
constant(int_143,int).
constant(int_138,int).
constant(int_175,int).
constant(int_161,int).
constant(int_180,int).
constant(int_127,int).
constant(int_106,int).
head_pred(label,2).
body_pred(n_urls,2).
body_pred(suspicious_getcelllocation,2).
body_pred(perm_android_permission_system_alert_window,2).
body_pred(intent_com_inmobi_share_id,2).
body_pred(suspicious_getcellsignalstrength,2).
body_pred(suspicious_system_bin_su,2).
body_pred(perm_android_permission_read_phone_state,2).
body_pred(suspicious_ldalvik_system_pathclassloader_,2).
body_pred(n_providers,2).
body_pred(n_services,2).
body_pred(suspicious_ljava_lang_system___loadlibrary,2).
body_pred(perm_android_permission_receive_boot_completed,2).
body_pred(intent_com_google_firebase_instance_id_event,2).
body_pred(suspicious_ljava_lang_system___load,2).
body_pred(intent_android_intent_action_boot_completed,2).
body_pred(perm_android_permission_mount_unmount_filesystems,2).
body_pred(intent_com_google_firebase_messaging_event,2).
body_pred(perm_com_google_android_finsky_permission_bind_get_install_referrer_service,2).
body_pred(n_api_calls,2).
body_pred(n_activities,2).
body_pred(suspicious_getsimcountryiso,2).
body_pred(perm_com_google_android_providers_gsf_permission_read_gservices,2).
body_pred(perm_com_android_vending_billing,2).
body_pred(n_used_permissions,2).
body_pred(n_permissions,2).
body_pred(n_receivers,2).
body_pred(intent_com_google_android_c2dm_intent_registration,2).
body_pred(intent_com_google_android_gms_appinvite_action_preview,2).
body_pred(perm_android_permission_vibrate,2).
body_pred(intent_com_google_android_gms_iid_instanceid,2).
type(label,(ex,int)).
type(n_urls,(ex,int)).
type(suspicious_getcelllocation,(ex,int)).
type(perm_android_permission_system_alert_window,(ex,int)).
type(intent_com_inmobi_share_id,(ex,int)).
type(suspicious_getcellsignalstrength,(ex,int)).
type(suspicious_system_bin_su,(ex,int)).
type(perm_android_permission_read_phone_state,(ex,int)).
type(suspicious_ldalvik_system_pathclassloader_,(ex,int)).
type(n_providers,(ex,int)).
type(n_services,(ex,int)).
type(suspicious_ljava_lang_system___loadlibrary,(ex,int)).
type(perm_android_permission_receive_boot_completed,(ex,int)).
type(intent_com_google_firebase_instance_id_event,(ex,int)).
type(suspicious_ljava_lang_system___load,(ex,int)).
type(intent_android_intent_action_boot_completed,(ex,int)).
type(perm_android_permission_mount_unmount_filesystems,(ex,int)).
type(intent_com_google_firebase_messaging_event,(ex,int)).
type(perm_com_google_android_finsky_permission_bind_get_install_referrer_service,(ex,int)).
type(n_api_calls,(ex,int)).
type(n_activities,(ex,int)).
type(suspicious_getsimcountryiso,(ex,int)).
type(perm_com_google_android_providers_gsf_permission_read_gservices,(ex,int)).
type(perm_com_android_vending_billing,(ex,int)).
type(n_used_permissions,(ex,int)).
type(n_permissions,(ex,int)).
type(n_receivers,(ex,int)).
type(intent_com_google_android_c2dm_intent_registration,(ex,int)).
type(intent_com_google_android_gms_appinvite_action_preview,(ex,int)).
type(perm_android_permission_vibrate,(ex,int)).
type(intent_com_google_android_gms_iid_instanceid,(ex,int)).
:- clause(C), #count{V : var_type(C,V,ex)} != 1.
body_pred(P,1):- constant(P,_).
type(P,(T,)):- constant(P,T).
